### ISSUE TITLE
Exception in setTimeout callback: { MongoError: cursor id xyz not found - since upgrade to 1.7.0.3

### ISSUE THREAD

**Issue by a4xrbj1** [meteor/meteor#10107]
Since we upgrade to Meteor 1.7.0.3 (which is the only change we did) we are experiencing repeated errors of "Exception in setTimeout callback: { MongoError: cursor id xyz not found" in MongoDb queries that worked without any problems for the last two years.

We are on MongoDb version 3.6.6 on Atlas - not sure if that is the cause as it seems that Meteor 1.7.0.3 still uses 3.6.4

Log files are below (copied from our Galaxy server):

```
vj3jw
2018-07-28 02:33:37+02:00Exception in setTimeout callback: { MongoError: cursor id 176950257865 not found
vj3jw
2018-07-28 02:33:37+02:00 at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:593:63
vj3jw
2018-07-28 02:33:37+02:00 at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:516:16)
vj3jw
2018-07-28 02:33:37+02:00 at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:552:5)
vj3jw
2018-07-28 02:33:37+02:00 at emitMessageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:10)
vj3jw
2018-07-28 02:33:37+02:00 at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:452:17)
vj3jw
2018-07-28 02:33:37+02:00 at emitOne (events.js:116:13)
vj3jw
2018-07-28 02:33:37+02:00 at TLSSocket.emit (events.js:211:7)
vj3jw
2018-07-28 02:33:37+02:00 at addChunk (_stream_readable.js:263:12)
vj3jw
2018-07-28 02:33:37+02:00 at readableAddChunk (_stream_readable.js:250:11)
vj3jw
2018-07-28 02:33:37+02:00 at TLSSocket.Readable.push (_stream_readable.js:208:10)
vj3jw
2018-07-28 02:33:37+02:00 at TLSWrap.onread (net.js:597:20)
vj3jw
2018-07-28 02:33:37+02:00 => awaited here:
vj3jw
2018-07-28 02:33:37+02:00 at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
vj3jw
2018-07-28 02:33:37+02:00 at Promise.asyncApply (packages/mongo/mongo_driver.js:1034:11)
vj3jw
2018-07-28 02:33:37+02:00 at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
vj3jw
2018-07-28 02:33:37+02:00 => awaited here:
vj3jw
2018-07-28 02:33:37+02:00 at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
vj3jw
2018-07-28 02:33:37+02:00 at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1083:12)
vj3jw
2018-07-28 02:33:37+02:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1097:22)
vj3jw
2018-07-28 02:33:37+02:00 at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:879:44)
vj3jw
2018-07-28 02:33:37+02:00 at JobQueue.worker (server/oneToManyDecode.js:273:17)
vj3jw
2018-07-28 02:33:37+02:00 at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
vj3jw
2018-07-28 02:33:37+02:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
vj3jw
2018-07-28 02:33:37+02:00 at packages/meteor.js:620:25
vj3jw
2018-07-28 02:33:37+02:00 at runWithEnvironment (packages/meteor.js:1356:24)
vj3jw
2018-07-28 02:33:37+02:00 name: 'MongoError',
vj3jw
2018-07-28 02:33:37+02:00 message: 'cursor id 176950257865 not found',
vj3jw
2018-07-28 02:33:37+02:00 ok: 0,
vj3jw
2018-07-28 02:33:37+02:00 errmsg: 'cursor id 176950257865 not found',
vj3jw
2018-07-28 02:33:37+02:00 code: 43,
vj3jw
2018-07-28 02:33:37+02:00 codeName: 'CursorNotFound',
vj3jw
2018-07-28 02:33:37+02:00 operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1532738011 },
vj3jw
2018-07-28 02:33:37+02:00 '$clusterTime':
vj3jw
2018-07-28 02:33:37+02:00 { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1532738011 },
vj3jw
2018-07-28 02:33:37+02:00 signature: { hash: [Object], keyId: [Object] } } }
```

This is just one occurrence, it has happened on other functions as well. Like I said, the production server is running flawless for almost 2 years and it all started with our upgrade of Meteor (which went fine on the frontend server).

Thanks in advance for your help,

Andreas (Numero Pte Ltd)

**Comment by pmcochrane** [comment]
I too am getting this error when running bulk updates. There is another issue here similar to this #9944 Try having a look at that. Don't think there is a fix at present  apart from doing queries in smaller batches but my experience is that is not reliable. Only noticed this after upgrading to 7

**Comment by a4xrbj1** [comment]
Thank you @pmcochrane - that confirms we're not the only one experiencing this problem in production system only. It also points to 3.6.6 and we would like to upgrade MongoDb 4 anytime soon as the new feature of multi-document ACID transactions will help us a lot (I guess everyone has to fight against the missing referential integrity in NoSQL db's).

**Comment by koszta** [comment]
This is a bug in mongodb and not meteor. First they thought they fixed it entirely in 3.6.6. But this problem is clearly still occurring. So there is no fix since May...

See the related tickets:
https://jira.mongodb.org/browse/SERVER-34810
https://jira.mongodb.org/browse/SERVER-36808

**Comment by a4xrbj1** [comment]
Sorry but the problem is for us fixed and it only showed up when we upgraded Meteor.

I have to disagree with your view.

Maybe other people have a different case but ours is solved since we moved to beta versions and now RC

**Comment by Isarstyle** [comment]
FYI had the same issue with a collection with >30000 datasets, with meteor 1.6.1 and mongodb 3.6.
Tried mongodb 4, did not help, updated meteor to 1.7.0.5 still the same issue. 
for me the current latest meteor release 1.7.1. rc -5 is working without errors, still on mongodb 4.
hope that helps anyone with the same error.

**Comment by a4xrbj1** [comment]
Might be a bit OT but any tips on upgrading to Mongodb 4? We are very interesting in transactions

Thanks for your feedback, same for us in that the RC’s are working fine

**Comment by Isarstyle** [comment]
@a4xrbj1 You can wrap a multidocument operation inside an transaction function, but i am not sure the current mongodriver supplied by meteor does support that. Also transactions do not work on replica sets at the moment, keep that in mind if you use a sharded cluster. On my testing server all operations that worked before continued to work so far, feel free to contact me directly for further questions.

**Comment by etyp** [comment]
@a4xrbj1 which RC are you on that you got it working?

**Comment by SimonSimCity** [comment]
@a4xrbj1 Since you said that it came when updating to Meteor `1.7.0.3`, which version were you on before?

In version `1.7.0` Meteor updated the MongoDB driver to `` which could well have caused this. I also got this error-message and am now using a newer version of the driver, which will be available in Meteor `1.7.1`. Since I can't wait for the release for this fix, I wrote some lines of how you can do it yourself: https://github.com/meteor/meteor/issues/9944#issuecomment-420542042 Please try it out.

@Isarstyle Your issue looks exactly like what I solved in the comment linked here. Transactions are first supported in MongoDB 4.0, which needs the driver in version `3.1.0`, so you would anyways have to update, whereby the update in itself fixed the bug for me.
