### ISSUE TITLE
[1.7.0.4][Edge][Accounts] srp.js - Expected identifier, string or number

### ISSUE THREAD

**Issue by Rhywden** [meteor/meteor#10143]
OS: Win10
Browser: Edge
Also happens in 1.7.1-beta by the way. 

Basically, due to the error in the topic title, the whole Accounts / Accounts-Password package does not work. What I'm getting to see is this (disregard the yellow stuff) when I pull up a login page and then actually try to login:

![image](https://user-images.githubusercontent.com/84586/43961868-68bd0880-9cb6-11e8-81d8-cf29ec6d1772.png)

I do not see the same error on Chrome.

Repo can be found here:
https://github.com/Rhywden/nawischule

**Comment by benjamn** [comment]
Possibly related to #10136—any thoughts, @jamesmillerburgess?

**Comment by benjamn** [comment]
Ah yes, it looks like `srp/package.js` needs to `api.use("ecmascript")`. I can fix that.

**Comment by benjamn** [comment]
Ok, this should be fixed if you run `meteor update srp` in your application directory (to get the latest version, 1.0.12). Please feel free to reopen if you still have any trouble.

**Comment by Rhywden** [comment]
Naw, just tried it, it's fixed now. Thanks!

**Comment by jamesmillerburgess** [comment]
I think this would have been caught if I had added a unit test. Sorry!

I will do a better job of that going forward.

**Comment by sylido** [comment]
Just encountered this, still stuck at 1.6.1.1 it somehow updated SRP to 1.0.11 but the bug is still present there - any way to patch that version as 1.0.12 was, there are some restrictions that prevent me from going to 12 at the moment.

**Comment by pierre-moire** [comment]
@sylido Please note that you can probably downgrade srp (add it to .meteor/packages and edit .meteor/versions) and fix this bug by using the 1.0.10 version if it is constraints-compatible for you. I have done this myself and fixed the issue I had on Edge.

**Comment by mahaveer0496** [comment]
I'm using `Meteor@1.6.1.3` with these packages
```
meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.1.18                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-js@2.1.0    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.8.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.3            # Server-side component of the `meteor shell` command

kadira:flow-router
react-meteor-data
chrismbeckett:toastr
twbs:bootstrap
accounts-password@1.3.6
meteorhacks:subs-manager
seba:minifiers-autoprefixer
natestrauser:font-awesome
zimme:active-route
dynamic-import
session
email
matb33:collection-hooks
edgee:slingshot
kadira:dochead
underscore@1.0.10
todda00:friendly-slugs
fourseven:scss
aldeed:collection2@3.0.0
static-html
```
I still have this error, [this particular line](https://github.com/meteor/meteor/blob/master/packages/srp/srp.js#L80) doesn't get transpiled, and breaks the app in production in Edge.
