### ISSUE TITLE
1.7.0.5 css minifier removes leading /

### ISSUE THREAD

**Issue by znewsham** [meteor/meteor#10247]
Only visible when running in production, or with `--production`, if you add some css:

```
body {
  padding: 10px;
  font-family: sans-serif;
  background-image: url(/somewhere.png);
}
```

it gets minified as
```
  background-image: url(somewhere.png);
```

The issue exists upto at least 1.8-rc.15

**Comment by znewsham** [comment]
It seems this only causes problems if you also use a non "/" ROOT_URL

**Comment by nathan-muir** [comment]
Did a bit of digging into this.

 - The original css bundling system converts all embedded url's to relative, as the browser would then load assets relative to the bundle url.
 - With the new `modules` system (eg, `import './my.css'`), css is packaged as a js module. When imported, it gets injected into the DOM, and urls are interpreted based on the current url (when injected)

Created a minimal reproduction here:  https://github.com/nathan-muir/meteor-css-minifier-absolute-url-error

**Comment by janka** [comment]
Adding a / to the ROOT_URL does not make a difference, btw.

**Comment by nathan-muir** [comment]
@janka Did you try

>  Move your css outside `/imports`, it will get included in the main css bundle

URL's will be relative to the main bundle then, and it should be fixed

**Comment by znewsham** [comment]
@nathan-muir I use sccss and it all gets compiled into a single file - its still broken

**Comment by nathan-muir** [comment]
@znewsham Your bug report is accurate ; it will convert all `url`'s to relative in any CSS/LESS/SASS.

It's just that, relative URL's should be OK so long as the `.less`/`.sass`/`.css` files are outside the `imports` directory of your app. (Due to some special treatment by the meteor compiler).

Ideally, absolute URL's would be kept in tact. (However there's an issue with absolute URL's and `WebAppInternals.setBundledJsCssPrefix`)

**Comment by znewsham** [comment]
@nathan-muir this is a pretty recent change - we have 4 applications and maybe 60/70 scss files that would need to be moved to correct this - so its not really a viable solution. 

I just re-read your previous comment, it seems that youre saying that imported scss files get inline inserted into the head? That seems like an odd way of doing things. Its not something I've noticed though

**Comment by nathan-muir** [comment]
You can confirm with the browsers 'inspect element' tool, but you can also search your JS bundle for the css file names, eg:

```js
"green-less.less":function(e,s,r){r.exports=e("meteor/modules").addStyles(".less-green-button{width:100px;height:100...
```

The issue appeared after meteor added support for `dynamic-import`. Though it took a while to surface as most people load the app at the root URL.

The justification seems to be, if you're dynamically importing `page.jsx` which imports `page.scss`. You don't want `page.scss` inflating your app bundle (so it needs some way of dynamically loading).

I think that meteor's dynamic import could be done better; by producing several static artefacts instead of using POST to fetch modules. Which would probably fix this issue.

---

It might be easier than you think to remove the `/imports` directory. The new `mainModule` support in `package.json` makes it a breeze. I feel your pain though, I had to do this for a 2x ~200kLOC meteor apps.

If it's not viable to reorganise your app, your alternative is to fork/patch the meteor compiler (or get a change upstreamed) (Offending lines: https://github.com/meteor/meteor/blob/master/tools/isobuild/compiler-plugin.js#L683-L688)

**Comment by znewsham** [comment]
@nathan-muir thanks for taking the time to explain, so the files don't all need to be in a single scss file - they just have to be outside the imports directory? As you say, that does sound do-able. it could just be a case of renaming the imports directory and fixing the two files that point to it (client.js and server.js).

To be honest, its a little disapointing this hasn't been fixed yet - Meteor makes quite a lot of noise about its backwards compatibilty - this is the fourth breaking change I've had - that has also impacted many other people - after upgrading past 1.7, three of those changes are still unfixed.

**Comment by janka** [comment]
> @janka Did you try
> 
> > Move your css outside `/imports`, it will get included in the main css bundle
> 
> URL's will still be relative, but resolved against the css bundle url then (not the initial page url), and it should be fixed

@nathan-muir now I did. And it worked, thank you!

I moved all the `@font-face` declarations to `/client/main.css` which was made for the occasion. All other CSS/LESS is in `/imports`

For my code as it is now it is not a big deal, but it doesn't sit right with me. I do use dynamic imports, so my clients initial payload now is a little bit bigger as a few fonts are not used on the login page.

When I one day move everything out of `/imports`, will that mean I can put `@font-face` back in place?

**Comment by janus-reith** [comment]
I hope that this not considered expected behaviour pf the minifier and will be fixed.

I don't consider moving things out of my /imports folder a real solution here, as it doesn't seem to solve the underlying issue here?

If I define an absolute path to an image in a CSS/LESS/SASS file that I have somewhere in my imports directory, I should be able to use that css on every route I want to.

Like, if I use a background for a Header, the chances are high that I would like to use that Header on another route aswell.

It shouldn't be converted to relative path, or if this beheaviour really should be forced, the output should accomodate to the current route (although this would probably mean overhead).

**Comment by tducasse** [comment]
Just encountered the same problem after upgrading to 1.8.0. Is the only viable solution to put my `.scss` files outside of `/imports`? I'm using React, and I think it would make more sense to keep them near my component files.

**Comment by ddaydd** [comment]
same METEOR@1.8.0.2

**Comment by nathan-muir** [comment]
> Just encountered the same problem after upgrading to 1.8.0. Is the only viable solution to put my `.scss` files outside of `/imports`? I'm using React, and I think it would make more sense to keep them near my component files.

As of Meteor 1.7 you can get rid of the old auto-import behaviour, and hence the `imports` directory by specifying some directives in your `package.json`.

```
"meteor": {
  "mainModule": {
    "client": "client/main.js",
    "server": "server/main.js"
  }
}
```

Then you can just move everything out of imports directory; And this CSS problem gets solved too.

As per https://github.com/meteor/meteor/issues/10247#issuecomment-432116487 there are other possible solutions - but they all have drawbacks and aren't likely to be implemented.

**Comment by markreid** [comment]
So can someone explain _why_ this change was implemented? There seems to be a solution of "just restructure your entire project" but there's not a lot of explanation as to how this change benefits anyone... Interested to know why the decision was made?

**Comment by nathan-muir** [comment]
@markreid I'm sure meteor doesn't want to break your css `url`'s. It's just an unlucky bug created by the intersection of a few features.

**Comment by Shelagh-Lewins** [comment]
As I'm only using a few background images, I was able to avoid restructuring my project by using inline styles to reference the file in my public/images folder:

<div
	style={{ 'backgroundImage': 'url(\'/images/myfile.png\')' }}
>
</div>

I'm using React and ES6 imports, but my files are in a folder named imports. If this issue really isn't going to be fixed, it needs at the least to be documented in the tutorials.

**Comment by vparpoil** [comment]
I can confirm the issue still being present in latest release 1.8.2

**Comment by afrokick** [comment]
The reason is https://github.com/meteor/meteor/blob/devel/packages/minifier-css/minifier.js#L257-L271

**Comment by dmitry-sher** [comment]
Still relevant in Meteor 1.10.2

**Comment by dr-dimitru** [comment]
Posting new comment to keep this issue open as we still experiencing it in the latest Meteor release

**Comment by dr-dimitru** [comment]
TL;TR;

Add to the `<head>`: 

```html
<base href="/">
```

After hitting a wall with this one, during my research I found out (*thumb up* if it helped you):

- 👎 Leading slash is removed only when application is `build` or `--production` flag is used
- 👎 Removing/adding trailing slash to `ROOT_URL` makes no difference
- 👎 Moving SASS/SCSS out of `import` — __doesn't work__
- 👎 `ROOT_URL_PATH_PREFIX="/"` __doesn't work__
- 👎 `WebAppInternals.setBundledJsCssPrefix('/')` __doesn't work__
- 🤔 `WebAppInternals.setBundledJsCssPrefix(Meteor.absoluteUrl('/'))` __doesn't work__, while it might if it would be used by minifier
- 👎 `<base href="${Meteor.absoluteUrl()}">` does the trick but not simple to implement in Blaze
- ❤️ `<base href="/">` — Solve this annoying issue!
- 🤔 `WebAppInternals.setBundledJsCssUrlRewriteHook()` __doesn't work__, but might, if it would be used by minifier
- 🧐 This behavior [is not going to change](https://github.com/meteor/meteor/blob/devel/packages/minifier-css/minifier.js#L270): 

```js
      // ... Instead we transform absolute paths to make them relative to the
      // merged CSS, leaving to the browser the responsibility to calculate
      // the final resource links (by adding the application deployment
      // prefix, here `myapp/`, if applicable).
```

**Comment by StorytellerCZ** [comment]
Since we have a resolution for the issue I'm closing this issue. This is a good issue to submit to the docs or guide if someone is interested.

**Comment by vlasky** [comment]
You cannot imagine how much time I have wasted in trying to solve this problem until I randomly stumbled upon dr-dimitru's solution. It's now mid 2025 and this obscure tidbit really needs to be documented!

**Comment by dr-dimitru** [comment]
@vlasky I'm glad it worked for you. What meteor version are you on?
@StorytellerCZ shall we push it forward in the docs?

**Comment by StorytellerCZ** [comment]
Please do
