### ISSUE TITLE
[1.10-beta.7] startup in dev mode MongoServerSelectionError: Server selection timed out after 30000 ms

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#10925]
Just spun this up 1.10-beta.5 today with my project.

I got through all the typical stuff. I had to deal w/ some packages that were not yet 1.9/10 compatible: `qualia:profile`, `apollo`, removed chimpy, and `meteor npm rm/add bcrypt`

But when I try to start my application in _development mode_ I am getting the following error from connecting to Mongo:

```
MongoServerSelectionError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (/Users/jbb/.meteor/packages/npm-mongo/.3.5.0-beta110.5.kly54m.aladc++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/topology.js:448:30)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'MongoServerSelectionError',
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map { '127.0.0.1:3001' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: 30,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 8
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

I tried it with a freshly `meteor create`d app and it works fine. 

I tried `meteor reset` but it doesn't help.

I should also note that I can connect to the new mongo server using `mongo localhost:3001`

And `rs.status()` returns:

```
{
	"set" : "meteor",
	"date" : ISODate("2020-02-14T23:35:31.798Z"),
	"myState" : 1,
	"term" : NumberLong(1),
	"syncingTo" : "",
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 1,
	"writeMajorityCount" : 1,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1581723329, 1),
			"t" : NumberLong(1)
		},
		"lastCommittedWallTime" : ISODate("2020-02-14T23:35:29.966Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1581723329, 1),
			"t" : NumberLong(1)
		},
		"readConcernMajorityWallTime" : ISODate("2020-02-14T23:35:29.966Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1581723329, 1),
			"t" : NumberLong(1)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1581723329, 1),
			"t" : NumberLong(1)
		},
		"lastAppliedWallTime" : ISODate("2020-02-14T23:35:29.966Z"),
		"lastDurableWallTime" : ISODate("2020-02-14T23:35:29.966Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1581723279, 1),
	"lastStableCheckpointTimestamp" : Timestamp(1581723279, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "electionTimeout",
		"lastElectionDate" : ISODate("2020-02-14T23:28:42.607Z"),
		"termAtElection" : NumberLong(1),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(0, 0),
			"t" : NumberLong(-1)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1581722922, 1),
			"t" : NumberLong(-1)
		},
		"numVotesNeeded" : 1,
		"priorityAtElection" : 100,
		"electionTimeoutMillis" : NumberLong(10000),
		"newTermStartDate" : ISODate("2020-02-14T23:28:43.633Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2020-02-14T23:28:43.646Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "127.0.0.1:3001",
			"ip" : "127.0.0.1",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 418,
			"optime" : {
				"ts" : Timestamp(1581723329, 1),
				"t" : NumberLong(1)
			},
			"optimeDate" : ISODate("2020-02-14T23:35:29Z"),
			"syncingTo" : "",
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1581722922, 2),
			"electionDate" : ISODate("2020-02-14T23:28:42Z"),
			"configVersion" : 1,
			"self" : true,
			"lastHeartbeatMessage" : ""
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1581723329, 1),
		"signature" : {
			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
			"keyId" : NumberLong(0)
		}
	},
	"operationTime" : Timestamp(1581723329, 1)
}
```

Workaround: I got it working by forking the mongo package and commenting out the newly added `useUnifiedTopology` parameter on the Mongo connection. I noticed in another thread that some users were saying they had intermittent problems with this new parameter.

**Comment by hexsprite** [comment]
Seems like these two issues may be related: https://github.com/meteor/meteor/issues/10924

**Comment by hexsprite** [comment]
This is still occurring in 1.10-beta.7 release.

**Comment by benjamn** [comment]
@hexsprite When you commented out `useUnifiedTopology`, did you start seeing any deprecation warnings, as mentioned in the comment above that option? https://github.com/meteor/meteor/commit/282b16ed16f416d0e399657348616cc3ff408ea8

**Comment by hexsprite** [comment]
@benjamn No, I just checked and I don't see any deprecation warnings when running in development mode against the local MongoDB, nor do I see it when running in development mode but connecting to an Atlas instance with replicas.

**Comment by hexsprite** [comment]
I should note that I'm also seeing this warning when running tests that i never saw before:

```
Step #7 - "test-all": Error starting Mongo (2 tries left): Primary not writable after one minute.
Step #7 - "test-all": Last replica set status:
Step #7 - "test-all": {"set":"meteor","date":"2020-02-26T20:02:32.433Z","myState":1,"term":1,"syncingTo":"","syncSourceHost":"","syncSourceId":-1,"heartbeatIntervalMillis":2000,"majorityVoteCount":1,"writeMajorityCount":1,"optimes":{"lastCommittedOpTime":{"ts":"6797848106080665601","t":1},"lastCommittedWallTime":"2020-02-26T20:02:30.377Z","readConcernMajorityOpTime":{"ts":"6797848106080665601","t":1},"readConcernMajorityWallTime":"2020-02-26T20:02:30.377Z","appliedOpTime":{"ts":"6797848106080665601","t":1},"durableOpTime":{"ts":"6797848106080665601","t":1},"lastAppliedWallTime":"2020-02-26T20:02:30.377Z","lastDurableWallTime":"2020-02-26T20:02:30.377Z"},"lastStableRecoveryTimestamp":"6797847977231646721","lastStableCheckpointTimestamp":"6797847977231646721","electionCandidateMetrics":{"lastElectionReason":"electionTimeout","lastElectionDate":"2020-02-26T20:01:09.359Z","termAtElection":1,"lastCommittedOpTimeAtElection":{"ts":"0","t":-1},"lastSeenOpTimeAtElection":{"ts":"6797847758188314625","t":-1},"numVotesNeeded":1,"priorityAtElection":100,"electionTimeoutMillis":10000,"newTermStartDate":"2020-02-26T20:01:10.375Z","wMajorityWriteAvailabilityDate":"2020-02-26T20:01:10.390Z"},"members":[{"_id":0,"name":"127.0.0.1:9001","ip":"127.0.0.1","health":1,"state":1,"stateStr":"PRIMARY","uptime":85,"optime":{"ts":"6797848106080665601","t":1},"optimeDate":"2020-02-26T20:02:30.000Z","syncingTo":"","syncSourceHost":"","syncSourceId":-1,"infoMessage":"could
Step #7 - "test-all": not find member to sync
Step #7 - "test-all": from","electionTime":"6797847758188314626","electionDate":"2020-02-26T20:01:09.000Z","configVersion":1,"self":true,"lastHeartbeatMessage":""}],"ok":1,"$clusterTime":{"clusterTime":"6797848106080665601","signature":{"hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyId":0}},"operationTime":"6797848106080665601"}
Step #7 - "test-all": => Started MongoDB.
```

It may be in both cases that it's related to some way in which startup code is executing in my app. I wonder if I could profile what's happening during startup.

**Comment by benjamn** [comment]
Good news: it looks like `mongodb@3.5.4` fixed this bug! https://jira.mongodb.org/browse/NODE-2467

**Comment by benjamn** [comment]
This should now be fixed, without having to remove the `useUnifiedTopology` option:
```
meteor update --release 1.10-rc.0
```
🤞

**Comment by hexsprite** [comment]
Not fixed. But I am suspecting that it has something to do with my application code and may not be a bug in Meteor. I'm wondering if something that initializes at load might be slow (outside of a `Meteor.startup` call) and that this might be triggering a race condition related to DB initialization. That could indeed be a bug but it's not totally clear yet... I need to profile my startup code but `qualia:profile` startup profiling is broken in 1.10 and 1.8.3 as well ;(

**Comment by hexsprite** [comment]
That said, it's very suspicious that the simple inclusion of commenting out the useUnifiedTopology suffices to solve this....

**Comment by klaussner** [comment]
I added the `useUnifiedTopology` option only because of the deprecation. I don't think there are any other noticeable benefits at the moment. The [warning](https://github.com/mongodb/node-mongodb-native/blob/69d10ba5623731d5c87bd3009a14004442c8fa94/lib/operations/connect.js#L250-L251) is shown in the console because currently [all deprecation warnings are silenced in the `npm-mongo` package](https://github.com/meteor/meteor/blob/573c9dc478b15df70fa26c4a753d62077df1b066/packages/npm-mongo/wrapper.js#L1-L9).

@hexsprite Does the "Primary not writable after one minute." error also disappear if you remove `useUnifiedTopology`?

**Comment by hexsprite** [comment]
Trying to run it from the checkout since there's no release yet. Strangely it's complaining about a conflict with `jquery@3.0.0` yet I haven't explicitly listed that as a requirement (though some atmosphere packages use 1.x) and it's working fine with rc.0....

**Comment by hexsprite** [comment]
OK, when I said there was no release of rc.1 it's because meteor was warning me that there was no release for my platform. But I just figured out that doing `meteor reset` solved that. Weird! Anyway, just tested rc.1 and it now starts perfectly in development. Just pushed my changes to CI and I'll let you know if this also solves any issues I had there as well...

**Comment by hexsprite** [comment]
Still getting this warning in CI tests that wasn't present in 1.8.3. It does successfully run through to completion however so if anything it's just slowing things down. But still I'm curious why that might happen...?

```
Step #7 - "test-all": Error starting Mongo (2 tries left): Primary not writable after one minute.
Step #7 - "test-all": Last replica set status:
Step #7 - "test-all": {"set":"meteor","date":"2020-02-28T18:28:36.093Z","myState":1,"term":1,"syncingTo":"","syncSourceHost":"","syncSourceId":-1,"heartbeatIntervalMillis":2000,"majorityVoteCount":1,"writeMajorityCount":1,"optimes":{"lastCommittedOpTime":{"ts":"6798566061403799553","t":1},"lastCommittedWallTime":"2020-02-28T18:28:32.724Z","readConcernMajorityOpTime":{"ts":"6798566061403799553","t":1},"readConcernMajorityWallTime":"2020-02-28T18:28:32.724Z","appliedOpTime":{"ts":"6798566061403799553","t":1},"durableOpTime":{"ts":"6798566061403799553","t":1},"lastAppliedWallTime":"2020-02-28T18:28:32.724Z","lastDurableWallTime":"2020-02-28T18:28:32.724Z"},"lastStableRecoveryTimestamp":"6798566061403799553","lastStableCheckpointTimestamp":"6798566061403799553","electionCandidateMetrics":{"lastElectionReason":"electionTimeout","lastElectionDate":"2020-02-28T18:27:31.711Z","termAtElection":1,"lastCommittedOpTimeAtElection":{"ts":"0","t":-1},"lastSeenOpTimeAtElection":{"ts":"6798565799410794497","t":-1},"numVotesNeeded":1,"priorityAtElection":100,"electionTimeoutMillis":10000,"newTermStartDate":"2020-02-28T18:27:32.723Z","wMajorityWriteAvailabilityDate":"2020-02-28T18:27:32.733Z"},"members":[{"_id":0,"name":"127.0.0.1:9001","ip":"127.0.0.1","health":1,"state":1,"stateStr":"PRIMARY","uptime":66,"optime":{"ts":"6798566061403799553","t":1},"optimeDate":"2020-02-28T18:28:32.000Z","syncingTo":"","syncSourceHost":"","syncSourceId":-1,"infoMessage":"could
Step #7 - "test-all": not find member to sync
Step #7 - "test-all": from","electionTime":"6798565799410794498","electionDate":"2020-02-28T18:27:31.000Z","configVersion":1,"self":true,"lastHeartbeatMessage":""}],"ok":1,"$clusterTime":{"clusterTime":"6798566061403799553","signature":{"hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyId":0}},"operationTime":"6798566061403799553"}
Step #7 - "test-all": => Started MongoDB.
```

**Comment by benjamn** [comment]
@hexsprite Sorry I got interrupted yesterday before finishing the `-rc.1` release, but glad to hear the original issue seems to be resolved now.

The only exact search result that I can find for `Primary not writable after one minute` is coming from [this line of the Reaction Commerce code](https://github.com/reactioncommerce/reaction/blob/4cd078521b9ce382a4d7b37f00b0e93309524497/src/core/util/initReplicaSet.js#L82). Are you using Reaction? Do you think it's possible they need to make some updates to adjust to MongoDB 4.2?

**Comment by hexsprite** [comment]
Nope, I am not using reaction commerce.

**Comment by klaussner** [comment]
The error is thrown in `run-mongo.js` (Reaction just copied this part to their project): https://github.com/meteor/meteor/blob/573c9dc478b15df70fa26c4a753d62077df1b066/tools/runners/run-mongo.js#L714-L717 Maybe the one minute timeout is too optimistic for your CI environment.

**Comment by hexsprite** [comment]
@klaussner ok good to know. I should note that it didn't happen the last time I ran my tests in CI. Either way it's not a major deal. If it becomes an issue maybe I'll submit a PR to be able to configure this value via ENV

**Comment by hexsprite** [comment]
OK I think we solved this issue. Thank you both!
