### ISSUE TITLE
HMR + React fails when new import added

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#11324]
Hi, if I edit a file located `/imports/client/file.jsx` by adding an import to the top (eg `import MdEdit from '@meronex/icons/md/MdEdit'`), I get the following error:
```
hot-module-replacement.js?hash=22d8cfbe1ca1509fc13b6f268883287a7c6b3b6c:560 HMR: Error while applying changes: Error: Cannot find module '/node_modules/@meronex/icons/md/MdAdd.js'
    at makeMissingError (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:234)
    at fileEvaluate (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:377)
    at Module.require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:270)
    at Module.moduleLink [as link] (modules.js?hash=b0fbe8d3321feb4cd1fe8c6393e2f99e7757ef22:375)
    at module ((index):27)
    at hot-module-replacement.js?hash=22d8cfbe1ca1509fc13b6f268883287a7c6b3b6c:370
    at fileEvaluate (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:388)
    at Module.require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:270)
    at require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:310)
    at hot-module-replacement.js?hash=22d8cfbe1ca1509fc13b6f268883287a7c6b3b6c:557
```
From there I have to do a manual refresh.

Is there a way around this? CC @zodern

**Comment by arggh** [comment]
I bumped into this same problem with Svelte. Adding a new import throws the same error and I have to kill Meteor & restart.

**Comment by filipenevola** [comment]
AFAIK Svelte is not using the same HMR system of React so it would be a different problem.

Zodern is going to take a look at this issue.

**Comment by zodern** [comment]
I haven't been able to reproduce it so far. I see the error, but then it always reloads the page since it currently isn't able to add the new files from `node_modules` using HMR. Since it isn't reloading the page for you, it seems the imported files are already part of the js bundle, or Meteor isn't detecting or correctly handling the added files.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Comment by jasongrishkoff** [comment]
This is still an issue for me. Have to refresh if I add a new import.
If I add this line to `/imports/client/songs/home.jsx':
`import About from "/imports/client/messages/about"`
Then I get this error:
```
HMR: Error while applying changes: Error: Cannot find module '/imports/client/messages/about.jsx'
    at makeMissingError (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:234)
    at fileEvaluate (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:377)
    at Module.require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:270)
    at Module.moduleLink [as link] (modules.js?hash=8ad747c1c9f61ad4571e13f7cd4d7199799acc6b:372)
    at module ((index):25)
    at hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:404
    at fileEvaluate (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:388)
    at Module.require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:270)
    at require (modules-runtime-hot.js?hash=d12281259a6cee99786429a66f76b05f13449c7f:310)
    at hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:591
overrideMethod @ react_devtools_backend.js:2574
applyChangeset @ hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:594
(anonymous) @ hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:254
handleMessage @ hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:253
(anonymous) @ hot-module-replacement.js?hash=f879925ea8ee47e7a1f40213e08fc846afa4792f:347
```

**Comment by zodern** [comment]
@jasongrishkoff was `/imports/client/messages/about.jsx` already dynamically imported by the app, or only used by modules that were dynamically imported?

There were some scenarios I overlooked that could cause this error when adding imports for modules that were already dynamic imports.

**Comment by jasongrishkoff** [comment]
Hi @zodern.  It was only used in the modules that was dynamically imported.  It was not part of the initial app bundle, nor imported by any other component.

**Comment by jasongrishkoff** [comment]
Hi @zodern - any luck reproducing this?  It's gotten to the point where updating a scss file at `/functions/scss/file.scss` forces me to wait ~30 seconds to update, then refreshes the page.  I feel like I'm back in the old days of 2016 Meteor :(

**Comment by zodern** [comment]
I am able to reproduce.

>  It's gotten to the point where updating a scss file at /functions/scss/file.scss forces me to wait ~30 seconds to update, then refreshes the page.

This looks like a separate issue. 30 seconds is much longer than a rebuild should take. Could you please create a new issue with a profile from [zodern:build-profiler](https://packosphere.com/zodern/build-profiler) or the output from a rebuild with the `METEOR_PROFILE=20` env var set?

**Comment by jasongrishkoff** [comment]
@zodern struggling to get that package installed. Keep encountering an error:
```
no member named 'GetCallUid' in 'v8::CpuProfileNode'
```

**Comment by zodern** [comment]
@jasongrishkoff sorry, I forgot it hadn't been updated for Meteor 2.3. It should work now.

**Comment by jasongrishkoff** [comment]
Thanks! Attached is a log from when I updated a scss file in `/imports/scss/`. Just replace the `txt` extension with `cpuprofile` and I'm hoping it'll work!
[client-rebuild.txt](https://github.com/meteor/meteor/files/7123455/client-rebuild.txt)

**Comment by jasongrishkoff** [comment]
Anything I can do to help get this one resolved? Still happens in v2.5 for me.

**Comment by italojs** [comment]
[Abandoned]  
Please inform us if this occurs in Meteor 3.x.

**Comment by zodern** [comment]
We haven't fixed the issue of a dynamically imported module becoming a statically imported module.

**Comment by make-github-pseudonymous-again** [comment]
@zodern ?

**Comment by make-github-pseudonymous-again** [comment]
@zodern Still relevant?

**Comment by nachocodoner** [comment]
With the new Meteor–Rspack integration this issue may be gone, since a new HMR is now used for the app code (Meteor 3.4 with rspack package).

However, it may still be happening in Meteor’s bundler itself (when no rspack enabled), so the problem is likely there. I’ll keep it open until we can confirm.

**Comment by make-github-pseudonymous-again** [comment]
@nachocodoner Any progress?

**Comment by nachocodoner** [comment]
Meteor 3.4 with Rspack integration is already delivered. Check out the new docs to adopt it: https://docs.meteor.com/about/modern-build-stack/rspack-bundler-integration.html. On my end, I don't see any issues when using Rspack, refreshes work automatically in all scenarios, including dynamic imports.

Can anybody else confirm with Rspack?

If it only happens on the legacy Meteor bundler for app code, we can create a new `legacy-build-stack` tag to track issues that are solved by Rspack (`modern-build-stack`) but still happen on the legacy stack. If the Meteor-Rspack era sticks in a future, we can later close everything under those tags, if we don't get as this fixes on the meantime.
