### ISSUE TITLE
When attempting to create an app, creation fails with an error.

### ISSUE THREAD

**Issue by Haaffin** [meteor/meteor#11526]
Hello! I'm currently using version 2.3 of meteor and on windows 10.

When I try to use the create app command, it throws this error and I have absolutely no idea what's happening. 

```
C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: semver is not a constructor
    at Function.PV.compare (C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:215:26)
    at C:\tools\packaging\catalog\catalog-remote.js:578:28
    at Array.sort (<anonymous>)
    at RemoteCatalog.getSortedVersionRecords (C:\tools\packaging\catalog\catalog-remote.js:577:20)
    at LayeredCatalog._returnFirst (C:\tools\packaging\catalog\catalog.js:190:12)
    at LayeredCatalog.getSortedVersionRecords (C:\tools\packaging\catalog\catalog.js:202:17)
    at CS.CatalogLoader._getSortedVersionRecords (packages/constraint-solver.js:333:20)
    at CS.CatalogLoader.loadAllVersions (packages/constraint-solver.js:362:26)
    at CS.CatalogLoader.loadAllVersionsRecursive (packages/constraint-solver.js:395:10)
    at CS.Input.loadFromCatalog (packages/constraint-solver.js:562:17)
    at packages/constraint-solver.js:2285:15
    at Function.time (C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
    at CS.PackagesResolver.resolve (packages/constraint-solver.js:2282:13)
    at C:\tools\project-context.js:623:35
    at Function.time (C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
    at C:\tools\project-context.js:619:19
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\project-context.js:591:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._resolveConstraints (C:\tools\project-context.js:590:13)
    at C:\tools\project-context.js:362:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:352:18)
    at C:\tools\project-context.js:344:12
    at Function.run (C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:343:13)
    at C:\tools\cli\commands.js:832:20
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
    at Command.func (C:\tools\cli\commands.js:806:8)
    at C:\tools\cli\main.js:1528:15
```

**Comment by StorytellerCZ** [comment]
Hello @Haaffin 
Thanks for the report! I'll look into it. Just out of curiosity, are you running this in command prompt or power shell?

**Comment by StorytellerCZ** [comment]
@Haaffin also have you tried again recently? Windows is still a bit fickle with Node related stuff from my experience.

**Comment by Haaffin** [comment]
> @Haaffin also have you tried again recently? Windows is still a bit fickle with Node related stuff from my experience.

I've tried multiple times and have even tried completely reinstalling. the only thing i haven't done is try and use different app types if you want me to do that ( : 

i've only tried it with React

**Comment by zodern** [comment]
This might be the same issue as https://github.com/meteor/meteor/issues/10930#issuecomment-678580436 where it is loading the wrong version of an npm package. @Haaffin is there a `node_modules` directory in any of the folders between `C:\` and `C:\Users\haaff\AppData\Local` with `semver`?

**Comment by Haaffin** [comment]
@zodern there is, yeah.

**Comment by zodern** [comment]
If you are able to remove it, it should fix the error.

**Comment by Haaffin** [comment]
No longer getting the "semver is not a constructor" error but instead im getting this: 

```
=> Errors while creating your project

While loading package webapp@1.11.0:
error: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
rebuild --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command
"C:\\Users\\haaff\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\haaff\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\haaff\AppData\Local\.meteor\packages\webapp\1.11.0\npm\node_modules\.temp-1m141cc.uw6y\node_modules\posix
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\haaff\AppData\Roaming\npm-cache\_logs\2021-07-13T03_09_38_878Z-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\haaff\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command
"C:\\Users\\haaff\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\haaff\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.3.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd
C:\Users\haaff\AppData\Local\.meteor\packages\webapp\1.11.0\npm\node_modules\.temp-1m141cc.uw6y\node_modules\posix
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\haaff\AppData\Roaming\npm-cache\_logs\2021-07-13T03_09_38_878Z-debug.log
```

**Comment by StorytellerCZ** [comment]
Update WebApp, that should fix the issue.

**Comment by Haaffin** [comment]
Even after updating WebApp it still throws the same error so unfortunately I think I'm gonna have to pass on Meteor (,:

**Comment by StorytellerCZ** [comment]
`Failed at the posix@4.2.0 install script` shows that you don't have the latest WebApp version where this has been removed. What is the latest error you are getting? Have you updated to Meteor 2.3.2?

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while. This looks like an issue that has been fixed already in the latest Meteor as well.
