### ISSUE TITLE
Sow oplog tailing on ATLAS (reactivated issue)

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#11578]
Hi, I'd like to issue #10808, because a couple of other folks (like me) are facing similar issues and I just became aware of that thread. Please also have a look at this thread in the forum:

https://forums.meteor.com/t/horrible-degradation-of-performance-using-galaxy-and-mongodb-atlas/56435

What alerted me in particular, was that the thread in #10808 also mentions other behavior that I have been facing with Meteor on ATLAS, besides the frequent "Query Targeting: Scanned Objects / Returned has gone above 1000" emails, which I get nearly every day.

1. Someone mentioned that sometimes Meteor method callbacks are not invoked, if a subscription for the same collection was running. This might be related this thread:
https://forums.meteor.com/t/meteor-login-method-never-invokes-callback-blocks-all-future-rpc-calls/36305

2. Another comment mentions that sometimes `update` DDP messages are not being sent to the client. This is a behavior I noticed in my Unity frontend that uses a low-level DDP protocol. Especially on Android, it happens quite often that `update` is not received after a `login` message is being sent.

I think this whole issue is worth looking into.

**Comment by StorytellerCZ** [comment]
@derwaldgeist I agree with your assessment that this needs to be looked into, but for me personally I have no idea where to even start. Right now @filipenevola is working on mongo package with no fibers so he will probably have the most insight on what is going on there.

**Comment by derwaldgeist** [comment]
@StorytellerCZ Unfortunately, I have no idea either. :-/ I am only able to describe the symptoms, but have no clue about the root cause. But I think the hint in #10808 that it might be related to the oplog query itself might be a good one. I don't understand much about oplog, though.

**Comment by StorytellerCZ** [comment]
@renanccastro Oplog will need a closer look then.

**Comment by renanccastro** [comment]
Hi, @derwaldgeist. There is, unfortunately, a lot of causes for this, one can be the scarcity of read/write ticket, which would cause a lot of issues in your DB. This is caused when you have a lot of observers.
But anyway, talking about this issue in specific, it seems very hard to reproduce... We would need a more isolated reproduction, without external services, to try to fix it, also because I had issues with MongoDB atlas suddenly dropping the performance.
Also, redis-oplog is a strong workaround for this issue. With it, you won't tail the oplog anymore, and in theory, you would solve all issues reported.
We also have the plan to port our default strategy from oplog to change streams, which would lead us to more performance, and more reliability when scaling.
If you could try redis-oplog and see if it solves the reported issues it would be good, so we know we are on the right path.

**Comment by HoptimizeME** [comment]
Hi, we're also experiencing issues but was wondering which versions of mongo,/ mongo driver/ meteor are affected by this.

Thanks 😊

**Comment by applew** [comment]
Hey @timturnerwhcc, I too have this problem just surface when I upgraded from Meteor 1.12.1 to 2.6.1. I'm hosted on Atlas with a M10 and it is running MongoDB 4.2.18. I'm curious as to what version you are running? Was thinking that things might resolve if I upgraded to MongoDB 5.0, but haven't pulled the trigger.

Also, I saw that someone had success by turning on "Require Index for All Queries" in the server configuration (it is one of the parameters when you Edit Configuration for your cluster), but I'm cautious to try it out.
<img width="880" alt="Screen Shot 2022-02-28 at 9 23 39 PM" src="https://user-images.githubusercontent.com/6322038/156110275-69ea23ce-24df-4e8e-b5ef-c3abd1266c7b.png">

**Comment by timturnerwhcc** [comment]
@applew We're running MongoDB 4.2.18 on that cluster. I'm also wondering if it may be resolved with an upgrade to 5.0, but we haven't finished updating all of our MongoDB drivers to support 5.0 yet.

I would be hesitant to require indexes for all queries - if I understand correctly, the Oplog collection is fixed-size and doesn't allow indexes, so it would just hide the issue by erroring instead of doing scans. Doesn't seem like a real resolution to me.

**Comment by timturnerwhcc** [comment]
I have updated our MongoDB Instances on Atlas to use MongoDB 5.0 and am still seeing this issue, unfortunately.

**Comment by applew** [comment]
I decided to roll back to Meteor 2.5.6 and the issue does not exist. According to the changelog, it looks like some work was done in version 2.6+ to the oplog for MongoDB 5 support, which may explain this behavior.
 
I'm going to wait it out and see if a newer release might fix this problem. I'd love to be on the cutting edge, but sometimes it hurts.

**Comment by derwaldgeist** [comment]
This problem does not to be caused by high loads. It appears even if there is literally zero to none load on the server. Fortunately, nothing seems to be affected, the server is just running fine, without noticable problems. Still, these messages from Mongo on your mailbox are a bit annoying.

**Comment by lynchem** [comment]
It seems actually that the issue is when nothing happens for whatever the oplog 'window' is. See #11993 as well. I think we're also downgrading to 2.5.6 until we get a bit of clarity on this.

**Comment by derwaldgeist** [comment]
> It seems actually that the issue is when nothing happens for whatever the oplog 'window' is. See #11993 as well. I think we're also downgrading to 2.5.6 until we get a bit of clarity on this.

This might actually explain the behaviour.

**Comment by zzaacchh** [comment]
Our team runs many production Meteor apps, and we started seeing Atlas (MongoDB V4.2) clusters consuming 100% relentlessly whenever any app connected from _any version_ of Meteor after V2.6.  

We spent some time with an engineer from the MongoDB Engineering team this week to figure this out.  We learned:

- The solution, generally, is to upgrade Atlas servers to run at least MongoDB v4.4. 
- I think the underlying problem is that more recent versions of Meteor use a more recent underlying MongoDB Node.js driver, and I believe this driver is dropping an `allowReplay` parameter on oplog queries.  Apparently, not having this parameter makes the oplog queries super inefficient on Mongo V4.2, because Meteor can't hang on to a cursor without it.  And that means ever few seconds Meteor will connect and do a full collection scan of the oplog.

For what it's worth, from talking to the MongoDB engineer, it sounds like the situation that @derwaldgeist documents is another equally important but *separate* thing to worry about.  It affects some of my applications too.  As I understand it, if you have an infrequently used meteor app (like a staging server) that connects to a shared MongoDB cluster, then oplog queries can become horrifically inefficient.  Oplogs are shared by all databases on the cluster, and are capped/circular buffers, so another chatty application on the cluster can flush out mention of the infrequently used database.  And that prevents the app hanging on to oplog query cursors, as hanging on requires at least one from the initial matching oplog document.  So, the infrequently used app will hammer Mongo every few seconds, asking for a full collection scan of the oplog.

**Comment by lynchem** [comment]
Good to get further confirmation of this @zzaacchh. Should be fixed in the 2.8 beta thanks to a fix in v4.9 of the driver. [See this](https://github.com/meteor/meteor/issues/11993#issuecomment-1210989103) for more detail.

**Comment by derwaldgeist** [comment]
@zzaacchh Thanks for sharing these insights. Very interesting. Just wanted to note, though, that I am not using a shared cluster for my app and still see these warnings.

**Comment by cormip** [comment]
OK, here are some more clues for you all:

1. Meteor 2.9.0
2. MongoDB v5.0.14 (Atlas)
3. My app was being developed on a DigitalOcean droplet using an M2 Atlas cluster. Not once did I EVER see a "Query Targeting: Scanned Objects / Returned has gone above 1000" warning.
4. Built out the production environment on a pair of load-balanced AWS EC2 servers with an M10 Cluster and I'm getting DOZENS of these warnings every day.
5. The database is tiny, and in fact, the production database is smaller than the development database.
6. Virtually no one is using the app yet.
7. Both systems (dev/prod) use similar connect strings:
MONGO_URL: 'mongodb+srv://myapp_[prod|dev]:################@myapp-cluster-[prod|dev].abcdefg.mongodb.net/myapp?retryWrites=true&w=majority&readPreference=primary'
MONGO_OPLOG_URL: 'mongodb+srv://oplog_reader:##################@myapp-cluster-[prod|dev].abcdefg.mongodb.net/local?retryWrites=true&w=majority&readPreference=primary'

Any ideas how to address this?

**Comment by cormip** [comment]
Hmmm, just had a thought. In this context (oplog tailing) I see that occasionally 0 documents are being returned:

![image](https://user-images.githubusercontent.com/1108728/208252011-3d03fac0-46a3-452a-bed7-e7968eaab89d.png)

The ratio of scanned / returned objects would be infiniti (greater than 1000), but is there even really a problem? An unused app might very well have no oplog records over a period of time. I'm tempted to simply disable this alert, since there's really nothing Meteor can do about it?

**Comment by paulincai** [comment]
@cormip your oplog URI seems wrong. I think there should be nothing after "/local". You don't write to oplog not have a primary on it.

**Comment by cormip** [comment]
@paulincai good catch. I updated the oplog URL, but it made no difference.

**Comment by evolross** [comment]
We have a production app that gets the "Query Targeting: Scanned Objects / Returned has gone above 1000" errors a few times per day.

We traced it to use of the Meteor package [aldeed:tabular](https://github.com/Meteor-Community-Packages/meteor-tabular#searching). Its search implementation ends up doing a giant `$or` of a series of `$regex` queries for every field of the datatable in order to perform a search across every column of the table on the server. This causes Mongo to spit out this error as the query is not optimized.

I talked to Mongo and they said that pattern would indeed cause the issue and it should be rewritten to use their newer Text Search solution. So for us, this will take forking the `aldeed:tabular` package. 

Not sure if this is your issue but thought I would add this just in case.

**Comment by cormip** [comment]
@evolross our app does not use that Meteor package. Looking at the details of the alert, it's definitely oplog queries that are triggering the alert and not queries performed on data collections.

**Comment by belfigue** [comment]
We have this problem too. We are hosted on Atlas with an M10 and running on MongoDB 5.0.14. We receive tens of emails a day from Atlas with this alert. I can see from the logs that the Oplog tailing is the culprit. I've just updated from Meteor 2.7.3 to Meteor 2.10.0 (unlikely it will have any effect on this issue).

Did anybody manage to solve it??

**Comment by Grubba27** [comment]
Hey @belfigue, can you share what packages you are using? perhaps you are having the same issue as @evolross with the Meteor package [aldeed:tabular](https://github.com/Meteor-Community-Packages/meteor-tabular#searching)

**Comment by derwaldgeist** [comment]
Not using this tabular package either.
