### ISSUE TITLE
[2.5.6] import of npm library gives empty object

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#11900]
I'm blocked. I can't run a Meteor app because import of a library returns an empty object, as described in all these threads:

- https://github.com/meteor/meteor/issues/10065
- https://forums.meteor.com/t/importing-from-npm-returns-an-empty-object/44491
- https://github.com/thereactivestack-legacy/meteor-webpack/issues/235
- https://stackoverflow.com/questions/55382092/importing-gitlab-package-from-meteorjs-returns-empty-object
- https://forums.meteor.com/t/solved-require-import-npm-require-all-return-empty-object/50153/6
- https://ethereum.stackexchange.com/questions/60335/web3-empty-object-server-side-in-meteor
- https://github.com/VulcanJS/Vulcan/issues/2580

I don't know if this ever worked in previous versions of Meteor, but from the threads we can see the issue celebrated quite a few birthdays already.

I think @benjamn might have the most clue as to what this might be caused by; he architected Meteor's module system.

Reproduction:

**Comment by trusktr** [comment]
Added a reproduction.

**Comment by eric-burel** [comment]
@trusktr Awesome that you have a simple reproduction!

For the record, this seems to specifically affect ES Modules (Material UI in my case), and the server build.

I recently hit an unexpected issue recently when exploring ES modules, with NPM packages and Next.js: files with ".js" extensions maybe interpreted differently depending if `"type": "module"` is enabled or not.
- If "type": "module" is enabled in package.json, ".js" is treated as ES modules
- If not, eg when using conditional exports instead, ".js" is treated as CommonJS

Maybe it's related? Like Meteor wrongly consider the package as CommonJS during the server build.

**Comment by trusktr** [comment]
> Maybe it's related? Like Meteor wrongly consider the package as CommonJS during the server build.

Meteor doesn't understand Node.js ESM or package.json `exports` fields yet (https://github.com/meteor/meteor/issues/10906).


> I saw that you have the package `dayjs` as a `devDependencies`.
> 
> I tested moving it to `dependencies`, then running `rm -rf node_modules`, then `meteor npm install`, and it was fixed.

Ah, moving it from `devDependencies` to `dependencies` worked.

I think this might be considered a bug because all other tools (Webpack, Rollup, Parcel, etc) all successfully build an app regardless of which field dependencies are in.

Another way to look at this is that having runtime dependencies in `dependencies` namely a thing for libraries that run in Node and need to use Node's lookup algorithm. In this sense, Meteor is treating my app like a library, not an app.

If I were to write a plain Node.js app, with `devDependencies`, then run `npm install` and finally `node server.js` (or similar to start the server), it would work. On this note, it is intuitive for Meteor to also work as expected.

The only time `devDependencies` are ignored in the Node ecosystem is when `npm install`ing a library, and in that case `devDependencies` are left behind.

**Comment by eric-burel** [comment]
@denihs incredible I would never had imagined this to be the issue! Thanks a lot! It's consistent with my own experience with Material UI, as it was installed as a dev dependency in Vulcan. We use a Meteor app as a kind of a monorepo just for dev, so we have a lot of dev dependencies.

**Comment by trusktr** [comment]
This needs to be marked as a bug.

**Comment by denihs** [comment]
Hi @trusktr,

This was fixed on this [PR](https://github.com/meteor/meteor/pull/11954). 

We have already released a new version with this code.

Could you test it?

Just update your app with:

```
meteor update --release 2.7-rc.4
```

**Comment by trusktr** [comment]
After performing `meteor update` to `2.7.1`, the above reproduction still fails with an error:

```js
❯ meteor --exclude-archs "web.browser.legacy, web.cordova"
[[[[[ ~/deleteme/mapapp ]]]]]                 

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
W20220407-20:53:38.794(-7)? (STDERR) /home/trusktr/.meteor/packages/meteor-tool/.2.7.1.tb7vzh.a2uk++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20220407-20:53:38.799(-7)? (STDERR) 						throw(ex);
W20220407-20:53:38.799(-7)? (STDERR) 						^
W20220407-20:53:38.799(-7)? (STDERR) 
W20220407-20:53:38.799(-7)? (STDERR) Error: Cannot find module "/node_modules/dayjs/esm/index.js". Try installing the npm package or make sure it is not a devDependency.
W20220407-20:53:38.799(-7)? (STDERR)     at Module.useNode (packages/modules-runtime.js:647:11)
W20220407-20:53:38.799(-7)? (STDERR)     at module (packages/modules.js:215:8)
W20220407-20:53:38.799(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20220407-20:53:38.799(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20220407-20:53:38.799(-7)? (STDERR)     at Module.moduleLink [as link] (/home/trusktr/.meteor/packages/modules/.0.18.0.1i29cl.iter++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
W20220407-20:53:38.800(-7)? (STDERR)     at module (imports/day.js:1:1)
W20220407-20:53:38.800(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20220407-20:53:38.800(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20220407-20:53:38.800(-7)? (STDERR)     at Module.moduleLink [as link] (/home/trusktr/.meteor/packages/modules/.0.18.0.1i29cl.iter++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
W20220407-20:53:38.800(-7)? (STDERR)     at module (server/imports/fixtures.js:1:1)
W20220407-20:53:38.800(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20220407-20:53:38.800(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20220407-20:53:38.800(-7)? (STDERR)     at Module.moduleLink [as link] (/home/trusktr/.meteor/packages/modules/.0.18.0.1i29cl.iter++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
W20220407-20:53:38.800(-7)? (STDERR)     at module (server/main.js:1:1)
W20220407-20:53:38.800(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20220407-20:53:38.800(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
^C
```

In particular, note that the missing file does exist:

```                                                                                                                                                                    
❯ ls -l node_modules/dayjs/esm/index.js
-rw-rw-r-- 1 trusktr trusktr 12274 Apr  7 20:52 node_modules/dayjs/esm/index.js
```

**Comment by trusktr** [comment]
Here is a new reproduction that includes the meteor update:

```
git clone git@github.com:trusktr/mapapp.git
cd mapapp
git checkout meteor-issue-11900-2
npm install
meteor --exclude-archs "web.browser.legacy, web.cordova"
```

**Comment by denihs** [comment]
Hi, the solution on the PR was to throw a clear error message:

`Try installing the npm package or make sure it is not a devDependency.`.

Did you make sure the package is not a devDependency?

**Comment by bobo96run** [comment]
Hi,

I find it unexpected that Meteor build differentiates between prod and dev dependencies (no other build engine I know does that), but at least the error message makes it more explicit indeed!

Looks like it is also the case in above repro example: https://github.com/LUMECraft/mapapp/blob/meteor-issue-11900-2/package.json#L30
```json
{
	"devDependencies": {
		"dayjs": "^1.10.7"
	}
}
```

**Comment by nachocodoner** [comment]
Closing this in favor of getting a reproduction on Meteor 3.x after all the [Modern Build Stack improvements](https://docs.meteor.com/about/modern-build-stack.html), which have significantly changed how npm imports behave in applications using Rspack and modern ESM modules.
