### ISSUE TITLE
Meteor server exception when mistakenly used as a proxy

### ISSUE THREAD

**Issue by fortress-of-solitude** [meteor/meteor#1212]
Even with no clients running the server throws this exception at random times but consistently. Strangely the apparently offending URL is always the same as shown below.

Error: url must be a relative URL: http://www.baidu.com/
    at _.extend.classify (app/packages/routepolicy/routepolicy.js:92:13)
    at appUrl (/root/application/.meteor/local/build/server/server.js:160:41)
    at Object.run [as handle] (/root/application/.meteor/local/build/server/server.js:310:13)
    at next (/root/.meteor/tools/cc18dfef9e/lib/node_modules/connect/lib/proto.js:190:15)
    at Router._start (app/packages/router/lib/router_server.js:83:20)

**Comment by glasser** [comment]
Fixed.

**Comment by terenceng2010** [comment]
Our team faces a similar issue when using fast render:

Error: url must be a relative URL: http://51.254.206.142/httptest.php
at [object Object]..extend.classify (packages/routepolicy/routepolicy.js:107:1)
at IsAppUrl (packages/meteorhacks_fast-render/packages/meteorhacks_fast-render.js:138:1)
at [object Object].filterFunction (packages/meteorhacks_fast-render/packages/meteorhacks_fast-render.js:168:1)
at [object Object].PickerImp._dispatch (packages/meteorhacks_picker/packages/meteorhacks_picker.js:44:1)
at processNextSubRouter (packages/meteorhacks_picker/packages/meteorhacks_picker.js:80:1)
at processNextRoute (packages/meteorhacks_picker/packages/meteorhacks_picker.js:73:1)
at processNextMiddleware (packages/meteorhacks_picker/packages/meteorhacks_picker.js:56:1)
....


https://github.com/kadirahq/fast-render/blob/c85e49f08eb0321a0f16ff1fcda8efe80f935e25/lib/server/utils.js
https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/routepolicy/routepolicy.js

As you can see, in fastrender's isAppUrl calls routepolicy.classify, but classify has its own if (url.charAt(0) !== '/') checking that throw the error, it is suitable to modify classify so it calls routepolicy.isValidUrl instead? 

Thanks.

**Comment by kaushik1979** [comment]
I updated the meteor version also but I am still getting this error. What am I supposed to do to resolve this error?

**Comment by elie222** [comment]
I also still see errors like this

**Comment by ppryde** [comment]
Yup me too :(

**Comment by dovrosenberg** [comment]
Here too.

**Comment by hellified** [comment]
Got it here too. I'm wondering ... is this related to running the app in a docker container and mapping the port to the host? Is that seen as forwarding by meteor?

**Comment by xunga** [comment]
Got it as well... I'm so afraid that this might affect SEO.

By the way my configuration:
- ssr with blaze
- Service Workers
- mup
- https only


errors:
`Error: url must be a relative URL: http://www.google.com/`
`Error: url must be a relative URL: http://www.baidu.com/cache/global/img/gs.gif`
`Error: url must be a relative URL: http://www.baidu.com/favicon.ico`
`Error: url must be a relative URL: http://www.bing.com/`
`Error: url must be a relative URL: http://httpheader.net/`
