### ISSUE TITLE
Error while running vue example app with --production

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#12594]
1. `meteor create --vue nfc-vue3`
2. `meteor --production`
3. First error:
```
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Downloads/nfc-vue3 ]]]]]              

=> Started proxy.                             
=> Started HMR server.                        
⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (18024.37ms)
⚡️ Building with Vite...
failed to load config from /Users/wayneuong/Downloads/nfc-vue3/vite.config.js
node:internal/modules/cjs/loader:900
  const err = new Error(message);
              ^

Error: Cannot find module 'node:path'
Require stack:
- /Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node-cjs/publicUtils.cjs
- /Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/index.cjs
- /Users/wayneuong/Downloads/nfc-vue3/vite.config.js
- /Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node/chunks/dep-5605cfa4.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node-cjs/publicUtils.cjs:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Object._require.extensions.<computed> [as .js] (file:///Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:63157:17)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node-cjs/publicUtils.cjs',
    '/Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/index.cjs',
    '/Users/wayneuong/Downloads/nfc-vue3/vite.config.js',
    '/Users/wayneuong/Downloads/nfc-vue3/node_modules/vite/dist/node/chunks/dep-5605cfa4.js'
  ]
}
=> Errors prevented startup:                  
   
   While loading plugin `vite` from package `vite:bundler`:
   packages/vite/build.js:375:2: Command failed with exit code 1: node
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/.meteor-vite-build-worker.mjs
   at makeError (packages/vite/build.js:375:2)
   at execaSync (packages/vite/build.js:375:2)
   at packages/vite/build.js:262:18
   at module (packages/vite/build.js:375:2)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/vite/build.js:375:2
   at packages/vite/build.js:375:2
   
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.                           
```
5. Solve by adding `"type": "module"`  to `package.json`
6. Second error:
```
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use
meteor build to create a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Downloads/nfc-vue3 ]]]]]              

=> Started proxy.                             
=> Started HMR server.                        
⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (15107.67ms)
⚡️ Building with Vite...
vite v3.2.5 building for production...
transforming...
✓ 33 modules transformed.
rendering chunks...
node_modules/.vite-meteor/dist/meteor-entry.js   0.02 KiB / gzip: 0.04 KiB
node_modules/.vite-meteor/dist/About.js          0.59 KiB / gzip: 0.33 KiB
node_modules/.vite-meteor/dist/main.js           285.62 KiB / gzip: 67.41 KiB

⚡️ Build successful (1721.98ms)
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement
   may only appear at the top level)
   Source file: client/main.js  (2:0)
   Line content: import "./vite/meteor-entry.js"
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
   at packages/minifyStdJS/plugin/minify-js.js:77:11
   at Array.forEach (<anonymous>)
   at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
   
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement
   may only appear at the top level)
   Source file: client/main.js  (2:0)
   Line content: import "./vite/meteor-entry.js"
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
   at packages/minifyStdJS/plugin/minify-js.js:77:11
   at Array.forEach (<anonymous>)
   at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
   
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
=> Your application has errors. Waiting for file change.
```
8. Solve by not using dynamic import https://forums.meteor.com/t/is-vue3-meteor-dead-i-cant-build-it/59302/5
9. Third error:
```
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use
meteor build to create a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Downloads/nfc-vue3 ]]]]]              

=> Started proxy.                             
=> Started HMR server.                        
⚡️ Building packages to make them available to export analyzer...
⚡️ Packages built (22496.78ms)
⚡️ Building with Vite...
vite v3.2.5 building for production...
transforming...
✓ 33 modules transformed.
rendering chunks...
node_modules/.vite-meteor/dist/meteor-entry.js   295.17 KiB / gzip: 69.45 KiB

⚡️ Build successful (1765.6ms)
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   app/client/main.css: While loading postcss config: Must use import to load ES Module:
   /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js
   require() of ES modules is not supported.
   require() of /Users/wayneuong/Downloads/nfc-vue3/postcss.config.js from
   /Users/wayneuong/Downloads/nfc-vue3/node_modules/lilconfig/dist/index.js is an ES module file as it is a
   .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that
   package scope as ES modules.
   Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove
   "type": "module" from /Users/wayneuong/Downloads/nfc-vue3/package.json.
   
   
=> Your application has errors. Waiting for file change.
```

Removing type module from package.json gets me back to the first error. I'm stuck on how to solve these ):

**Comment by Grubba27** [comment]
Hey, sad to hear that. I saw that you referenced it in https://github.com/Akryum/meteor-vite/issues/33. We can try checking with @Akryum if he has some ideas on how we could solve this.

**Comment by Akryum** [comment]
Could you try renaming your post SS config file to `postcss.config.cjs`?

**Comment by MomenYasser** [comment]
@Akryum hello 🤝
I did that and still there’s a problem related to import statements 
Can you please help me, coz I built big product and I’m stucked can’t deploy it to my client 🫤

**Comment by MomenYasser** [comment]
@Akryum Hello 😭,

Till now I'm not able to build the app or push it to production 😭

Once I run `meteor --production` or `meteor build ../output` or 'meteor deploy'

I got this error:

```
 While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
   Source file: client/main.js  (2:0)
   Line content: import "./vite/meteor-entry.js"
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
   at packages/minifyStdJS/plugin/minify-js.js:77:11
   at Array.forEach (<anonymous>)
   at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
   
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
   Source file: client/main.js  (2:0)
   Line content: import "./vite/meteor-entry.js"
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
   at packages/minifyStdJS/plugin/minify-js.js:77:11
   at Array.forEach (<anonymous>)
   at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)
   
   ```
   
----

`terser minification error (SyntaxError:"Import" statement may only appear at the top level)`

Please can you help on this? 👀 ?

Thanks a lot 🌹

**Comment by Akryum** [comment]
Having import statements in if conditions for example is not supported by ecmascript standard nor vite. They must appear at the "root" level of the files. However you can use dynamic imports or vite `define` option to replace variables at compile time to tree shake unused code.

**Comment by MomenYasser** [comment]
Hello @Akryum , Thanks for you instant reply. 

I tried in fresh project to build from the [official docs tutorial](https://vue3-tutorial.meteor.com/simple-todos/01-creating-app) => `meteor create --vue simple-todos-vue`

But unfortunately same error. 😭

Any ideas or workaround? 👀

Thanks a lot 🌹

**Comment by MomenYasser** [comment]
> Having import statements in if conditions for example is not supported by ecmascript standard nor vite. They must appear at the "root" level of the files. However you can use dynamic imports or vite `define` option to replace variables at compile time to tree shake unused code.

Hello @Akryum 
Actually I'm not using any import inside if conditions, anyway can you please clarify how i can use dynamic imports or define option?

**Comment by abate** [comment]
> I tried in fresh project to build from the [official docs tutorial](https://vue3-tutorial.meteor.com/simple-todos/01-creating-app) => `meteor create --vue simple-todos-vue`

same problem here
```
W20231016-12:25:37.897(2)? (STDERR) import { Meteor } from 'meteor/meteor'
W20231016-12:25:37.897(2)? (STDERR) ^^^^^^
W20231016-12:25:37.898(2)? (STDERR) 
W20231016-12:25:37.898(2)? (STDERR) SyntaxError: Cannot use import statement outside a module
```

**Comment by Akryum** [comment]
We are working on a lot of improvements to the package thanks to @JorgenVatle help

**Comment by MomenYasser** [comment]
@Akryum Thank you guys for your efforts 🌹

**Comment by abate** [comment]
Any news on this ? thank you for your efforts !

**Comment by JorgenVatle** [comment]
There's a discussion regarding this in https://github.com/JorgenVatle/meteor-vite/issues/34

I'll try to ship an update allowing for the --production flag in the next week or so.

**Comment by JorgenVatle** [comment]
Should be fixed with JorgenVatle/meteor-vite#58 👍

I'll go through and get a finalized PR ready for `vite:bundler` over the next couple of weeks.

**Comment by nicooler** [comment]
So the good news: the deployment runs through 😅. I am still getting a weird TypeError in the Browser Console and the app won't start (white screen)

![Screenshot 2023-11-28 at 08 31 12](https://github.com/meteor/meteor/assets/7045095/122896c8-1ff0-43fa-a517-a5df32e5da72)

It seems that there is a reference to a client/vite/meteor-entry.js that does not exist:

![Screenshot 2023-11-28 at 08 32 45](https://github.com/meteor/meteor/assets/7045095/4f58d0dd-c619-49a0-94dd-8300d7e4d4fe)

This only happens with the --production flag. 

Any ideas? Do I have to create the client/vite/meteor-entry.js file?

Versions:

METEOR@2.12
....
jorgenvatle:vite-bundler@1.7.2
....
 "@vitejs/plugin-react": "^4.0.4",
....
"meteor-vite": "^1.5.0",

...
   "vite": "^4.4.9",
    "vite-jsconfig-paths": "^2.0.1",
    "vite-plugin-eslint": "^1.8.1",
    "vite-plugin-node-polyfills": "^0.15.0",
    "vite-plugin-stylelint": "^5.1.1",
    "vite-tsconfig-paths": "^4.2.1"

**Comment by JorgenVatle** [comment]
Oh, that's strange. 🤔 If you run any of the example projects, e.g. [`examples/react`](https://github.com/JorgenVatle/meteor-vite/tree/release/examples/react), do you still run into the same issue?

**Comment by nicooler** [comment]
Thx for the quick response. 

1. Problem was, I ran `mup deploy` and not `meteor --production` this now created the file `client/vite/meteor-entry.js`
2. I updated now to 
"meteor-vite": "^1.7.1",
....
jorgenvatle:vite-bundler@1.8.1

But the TypeError remains. Where t is no constructor

![Screenshot 2023-11-28 at 09 45 17](https://github.com/meteor/meteor/assets/7045095/3d565d68-3599-4c0a-bac0-9a6ec01677df)


It must have something to do with the minification, cuz without it runs just fine.

**Comment by nicooler** [comment]
I think it is an aws package issue:

https://stackoverflow.com/questions/75426770/aws-sdk-contributes-to-build-error-uncaught-typeerror-e-is-not-a-constructor

was just a bit hard to find with the minification. 🫣

**Comment by u-sour** [comment]
hi, i want to use dynamic import when deploy to production. anyone find a solution with this problem ? 
```
Errors prevented bundling:                 
While minifying app code:                  
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: node_modules/mongo-object/dist/esm/main.js  (2:0)
Line content: import MongoObject from './mongo-object.js';

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:49:25: terser minification error (SyntaxError:"Import" statement may only appear at the top level)
Source file: client/main.js  (2:0)
Line content: import "./vite/meteor-entry.js"

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:49:25)
at packages/minifyStdJS/plugin/minify-js.js:77:11
at Array.forEach (<anonymous>)
at MeteorMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:66:11)


                                           
=> Build Error. Check the logs printed above.
```

**Comment by JorgenVatle** [comment]
Hey there. What version of `meteor-vite` are you running?

**Comment by JorgenVatle** [comment]
We had a bit of a bug where if you have two files with the same name, one intended for the server and the other for Vite, Meteor would skip it's normal bundling process for that file not intended to be processed by Vite. Leading to errors very similar to the one mentioned there.

In case you haven't tried already, try `jorgenvatle:vite-bundler@1.9.1` and `meteor-vite@1.7.1`  and see if that fixes the issue for you. 🤞

**Comment by u-sour** [comment]
@JorgenVatle thank you so much, it works 👍
