### ISSUE TITLE
[Meteor 3] Uncaught Promise Rejection when throwing stub error

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12950]
When throwing a stub error with `Meteor.applyAsync`, I see 3 `Unhandled Promise Rejection` errors in the browser console. 

This is with `3.0-beta.0`

```js
// client
const promise = Meteor.applyAsync('test', ['thing'], {returnStubValue: true, throwStubExceptions: true});
promise.stubPromise.catch(e => console.error('stubPromise error', e))
promise.catch(e => console.error('serverPromise error', e))
```

```js
// isomorphic method
Meteor.methods({
  'test': async function() {
    if (Meteor.isClient) {
      throw new Meteor.Error('negative')
    }

    return;
  }
});
```
<img width="1610" alt="Screenshot 2024-01-05 at 9 42 06 AM" src="https://github.com/meteor/meteor/assets/1749828/01ff64ce-c3ed-4174-b891-fe3683c45f8a">

**Comment by jamauro** [comment]
@nachocodoner any chance this issue is now fixed with your recent work in this area?

**Comment by nachocodoner** [comment]
No, this issue remains unsolved.  I attempted debugging and made changes [in this PR](https://github.com/meteor/meteor/pull/13010),  the problem persists. I reported to the team for ideas but not solution yet. We've postponed further action as it's not critical, but we'll revisit it later.

**Comment by denihs** [comment]
This should be fixed now. Let me know if you still have this issue, and we can reopen it.
