### ISSUE TITLE
[Meteor 3] critic regression: recalling Meteor.subscribe() with different params remove all documents and reinsert all documents

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#13212]
On the client:
```
Tracker.autorun(() => {
  const caseIds = _.pluck(Cases.find().fetch(), '_id');
  Meteor.subscribe('messages', caseIds);
});
```
On the server:
```
Meteor.publish('messages', function (caseIds) {
  return Messages.find({ caseId: { $in: caseIds } });
});
```

When Cases changes :

In 2.16, it only adds the new doc:

<img width="991" alt="image" src="https://github.com/meteor/meteor/assets/103561/d83b60cc-4d11-46b0-86b3-993816e73d14">

In 3.0-rc4, it removes all doc and inserts them again:

<img width="1592" alt="image" src="https://github.com/meteor/meteor/assets/103561/5d69e001-0895-4454-94b8-ae17680f30eb">

**Comment by leonardoventurini** [comment]
Interesting, we will investigate

**Comment by StorytellerCZ** [comment]
If this is the case then that would explain the strange behavior that I have noticed with my upgrade.

**Comment by acemtp** [comment]
We created a very minimal project to easily produce it.

Meteor 2.16: It first sub and then unsub (so it doesn't remove/add because there's always a sub)

<img width="642" alt="image" src="https://github.com/meteor/meteor/assets/103561/8fcbe602-b932-4eef-8391-b915de597a3f">

Meteor 3: It first unsub then sub (so the unsub remove the data and the sub add the data back).

<img width="618" alt="image" src="https://github.com/meteor/meteor/assets/103561/6182a7d3-68d9-41b7-91f7-3f2ba4c4cba5">

**Comment by StorytellerCZ** [comment]
@acemtp can you share with us the repository with the reproduction?

**Comment by peernohell** [comment]
Hi,

I just create a minimal project to reproduce the issue.
It has a webpage where you have a refresh button.
if you click on it you will see that the tracker that look after post is never re-run but if you update the project in meteor v3.0-rc.4 then the auto run is executed

https://github.com/peernohell/meteor-bug-publish

what it show in v2.16 if you click refresh multiple time
<img width="519" alt="image" src="https://github.com/meteor/meteor/assets/119765/ce1b3e08-c9d3-403f-a758-92117c46dbee">


what it show in v3.0-rc.4 if you click refresh multiple time
<img width="521" alt="image" src="https://github.com/meteor/meteor/assets/119765/408ff527-b2e6-404c-99e5-f75cbc76e3fc">

**Comment by StorytellerCZ** [comment]
Some thoughts:
I think in essence the system here is working as it should, but is too aggressive/fast in closing subscriptions and removing the associated data from minimongo. In essence the migration might have fixed a bug that became the behavior we know and are use to. Hard to say unless more knowledgeable people in this domain chime in.
The system detects a that there is a change in the params of the subscription (the name and params need to remain the same for the sub to continue existing). Hence it determines that the old subscription should be scrapped. This means that the subscription closes and that the data should be removed from Minimongo. I think in Meteor 2.x there has been a delay or something that closed the connection, but gave enough time for the new one to take over any existing data, while in Meteor 3 the removal of data happens before the new subscription has a chance to claim the data.

Right now I'm trying to locate where this is happening or what exactly has changed in the code so that we can return the behavior back to the old one. Maybe we could even change it so that the data lingers longer in Minimongo if the subscription name is the same.

**Comment by radekmie** [comment]
Based on the screenshots in https://github.com/meteor/meteor/issues/13212#issuecomment-2208402206, the issue seems rather clear: `sub` came _after_ `unsub`. It's not documented in the DPP protocol (https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md), but Meteor will react to `unsub` _synchronously_, i.e., as soon as this message is received. That means it doesn't matter that `sub` is sent a few ms later - it's a full refresh since the data is already scheduled to be flushed from the merge box ([relevant code is here](https://github.com/meteor/meteor/blob/faf04b8780211ede199a919936a5657426ea9b8a/packages/ddp-server/livedata_server.js#L975)).

**Comment by StorytellerCZ** [comment]
Looking through `ddp-client` in `common/livedate_connection.js` even though the new subscription gets triggered before the stop, the actual message for unsubscription gets sent first.

![image](https://github.com/meteor/meteor/assets/1715235/355dad70-3a17-43dc-8fb4-1da5b92037d3)

**Comment by denihs** [comment]
I narrowed down the problem on https://github.com/meteor/meteor/pull/13220. We just need to make sure that is the right strategy.

**Comment by peernohell** [comment]
Hi,

I just tested with the new 3.0 release and there's still an issue with pub/sub.

I updated the code on my test project so you can reproduce the problem https://github.com/peernohell/meteor-bug-publish

Each time you click on the refresh button, we increase the number of documents we want.

In 3.0 you see (in the websocket and on the html) that all documents are removed then added back then the new one is added.

<img width="352" alt="SCR-20240716-pclz" src="https://github.com/user-attachments/assets/c973c8e8-013c-4c34-98dd-370c311b68de">

In the 2.16, it just adds the new document.

<img width="335" alt="SCR-20240716-pcxd" src="https://github.com/user-attachments/assets/fd8d20e1-a8c7-46d5-8e58-5cb42226fbac">

**Comment by leonardoventurini** [comment]
@peernohell, thanks for reporting it to us and for the repro code, we will take a look and provide a patch for it.

**Comment by leonardoventurini** [comment]
GitHub closed it automatically, reopened. I am working on it.

**Comment by leonardoventurini** [comment]
I have a potential fix, will do some validation and add some tests

https://github.com/meteor/meteor/pull/13236

**Comment by acemtp** [comment]
We see another issue related to this one, the 'ready' message is sent before all data are added to the client so when we call the callback in the subscribe function, the data are not always available.

**Comment by leonardoventurini** [comment]
@acemtp I cannot repro it, not in 3.0.1 and not with 3.0.2 with the fix (I suspect it might already fix it). Can you provide some repro steps so I make sure the fix applies to it as well?

**Comment by acemtp** [comment]
We'll check if it happens again, perhaps it's fixed in 3.0.1. Since it's random depending of the latency of the network, it's not easy to fix.

**Comment by leonardoventurini** [comment]
> We'll check if it happens again, perhaps it's fixed in 3.0.1. Since it's random depending of the latency of the network, it's not easy to fix.

Ok, I will try playing with the latency and see if I can repro too

**Comment by JorgenVatle** [comment]
We've also run into some potentially unwanted behavior following the 3.0.1 release.
https://github.com/meteor/meteor/pull/13220#issuecomment-2233622828

**Comment by leonardoventurini** [comment]
@JorgenVatle the unwanted behavior you mention only affects auth, that we are aware of, this PR fixes auth sub directly but we could not fix all of them without regressions, we did optimize the process a little bit by batching the ready calls once the user is set by the login method. We added a task to investigate again for all other subs in the future, as at the minimum we see it as a small performance issue.

Here's the PR:

https://github.com/meteor/meteor/pull/13247

**Comment by JorgenVatle** [comment]
That makes sense @leonardoventurini. Thanks for the clarification on this. 🙌

**Comment by peernohell** [comment]
Hey,

I just try my test function with le devel version and the bug is still present.

I try to investigate and I think I found something interesting but as it's the first time I take a close look to core function maybe it's just something I didn't understand.

For me their something wrong with `Hook` class.
From what I understand it's a helper to run callbacks one after the other.
In meteor 2.16, the option `wrapAsync` that is default to `true` call [`Meteor.asyncFn`](https://github.com/meteor/meteor/blob/97b721b415e73c072284404e800f9a4d1eb040ea/packages/meteor/helpers.js#L166C1-L183C3) that ensure, thanks to fiber, that we will wait the async function to be resolved.
But in meteor 3 the `wrapFn` is just a function that call the passed function, so if it's an async function then it will not be waited by hooks.

As publish use Hook, it can definitely be part of the issue.

What do you think about it?

**Comment by peernohell** [comment]
Hi,

I have dig into livedata_server.js and I think I found the issue.

when the server receive `sub` then `unsub`
`sub` call `_startSubscription` that call `_runHandler` that call `_publishHandlerResult` with a cursor.
As it's a cursor it will set a promise on `_publishCursorPromise` but this promise is not awaited and sub have finish
`unsub` call `_stopSubscription` but do synchronious code (remove documents, etc) but at that instance, the cursor is still not resovlved.

So, for me the issue is that `_publishHandlerResult` should wait for the cursor to be resolved before continuing.
I don't understand why `_publishCursorPromise` is needed so I certainly miss something.


in `_runHandler`,

line 1217, if I add under the following
```
if (self._publishCursorPromise) await self._publishCursorPromise;
```

it fix the issue we have.
<img width="556" alt="image" src="https://github.com/user-attachments/assets/decab35e-a708-4b85-9de9-dd0716a9b1d3">

**Comment by brianlukoff** [comment]
@peernohell We're seeing [a related issue](https://github.com/meteor/meteor/pull/13220#issuecomment-2233622828) and I'm wondering if it has the same cause?

**Comment by leonardoventurini** [comment]
We've released a beta for 3.0.2 with the fixes, please try it.

`meteor update --release 3.0.2-beta.0`

https://forums.meteor.com/t/meteor-3-0-2-beta-0-is-out/61925

@peernohell please check this PR:

https://github.com/meteor/meteor/pull/13236/files

It should be working fine now in the beta 0.

**Comment by leonardoventurini** [comment]
@brianlukoff please confirm if the following still happens with `3.0.2-beta.0`:

> We're seeing the same thing, which is causing problems on reconnect -- essentially, upon reconnect, previously logged-in users get redirected away from their page because they are temporarily seen as being logged out (since the subscriptions before login fail). They are eventually logged in and a page refresh fixes the problem but not an ideal UX.

**Comment by brianlukoff** [comment]
@leonardoventurini Yes, unfortunately I'm still seeing this behavior on 3.0.2-beta.0.

**Comment by leonardoventurini** [comment]
Thanks @brianlukoff we will work on that now.

**Comment by peernohell** [comment]
Hi,

I just tested the 3.0.2-beta.0 and the reproduction app is now working correctly and our main application that had the issue is working fine with that new version 🎉

Thanks a lot ❤️

**Comment by leonardoventurini** [comment]
Lovely @peernohell, anything let us know. 🎉

**Comment by leonardoventurini** [comment]
@brianlukoff this PR should solve your issue, we plan to release another beta sometime next week before the official `3.0.2`

https://github.com/meteor/meteor/pull/13262

**Comment by brianlukoff** [comment]
@leonardoventurini Thanks! I just tried running the PR from a checkout of the `v3/login-sub-order` branch and unfortunately we're still seeing the same behavior, so I'm wondering if we are doing something unusual in our app somehow. 

It is only happening on reconnect -- it looks like `login` fires but the subscriptions are run on the server before the user is actually logged in on the server side (all of the "stopped" messages are corresponding to subscriptions that failed because the user is not completely logged in):

![CleanShot 2024-07-30 at 13 53 17@2x](https://github.com/user-attachments/assets/caebbcc1-e3e2-4299-adea-a6ae0b12749d)

**Comment by leonardoventurini** [comment]
@brianlukoff Yes, that looks odd, we haven't seen any subscriptions stopping like that. What do you mean specifically by reconnection? Just refreshing the page or when the socket disconnects/reconnects?

Can you provide some repro code for us? It would be very helpful in this case. Are your publications throwing any exceptions or things like that?

**Comment by brianlukoff** [comment]
@leonardoventurini Refreshing the page is totally OK -- it's when the socket disconnects/reconnects due to the server container being replaced (e.g. during a deployment so the user has to connect to another container -- also in development mode when the server restarts, although of course that latter case is no big deal).

What seems to be happening is that the subscription is being run upon reconnect and when the publication code checks the user's current logged-in state (or whether they have the appropriate roles/permissions), `Meteor.userId()` is not defined. So the publication throws an exception (which is expected at that point since from the publication's perspective an anonymous user is trying to access protected data).

I'll see if I can create a repro, but let me know if you have any other ideas!

**Comment by leonardoventurini** [comment]
I think I have everything that's needed to create a repro now, will investigate it tomorrow. Somehow the subs are being initialized before the login call is made, but differently from the issue before, it happens only when the socket reconnects, we are probably in a better position to fix that now, should be easy to solve.

**Comment by brianlukoff** [comment]
Great - thanks @leonardoventurini ! Let me know if/how I can help.

**Comment by leonardoventurini** [comment]
After discussing about the issue with @brianlukoff in private, the PR provides the fix successfully. I merged it and now we are going for another 3.0.2 beta, ETA today or tomorrow. After that we can close this issue.

**Comment by leonardoventurini** [comment]
We have released Beta 4 for 3.0.2, all subs with auth should be stable now, please check:

```
meteor update --release=3.0.2-beta.4
```

cc @StorytellerCZ @brianlukoff @filipenevola
