### ISSUE TITLE
Installing Meteor 3 with install.meteor.com shows Node 14 warning

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#13478]
When installing Meteor 3 using `curl https://install.meteor.com/ | sh`, it still shows the Node 14 warning:

```
This Meteor 2.x version is running on a deprecated Node.js version (14). Meteor 3.0 is in progress, and it will run on the latest Node.js version. For more information, please consult this migration guide: https://guide.meteor.com/3.0-migration.
```

**Comment by StorytellerCZ** [comment]
Closing this as I believe this has been resolved. If not please comment and we will address is then.

**Comment by zodern** [comment]
The issue still exists. If you open `https://install.meteor.com/`, it still has the warning right before the line `RELEASE="3.0.4"`

**Comment by StorytellerCZ** [comment]
I see, that should be a quick fix! But needs to be done by the Meteor Software team @fredmaiaarantes @nachocodoner

**Comment by nachocodoner** [comment]
We will fix this one on next release

**Comment by nachocodoner** [comment]
Deployed the fix. Closing the issue.
