### ISSUE TITLE
Meteor.wrapAsync doesn't return the error object correctly

### ISSUE THREAD

**Issue by laddi** [meteor/meteor#2774]
When using Meteor.wrapAsync to call external APIs, any errors will just return as standard errors and not the actual error returned by the external service.  So adding a try/catch around the call will return an error object but that object only contains the stack, not the object returned (see: https://meteorhacks.com/improved-async-utilities-in-meteor-npm.html)

Using Meteor.wrapAsync would be greatly improved if it was possible to also get the correct error returned, otherwise you're walking around in the dark when you encounter errors...

**Comment by artitw** [comment]
Experiencing same problem here. Anyone has a workaround so that I can return the error object correctly?

**Comment by laddi** [comment]
Try this:
```javascript
meteor add meteorhacks:async
```

And then use Async.wrap instead of Meteor.wrapAsync, that will return the proper error object in the stack trace.

**Comment by artitw** [comment]
@laddi, I tried it and the behavior is the same as the standard Meteor.wrapSync function. Also, the documentation clearly states `If the callback has a result, it will be returned from the wrapped function. If there is an error, it will be thrown. Async.wrap(function) is very similar to Meteor._wrapAsync.`

**Comment by faceyspacey** [comment]
I'm having the same issue. I really need to get the information in the original error object. Is there a temporary work around? 

I mean we can easily overwrite ```Meteor.wrapAsync``` for the time being. Is there anything we can add to ```Meteor.wrapAsync``` for now: 

````
Meteor.wrapAsync =  function (fn, context) {                                                                     // 90
    return function (/* arguments */) {                                                                   // 91
      var self = context || this;                                                                         // 92
      var newArgs = _.toArray(arguments);                                                                 // 93
      var callback;                                                                                       // 94
                                                                                                          // 95
      for (var i = newArgs.length - 1; i >= 0; --i) {                                                     // 96
        var arg = newArgs[i];                                                                             // 97
        var type = typeof arg;                                                                            // 98
        if (type !== "undefined") {                                                                       // 99
          if (type === "function") {                                                                      // 100
            callback = arg;                                                                               // 101
          }                                                                                               // 102
          break;                                                                                          // 103
        }                                                                                                 // 104
      }                                                                                                   // 105
                                                                                                          // 106
      if (! callback) {                                                                                   // 107
        if (Meteor.isClient) {                                                                            // 108
          callback = logErr;                                                                              // 109
        } else {                                                                                          // 110
          var fut = new Future();                                                                         // 111
          callback = fut.resolver();                                                                      // 112
        }                                                                                                 // 113
        ++i; // Insert the callback just after arg.                                                       // 114
      }                                                                                                   // 115
                                                                                                          // 116
      newArgs[i] = Meteor.bindEnvironment(callback);                                                      // 117
      var result = fn.apply(self, newArgs);                                                               // 118
      return fut ? fut.wait() : result;                                                                   // 119
    };                                                                                                    // 120
  }
````

for me, honestly, I rather be returned an error object, whose type I can just check, rather than have to try/catch errors. Perhaps even an object with an ```result.err``` property and a ```result.data``` property, e.g: 

```` 
stripe.charge = function (stripeToken) {
  var stripeChargeSync = Meteor.wrapAsync(Stripe.charge.create, Stripe.charge);

  var result = stripeChargeSync({
    amount: 1000, 
    currency: "USD",
    card: stripeToken,
    description: "bla"
  });

  if(!result.err) return result.data;
  //else do something with result.err.type
};
````

How can we accomplish that right now? Perhaps in ```Meteor.bindEnvironment(callback)```???

ps. it seems utterly retarded to have to try/catch shit. Often, u have one line of code to deal with the error situation, and it's not even a real exception ur dealing with, but a very common situation, such as one of the many reasons Stripe returns for failed cards. It's just a natural part of business. Please let me deal with it explicitly as part of how we deal with Async functions made to be synchronous. The reason being that it's most closely aligned to how u originally dealt with them when they were async--specifically u r passed both an error and a data parameter; there's no try/catching there. So, js can only return one variable, make it an object with what we are traditionally used to having. I can't say it enough--i don't wanna have to write try/catches everywhere i make one of these wrapSync calls. I wouldn't be so adamant except that's the solution Im saying everyone shooting for on the net. I admit returning 2 things might be awkward, but the whole fiber thing to begin with wasn't the status quo, yet look how much it's kicked ass for us.  ...shit i think i know the f###kin answer right now:

````
 newArgs[i] = function(error, data) {
   var newCallback = Meteor.bindEnvironment(callback);

   if(error) return {error:  error};
   else return {data: newCallback(error, data)};
};

... then just replace Meteor.wrapAsync for now (and only on the server). I don't think that supports supplying callbacks server side, but im sure someone can figure out how to modify that. U gotta adjust the code in the middle of ```wrapAsync``` when the presence of ```callback``` is first checked. I honestly, don't even wanna use callbacks and rather settle on this synchronous convention anyway since it's not blocking anyway. 
````

**Comment by channikhabra** [comment]
I'm having the same issue too, looks like @faceyspacey 's recommendation may work--anyway one try it yet?

**Comment by estark37** [comment]
This is a characteristic of throwing errors through futures and doesn't have anything to do with `Meteor.wrapAsync` itself.

When handling an error, futures takes the original error object and uses it as the prototype of the error object that it actually throws: https://github.com/laverdet/node-fibers/blob/master/future.js#L197 So in your reproduction repo, @laddi, all the expected properties are there, but they're on the prototype of the error object instead of on the object itself. To see this, add `for (var key in e) { console.log(e, e[key]); }` in the `catch` block.

Also see https://github.com/laverdet/node-fibers/issues/206.

All that to say, I'm not sure what we should actually do about this. Our options include:
* Do what `Async.wrap` does and set all the enumerable properties as instance properties: https://github.com/meteorhacks/meteor-async/blob/master/async.js#L72. This seems not quite correct to me; there could be edge cases where properties actually belong somewhere up the prototype chain instead of on the actual instance. (But maybe breaking those edge cases is preferable to the current situation?)
* Submit a PR to node-fibers (off the top of my head, I'm not sure why it's using `Object.create` instead of cloning the original error object).

As a temporary workaround (especially if you're just debugging and not worried too much about the edge cases I mentioned above), you could try doing something like `Async.wrap` does:
```
var myWrapAsync = function (fn, context) {
  var wrapped = Meteor.wrapAsync(fn, context);
  return function (/* arguments */) {
    try {
      return wrapped.apply(context, _.toArray(arguments));
    } catch (err) {
      var newErr = new Error(err.message);
      for (var key in err) {
        newErr[key] = err[key];
      }
      throw newErr;
    }
  };
};
```
and then use `myWrapAsync` where you are using `Meteor.wrapAsync`.

Finally, @faceyspacey, I think you're pointing out a completely separate concern: you're talking about whether `Meteor.wrapAsync` should throw errors that would normally be returned as the first argument of a callback, whereas this thread is about the correctness of the error object that gets thrown. Please start a thread on meteor-core if you'd like to discuss changing the `Meteor.wrapAsync` API. (Or, if you don't like using try/catch, you could just write your own wrapper that does the try/catch for you and formats the result the way you want it.)

**Comment by mitar** [comment]
I think this is maybe a duplicate of #1482? Or at least related. I would also point out that Meteor itself had to make a special case to fix this, see 5a8ab31f43aa1a9fcd99e28529de650f84c340d2 So while this is fixed now for `Meteor.Error`, it still shows a more general issue.

**Comment by estark37** [comment]
Ah, thanks @mitar! https://github.com/laverdet/node-fibers/pull/144 is definitely relevant.

**Comment by faceyspacey** [comment]
@estark37 ok, i'll start that thread, but just in case anyone was counting on this thread to answer this problem, here's my tested code which accomplishes the goal for what seems to be a common place people are unsatisfied with meteor's thrown errors:

````
Meteor.makeAsync = function(fn, context) {
  return function (/* arguments */) {
    var self = context || this;
    var newArgs = _.toArray(arguments);
    var callback;

    for (var i = newArgs.length - 1; i >= 0; --i) {
      var arg = newArgs[i];
      var type = typeof arg;
      if (type !== "undefined") {
        if (type === "function") {
          callback = arg;
        }
        break;
      }
    }

    if(!callback) {
      var fut = new Future();
			callback = function(error, data) {
			   fut.return({error:  error, data: data});
			};
			
      ++i; 
    }

    newArgs[i] = Meteor.bindEnvironment(callback);
    var result = fn.apply(self, newArgs);
    return fut ? fut.wait() : result;
  };
};
````

**Comment by jcolemorrison** [comment]
I personally found @faceyspacey 's problem with wrapAsync the most relevant and helpful.  For anyone who may be looking around for this answer, @faceyspacey 's solution here is spot on.  It works great.

**Comment by boustanihani** [comment]
Hope this gets fixed soon :+1:

**Comment by redspear** [comment]
@faceyspacey's solution worked for me too

**Comment by themeteorchef** [comment]
Any word on a fix for this? Maybe in 1.2?

**Comment by Maado** [comment]
Any word on a fix for this?

**Comment by mitar** [comment]
https://github.com/laverdet/node-fibers/issues/206 was closed upstream. So probably this is now just a matter of bumping the version in Meteor?

**Comment by sjmcdowall** [comment]
We're still on fibers 1.0.5 for gosh sakes -- who knows when they will bump fibers to a latest version -- let alone why did they fork it in the first place?

**Comment by nathanhornby** [comment]
Any updates on this?

**Comment by CTimmerman** [comment]
I just use a Future:
```coffeescript
			Future = Npm.require 'fibers/future'
			fut = new Future()
			exec(command, (error, stdout, stderr)->
				#console.log('error', error)    # Non-zero exit, error.code
				#console.log('stdout', stdout)  # Errors are here.
				#console.log('stderr', stderr)  # Not even when there's an error.
				fut.return(stdout)
			)
			console.log fut.wait()
```

**Comment by TimeBandit** [comment]
Having the same issues. It's a real be-yatch, would be nice if MDG provides a solution or a recommended way for returning values of async callbacks from methods, such as a call to Stripe.create.charge({}, callback(err, res)) from a meteor method.

**Comment by MichaelJCole** [comment]
Hey, groking this.  @estark37 is there a reason you used `new Error(err.message);` instead of `new Meteor.Error(err.message || err);`?

```
var myWrapAsync = function (fn, context) {
  var wrapped = Meteor.wrapAsync(fn, context);
  return function (/* arguments */) {
    try {
      return wrapped.apply(context, _.toArray(arguments));
    } catch (err) {
      var newErr = new Meteor.Error(err.message || err);
      for (var key in err) {
        newErr[key] = err[key];
      }
      throw newErr;
    }
  };
};
```
Thanks!

**Comment by mitar** [comment]
I think because `Meteor.Error` should be used only for DDP based errors, not general errors. If you are calling your function inside DDP context, then that code around should match a general `Error` and make it into `Meteor.Error` (which is done automatically for you inside Meteor methods, for example).

**Comment by AlexCatch** [comment]
Any update on a fix for this? It's a pretty annoying and breaking bug.

**Comment by TimeBandit** [comment]
I thought this was resolved in 1.3?

**Comment by AlexCatch** [comment]
@TimeBandit I still get the issue when doing Meteor.WrapAsync on any Stripe function.

**Comment by MiroHibler** [comment]
Any hope this will get resolved in 1.4 at l(e)ast?

**Comment by mitar** [comment]
Does https://github.com/peerlibrary/meteor-blocking work better?

**Comment by TimeBandit** [comment]
I don't see this issue in M1.3 & using **mdg:validated-method**. So I guess it is fixed.

**Comment by MiroHibler** [comment]
@mitar, yeah that looks good, but it would mean changing quite a bit of my current `Meteor.wrapAsync` code which I'm not prepared to do at the moment.

I'd rather go with @estark37's wrapper and just remove it once the main code gets fixed...

**Comment by mitar** [comment]
To my understanding that works as intended and it is simply a different API. You do not like that API, so you have to use something else. But maybe I am misunderstanding something.

**Comment by cheapRoc** [comment]
This problem still existed for us when using Stripe and Meteor 1.3.5.1. @faceyspacey's `Meteor.makeAsync` solution works around the issue using the Fiber/Future API.

**Comment by smeijer** [comment]
I can't believe converting node modules into meteor / fiber compatible code, must still be so difficult.

Is there any downside on using @faceyspacey's `Meteor.makeAsync` over `Meteor.wrapAsync`?

**Comment by hwillson** [comment]
Since there hasn't been any activity on this issue in a while, I'll close it for now. Happy to re-open if anyone is still encountering this issue (using a modern version of Meteor) and can supply an up to date reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug)). Thanks!
