### ISSUE TITLE
Template instance custom properties inaccessible inside content blocks

### ISSUE THREAD

**Issue by rclai** [meteor/meteor#3540]
Reproduction here: https://github.com/rclai/meteor-template-instance-issue

**Comment by stubailo** [comment]
Great reproduction!

**Comment by stubailo** [comment]
In PR #3545

**Comment by rclai** [comment]
Cool. 

There is another issue I'm going to submit regarding ```Template.parentData()``` returning the wrong stuff. Like for example, parentData 0 and 1 would have the same data when using content blocks sometimes or it would give you the completely wrong data context. I wonder if this issue is related?

**Comment by stubailo** [comment]
They are related, I also want to fix that one right now.

**Comment by rclai** [comment]
Should I still post a reproduction for that one?

**Comment by stubailo** [comment]
No I have one that's pretty good I think

**Comment by rclai** [comment]
How would I go about using this patch  on demand before the next release happens? Is that possible?

**Comment by stubailo** [comment]
After we fix this, we might be able to publish a pre-release version of Blaze, since that's the only package affected by the changes. I'll let you know.

**Comment by rclai** [comment]
Thanks.

**Comment by stubailo** [comment]
try running your app with `meteor --release TEMPLATE-CURRENT-DATA@0.0.1`, this includes the fix we just merged for this issue. let me know if it's fixed!

**Comment by rclai** [comment]
It's working great. Nested a bunch of content blocks and still getting the template instance.

In the process, I noticed that UI.body broke. helpers weren't working there in this pre-release.

**Comment by stubailo** [comment]
Interesting - this is actually a bug introduced in the preview, thanks for catching it!

**Comment by rclai** [comment]
No problem, let me know how it goes.

**Comment by stubailo** [comment]
I think I have fixed it now. I forgot you can have helpers on `Template.body`, which is not technically a template.

**Comment by rclai** [comment]
One thing I noticed also about the current release is that you can't call ```Template.instance()``` inside of ```UI.body```'s helpers for some reason. It'll give you this error: 

```
Exception in template helper: TypeError: undefined is not a function
    at Function.Template.instance (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3172:15)
    at Object.Template.body.helpers.huh (http://localhost:3000/todo.js?369894fe370de6099d78041d62a01b22fd3afe59:8:23)
    at bindDataContext (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16)
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:112:39)
    at null._render (http://localhost:3000/template.todo.js?8adea1cfbcc0c100fb92a17b2b10d75cdbbbf9bc:5:22)
    at doRender (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1866:25)
    at http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1808:16
```

Could this be related to the above thing?

Here's a reproduction (I hope you don't mind that I pasted it here?):

```
if (Meteor.isClient) {
  Template.body.created = function () {
    this.test = 'huh'
  };

  Template.body.helpers({
    huh: function () {
      return Template.instance().test;
    }
  });
}

<body>
  {{huh}}
</body>
```

**Comment by rclai** [comment]
What's the status of this?

**Comment by stubailo** [comment]
This is interesting - I think `Template.body` is not a real template, and therefore doesn't really have Template.instance(). @avital @dgreensp what should we do here?

**Comment by rclai** [comment]
I'm bringing up `Template.body` or `UI.body` because it's mentioned in [here](https://github.com/meteor/meteor/wiki/Using-Blaze#uibody-is-now-a-template-corresponding-to-the-entire-body-element).

**Comment by stubailo** [comment]
Oh interesting, I could be wrong then, let me look into it more

**Comment by stubailo** [comment]
Just opened a new issue for this: #3631

**Comment by stubailo** [comment]
Going to close this because this particular issue has been fixed

**Comment by rclai** [comment]
Ok cool thanks.
