### ISSUE TITLE
"template-level subscriptions" test is flaky

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#3859]
I've been seeing sporadic failures on devel of "template-level subscriptions"

Specifically, i think, the checkOneReady is sometimes seeing "ready! true" instead of "".

I think there is a race condition?  I'm really not clear on what is guaranteeing that checkOneReady actually executes before the second subscribe finishes.

cc @stubailo

**Comment by stubailo** [comment]
Fixed here: 86aeee4a4bc2271108c46053a1da547e60d78f5f

**Comment by glasser** [comment]
I'm still seeing this fail occasionally. Typically when running the full test-packages suite.

**Comment by stubailo** [comment]
Awesome - thanks, Glasser!
