### ISSUE TITLE
Minimongo: $eq not recognized? (Mongo 3.0 feature with Meteor 1.1.0.2)

### ISSUE THREAD

**Issue by iboxgithub** [meteor/meteor#4142]
***21 Upvotes*** Hi, 

I get this message
Error: Unrecognized operator: $eq
when trying to make the following request on minimongo
var transactions = Transactions.find({status:{$eq:'done'}});

Whereas this one works
var transactions = Transactions.find({status:{$ne:'done'}});

It is from 3.0 Mongo version and I have Meteor 1.1.0.2
http://docs.mongodb.org/manual/reference/operator/query/eq/

So am I missing something or is it normal?

Thanks for your help!

**Comment by iboxgithub** [comment]
I just add: I read the RN and didn't find a comment on it..just in case someone wonders =)

**Comment by iboxgithub** [comment]
No one has this issue? The last Meteor RN confirm that Mongo 3.0 just arrived, here is an extract of the email I received 31/03/2015

"We are pleased to announce Meteor 1.1 today, the latest release of the open source Meteor platform.  Meteor, which lets developers build modern web and mobile apps on a single JavaScript codebase in a fraction of the time and cost otherwise possible, is for the first time now available as an official distribution on the Windows operating system.  Meteor 1.1 also includes support for MongoDB's new 3.0 database engine and adds many improvements throughout the stack."

**Comment by glasser** [comment]
Good call.  I'm definitely aware of `$eq` (see my comment at https://jira.mongodb.org/browse/SERVER-1367).  Meteor works with Mongo 3.0 now but that doesn't mean that Minimongo supports all Mongo 3.0 features (after all, it doesn't support every Mongo 2 feature too).  Would definitely take a PR that adds this (with tests); it shouldn't be too hard.

**Comment by iboxgithub** [comment]
Cool =)

**Comment by udiedrichsen** [comment]
I use as a workaround for this missing feature $not -> $ne

This one here don't work:
    {
      username: {
        $eq: Meteor.user().username
      }
    }

This one here works:
    {
      username: {
        $not: {$ne: Meteor.user().username}
      }
    }

Would be great to have $eq :+1:

**Comment by trusktr** [comment]
How can we not have $eq? That seems like basic necessity.

**Comment by trusktr** [comment]
Oh, because it's relatively brand new. How strange of Mongo.

**Comment by trusktr** [comment]
I guess I'm too new to Mongo. :laughing: $in with an array works just fine, so `{field: {$in: [value]}}` is basically the same as `{field: {$eq: value}}`.

**Comment by guilhermedecampo** [comment]
I've been using `Collection.find({field: value}).count()` for comparison. If is what I understand =P

**Comment by dcworldwide** [comment]
:+1: Hit this issue today

**Comment by tobsai** [comment]
+1

**Comment by vladgolubev** [comment]
+1

**Comment by introbig** [comment]
+1

**Comment by markoshust** [comment]
+1, just stumbled on this today. `$not.$ne` works but is super awkward.

**Comment by shkomg** [comment]
+1

**Comment by crussi** [comment]
+1

**Comment by jazzdragon** [comment]
+1

**Comment by gor181** [comment]
+1

**Comment by smoke** [comment]
+1

**Comment by djules75** [comment]
+1

**Comment by smoke** [comment]
For those who struggle - I found somewhere that `$all: [val]` works like `$eq: val` - it worked for me in a specific case, but not gone further to fully explore is there any difference.

**Comment by lukabirsa** [comment]
+1

**Comment by maximebodereau** [comment]
+1

**Comment by dubielzyk** [comment]
+1

**Comment by jlmbaka** [comment]
+1

**Comment by jlourenco** [comment]
+1

**Comment by aviavia** [comment]
+2

**Comment by thomasmery** [comment]
Hi,

just hit this today too

as I'm new to meteor I thought I'd ask:

would using  `$regex` with something like `/^mystring$/` be considered bad practice as a replacement?

also ... +1

**Comment by patrickml** [comment]
+1

**Comment by scharf** [comment]
+1

**Comment by mashiox** [comment]
+1

**Comment by acomito** [comment]
1

**Comment by AlexCatch** [comment]
+1

**Comment by laran** [comment]
+1

**Comment by YagoLopez** [comment]
Still no solution as of may 2016? I can't believe it

**Comment by YagoLopez** [comment]
For anyone interested, If I am not wrong you can check equality in a field in this way:

{ fieldName: value }

(Note: "fieldName" sould exist in the documents you want to check)

Keep it simple.

Reference:
http://stackoverflow.com/questions/9047966/mongodb-logical-operators-e-g-lt-lte-but-is-there-one-for-to-simp

**Comment by Slava** [comment]
It seems to be a good opportunity for a community PR. Start by looking here: https://github.com/meteor/meteor/blob/0ba6a79d10f4e26243b1baba8c6fc53d3fc9f9aa/packages/minimongo/selector.js#L383

Then make sure that all checks on "simple matching" apply correctly to `$eq`. Then write tests and submit a PR. Good luck.

**Comment by YagoLopez** [comment]
Hey @Slava, good idea. Thanks for the information. I'll send a PR if I get time soon. Cheers.

**Comment by Slava** [comment]
Should this issue be closed after https://github.com/meteor/meteor/pull/4235 merges?

**Comment by glasser** [comment]
Fixed in #7080

**Comment by jsantana90** [comment]
what do I have to do to get this? I'm still getting $eq error, had to use `$not: {$ne:...`
