### ISSUE TITLE
Accept PR in cordova plugin repo to support replacing or extending it's methods

### ISSUE THREAD

**Issue by rbabayoff** [meteor/meteor#4487]
This is the PR:

https://github.com/meteor/com.meteor.cordova-update/pull/4

The PR above allowed me to use the much faster and better wkwebview in ios using this cordova plugin:

https://github.com/practicalmeteor/WKWebView

Once the above is accepted, the cordova plugin github tarball url will need to be updated in webapp's package.js.

**Comment by Tarang** [comment]
There are some issues with this. Maybe @Slava you could help? Where would this issue come from, would it be the updater?:

https://github.com/practicalmeteor/meteor-wkwebview/issues/1#issuecomment-107332134

**Comment by rbabayoff** [comment]
@Tarang , what are you referring to?

**Comment by Tarang** [comment]
@rbabayoff The issue is on your repository it is not a telerik issue but somewhere from within meteor. If you run the app with `meteor run ios` it behaves correctly. If you use `meteor run ios-device` it does not:

https://github.com/practicalmeteor/meteor-wkwebview/issues/1

Perhaps its the autoupdater?

**Comment by rbabayoff** [comment]
I'm intimately familiar with autoupdate. Don't see a reason why there should be a difference between run ios and run ios-device, as far as autoupdate is concerned (other than the much longer file paths in the simulator ), but I may be wrong. In any case, moving the class declaration to to a .h file, has nothing to do with my wkwebview package, it has no implications by itself whatsoever, but it actually will make it easier for me to publish updates to the community of wkwebview, so more people in the community can help stabilize this and figure out it's problems. with wkwebview memory consumption goes down 80%, memory leaks are eliminated and cpu usage goes down 80% too. It's that drastic. The old ios web view is basically unusable in most hybrid apps.

**Comment by Tarang** [comment]
Yes @rbabayoff I quite like your package do keep it up. I am not bashing it or anything merely pointing out its not a telerik issue and we need to find a way to fix it. It's quite likely there is a Meteor issue in somewhere causing the status bar gap problem. But please make no mistake me and lots of others would love to use wkwebview

I pointed out autoupdater because the black meteor splash takes a while longer with `run ios-device` and this happens when an update is going on in the background. This could account for the difference.

**Comment by rbabayoff** [comment]
Thanks @Tarang , reason I published it, and didn't keep it internally, is in order to catch all of those problems sooner rather than later, for the benefit of all of us. But some help making it easier for me to wrap it in a single meteor package, and not a modified cordova plugin + a meteor package will make it easier putting it out there.

**Comment by rbabayoff** [comment]
This is what this pr is all about.

**Comment by Tarang** [comment]
@rbabayoff I gave your suggestion a go of using a config.xml file but it didn't solve the problem.

I actually opened the Xcode project at `.meteor/local/cordova-build` and the same status bar issue remained so I'm guessing it has something to do with how the emulator is run.

**Comment by Tarang** [comment]
@rbabayoff The issue may not likely be from Meteor. It seems to come about when multiple instances of Web views are created instead of just one. If more than one web view exists the status bar issue will appear.

**Comment by glasser** [comment]
Thanks for the feature request! We welcome discussions about how to make Meteor better. If you haven't yet, check out our wiki page about [feature requests on GitHub](https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#feature-requests).

**Comment by rbabayoff** [comment]
@glasser, read it many times :) I don't see it as a feature request, just being able to do the same thing in cordova that everybody does in javascript - replace / extend existing meteor classes and methods. Nothing changes whatsover with this code - it's moving exactly the same code from one file to another, to make it more hack / experiment friendly.

**Comment by rbabayoff** [comment]
Hey, I saw that the [cordova 5.0 pr](https://github.com/meteor/meteor/pull/4390) was merged in order to allow people to use [crosswalk](https://github.com/copleykj/meteor/tree/cordova5-update/packages/crosswalk) on android, which is a non-official android web view.

Unlike the cordova 5.0 pr, The PR in https://github.com/meteor/com.meteor.cordova-update/pull/4 has 0 implications by itself whatsoever, it's only code reorganization, extracting the class definition from a .m file to a .h file, so you can use Objective C [swizzling](http://nshipster.com/method-swizzling/) to replace class methods.

But this pr is what my [wkwebview](https://atmospherejs.com/practicalmeteor/wkwebview) package uses to replace meteor's cordova update objective c class in order to have my objective c implementation of autoupdate work with wkwebview, another non-official web view, but this time for ios. 

As you can see from community feedback [here](http://practicalmeteor.com/drastically-improving-the-performance-of-your-meteor-ios-app-with-wkweb%E2%80%8Bview/) it reduces ios app memory consumption by a factor of almost 10 (yes, seriously), and [improves javascript execution](http://developer.telerik.com/featured/why-ios-8s-wkwebview-is-a-big-deal-for-hybrid-development/) by a factor of more than 3.

Can I go ahead and create a PR here in meteor that references my PR there in meteor's webapp package?

As you can see [here](https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine), official support from cordova for wkwebview, introduced by apple in ios 8.0, doesn't seem to be coming soon.

**Comment by martijnwalraven** [comment]
I'm sorry this issue has been open for so long. Given that I'm currently rewriting the file serving and hot code push plugin, and Cordova iOS 4.0 with support for WKWebView will be out soon, I'm closing this now.

**Comment by rbabayoff** [comment]
@martijnwalraven, finally a response :-) I hope you change the name too, because cordova update is really not communicating what this plug in does... What's the ETA? I have many people asking for this here:

https://github.com/practicalmeteor/meteor-wkwebview/issues/8

**Comment by martijnwalraven** [comment]
The new name is `cordova-plugin-meteor-webapp`, hope that's an improvement... (It makes sense if you consider it as part of the core `webapp` package.)

I hope to be able to do a preview release at the end of next month, but that also depends on the state of Cordova iOS 4.0. There are still a few issues to be solved there, especially when it comes to plugin compatibility.
