### ISSUE TITLE
Preview of batch plugins and other 1.2 features

### ISSUE THREAD

**Issue by glasser** [meteor/meteor#4800]
This issue is a good place to track concerns found with the `PLUGINS-PREVIEW@1` release.

We've been working hard over the past few months on a number of features for Meteor 1.2.  @Slava  and I have been focused on adding new capabilities to build plugins, and we have a preview release ready!  Try it out with `meteor --release PLUGINS-PREVIEW@1`.

This release adds new plugin APIs: `Plugin.registerCompiler`, `Plugin.registerLinter`, and `Plugin.registerMinifier`.

`registerCompiler` is a replacement for the now-deprecated `registerSourceHandler` feature. Compilers are like source handlers, but they always run when you're building your app instead of when packages are published, and they have access to all of the relevant files in your app and its packages at once. This lets us implement things like CSS preprocessor `@import`s that work across package boundaries.

`registerLinter` allows you to write linters that handle different file types and show warnings when you run your app or publish a package (or run the new `meteor lint` command).

`registerMinifier` allows you to define your own minifiers to use instead of the standard minifiers, which are no longer baked into the tool but now can be replaced.

The new APIs are documented at https://github.com/meteor/meteor/wiki/Build-Plugins-API

Some notes:

* You'll need to add the `standard-minifiers` package to your app when testing this. (When this is released for real as Meteor 1.2, `meteor update` will add that to your app automatically.)
* The `less` and `stylus` packages now support cross-package imports!  If you specify a file like `@import "{package}/file.js"` (with the curly braces), it will load the file from that package. Use `@import "{}/file.js"` to load a file from your app.
* There's a new core `jshint` package which is a linter for js files using JSHint.
* We've made one backwards-incompatible change to packages. To include static assets in packages, you now need to explicitly specify `{isAsset: true}` in your `api.addFiles` call. This is not necessary for static assets in apps, and doesn't affect published packages, just package sources.
* Because of this change to these packages, we've bumped their major version numbers. Packages that include `less` files will need to publish a new version using this preview (or an RC) before you can use them.
* We've improved rebuild time in `meteor run` in various ways, including via new caches and new APIs that allow plugins to define their own caches.
* There's a lot of other stuff in here too! For example, there's a new core `ecmascript` package which uses Babel to let you write Meteor code in ES2015 (similar to `grigio:babel`).  There's automatic compression on the wire for DDP.  There's some improvements to Livequery oplog tailing performance.  There are several months worth of incremental bugfixes.  Pretty exciting!

Were not quite ready for the formal 1.2 release candidate process, but we'd love to hear how this release works for your apps!  And plugin authors (or those interested in becoming plugin authors), we'd love to see how the new APIs work for you!

**Update july 27 (10am PST, by Slava)**: The new `PLUGINS-PREVIEW@2` pre-release has been pushed. The updates from the previous preview:

- fixed some importing from imports bugs in Stylus
- QA'd and tested on Windows (fixed bugs relevant to handling paths)
- all build plugins should prefer using `Plugin.fs` and `Plugin.path` that work with the standard paths (`/C/some path/file.exe` as opposed to `C:\some path\files.exe`)
- fixed import in `accounts-ui`'s less file
- a `jscript` fix for the `babel-compiler` package
- renewed dev-bundle working well for Windows

**Issues to resolve**:

- [ ] https://github.com/meteor/meteor/issues/4839

**Comment by rclai** [comment]
Cool, thanks for getting this up. 

So as I tried to get this to work, other than the typical version constraints to packages that need to get bumped up and setting isAsset to true, I wasn't sure as to what to do when it came to @arunoda's npm package in [this line of code](https://github.com/meteorhacks/npm/blob/master/plugin/init_npm.js#L105). Are server files able to be considered as assets?

**Comment by glasser** [comment]
Ah yeah.  If you're using `meteorhacks:npm`, you should go into the generated `npm-container/package.js` file and edit the api.addFiles line into two lines like this:

```js
api.addFiles(['index.js'], 'server');
api.addFiles(['../../packages.json'], 'server', {isAsset: true});
```

I mentioned this to @arunoda a few days ago and he said he'd improve this before 1.2 is out. (I suspect there's a way to use the new `registerCompiler` support to implement this without needing this addFiles at all, actually!  And hopefully we will simply have npm dependencies in apps be part of core, though I'm not expecting that for 1.2.)

**Comment by rclai** [comment]
What would be the best way for a package that uses a core package say, `stylus`, to use as the version constraint to run this preview?

I noticed that doing `api.use('stylus@1.0.0 || 2.0.0', 'client')` did not work, but rather had to do `'stylus@1.0.0 || 2.0.0-plugins'`.

**Comment by rclai** [comment]
Regarding `meteorhacks:npm`, that's what I had done, after I saw the error, but forgot I had to delete the `npm-container` folder that was created after making the appropriate edits to his build plugin script. So that one is good now.

I tried to add `twbs:bootstrap`, but it gave me this error (FYI I already cloned it to make the glyphicons `{ isAsset: true }` already):

```
While minifying app stylesheet:
   fs.js:439:18: ENOENT, no such file or directory 'packages/twbs_bootstrap/dist/css/bootstrap.css.map'
   at Object.fs.openSync (fs.js:439:18)
   at fs.readFileSync (fs.js:290:15)
   at resolveSourceMapSync
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/node_modules/source-map-resolve/lib/source-map-resolve-node.js:49:39)
   at Object.resolveSync
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/node_modules/source-map-resolve/lib/source-map-resolve-node.js:196:17)
   at Compiler.<anonymous>
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/source-map-support.js:105:42)
   at Array.forEach (native)
   at Compiler.exports.applySourceMaps
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/source-map-support.js:100:27)
   at Object.module.exports
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/index.js:36:14)
   at mergeCss (packages/minifyStd/plugin/minify-css.js:82:1)
   at CssToolsMinifier.processFilesForBundle (packages/minifyStd/plugin/minify-css.js:17:1)
```

**Comment by arunoda** [comment]
About the npm package:

I have add a fix for it and try to update meteorhacks:npm it will update
the npm-container correctly.

**Comment by rclai** [comment]
Oh cool, @arunoda looks like you pushed out an update already for 1.2 support. Thanks.

**Comment by glasser** [comment]
@rclai Unfortunately, it's not possible to publish a single version of a package that works with both new and old versions of stylus.  Use of the new compiler API leads your package to be published in a new format that won't be compatible with pre-1.2 versions of Meteor (and their Version Solvers know to not choose it).  You can write `api.use('stylus@1.0.0 || 2.0.0-plugins')` if you want, but if you publish it with the newer version of Meteor (ie, with the 2.0.0-plugins chosen) then it won't actually be compatible with the old version.  (It's not that every package published with new Meteor is incompatible with old Meteor ... just those that are built with plugins that use the new API.)

**Comment by vjau** [comment]
@glasser 
Reproduction for the console.log bug mentionned in the forum.
With the foo-compiler package found here : https://github.com/vjau/foo-compiler
With the meteor project found here : https://github.com/vjau/foo-compiler-user
When you modify the code in "plugin.js" and save, the app get reloaded and the console.log outputs are mixed with  the messages from the builder.
Hope that helps.

**Comment by glasser** [comment]
@vjau Hmm. I don't know how much this is a regression.  The progress bar code runs by printing messages without a trailing newline, followed by `\r` to move the cursor to the beginning of the line. If you go and print stuff while there's a progress bar running, it'll interact poorly with that.  But the sort of low level code that runs inside buildmessage jobs shouldn't really interact with the user (see eg https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#only-user-interface-code-should-engage-with-the-user) ... console.log is not really part of the Plugin interface; none of MDG's plugins print to the console.

That said, we haven't defined other APIs for non-error outputs from plugins, and I can see why you'd want to print in your plugin even if it's not really the right level of abstraction.  As a workaround, you can always print a bunch of spaces first...

@justinsb wrote the original progress code; any thoughts?

**Comment by vjau** [comment]
@glasser I understand, however, how are you supposed to debug build plugins ? 
meteor debug doesn't seems to work, "debugger" statements don't cause the code to halt.

**Comment by Slava** [comment]
@vjau there is no a special command for debugging the build process, but you can always edit the `meteor` script that runs node and add the `--debug-brk` or `--debug` key to it. And then connect with the `node-inspector` command.

Admittedly, it would be easier to do this if there was a special command.

An alternative method is to keep all your "compilation" functionality in the regular part of your package and then depend on it in the build-plugin.

**Comment by glasser** [comment]
You could use emacs shell, which uses a different progress bar implementation without this issue :)

**Comment by justinsb** [comment]
@glasser Console is the class to use to produce output from the tool.  Do we expose this to plugins?

And then Console.debug is the function to call for debug output, controlled by the METEOR_LOG=debug env var

**Comment by dandv** [comment]
> To include static assets in packages, you now need to explicitly specify {isAsset: true}

What qualifies as a static asset? Anything that won't be minified or compiled? Is a `.css` file a static asset?

**Comment by Slava** [comment]
@dandv anything that is not matched by linters or compilers.

CSS is not a static asset unless you explicitly mark it as such.

**Comment by Slava** [comment]
The new `PLUGINS-PREVIEW@2` pre-release has been pushed. The updates from the previous preview:

- fixed some importing from imports bugs in Stylus
- QA'd and tested on Windows (fixed bugs relevant to handling paths)
- all build plugins should prefer using `Plugin.fs` and `Plugin.path` that work with the standard paths (`/C/some path/file.exe` as opposed to `C:\some path\files.exe`)
- fixed import in `accounts-ui`'s less file
- a `jscript` fix for the `babel-compiler` package
- renewed dev-bundle working well for Windows

**Comment by rclai** [comment]
I am still getting this error (not sure if you guys saw it above):

```
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   fs.js:439:18: ENOENT, no such file or directory 'packages/twbs_bootstrap/dist/css/bootstrap.css.map'
   at Object.fs.openSync (fs.js:439:18)
   at fs.readFileSync (fs.js:290:15)
   at resolveSourceMapSync
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/node_modules/source-map-resolve/lib/source-map-resolve-node.js:49:39)
   at Object.resolveSync
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/node_modules/source-map-resolve/lib/source-map-resolve-node.js:196:17)
   at Compiler.<anonymous>
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/source-map-support.js:105:42)
   at Array.forEach (native)
   at Compiler.exports.applySourceMaps
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/source-map-support.js:100:27)
   at Object.module.exports
   (/root/.meteor/packages/standard-minifiers/.0.0.1-plugins.0.ymg3pu++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/css-stringify/node_modules/css/lib/stringify/index.js:36:14)
   at mergeCss (packages/minifyStd/plugin/minify-css.js:82:1)
   at CssToolsMinifier.processFilesForBundle (packages/minifyStd/plugin/minify-css.js:17:1)
```

To reproduce all you have to do is `meteor add twbs:bootstrap`, but making sure you use [this package.js](https://github.com/twbs/bootstrap/blob/master/package.js) (that they've just merged but haven't published yet).

My `packages` file:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
standard-minifiers # JS/CSS minifiers run for production mode
autopublish # publishes all data to the clients for prototyping
insecure # allows all DB writes from clients for prototyping
ecmascript # allows ECMAScript2015+ syntax by default


twbs:bootstrap
```

**Comment by Slava** [comment]
@rclai can you please create a repository with a local package and necessary files checked in?

**Comment by Slava** [comment]
I see, it happens because the compiled bootstrap file references a sourcemaps that is not added to the package and the error handling fails to ignore this.

**Comment by rclai** [comment]
Do you still need a repo?

**Comment by Slava** [comment]
@rclai I just disabled the input sourcemaps in the minifier if the sourcemap is referenced in the stylesheet itself. https://github.com/meteor/meteor/commit/6ab8afdcddcbdd1c9227d6d6de704511c1303f15

**Comment by sebakerckhof** [comment]
I think we need to specify something is an asset, that should be included in the package, but not in the final meteor build.

E.g. I develop a meteor application, using a package-based architecture. All of these packages define a part of my CSS (using a CSS pre/postprocessor). However, my mixins and CSS preprocessor variables (e.g. color scheme) have to be included into each package.
Instead, it'd be better if I could define these once in my core package and other packages could refer to these.

One part of this seems to be solved by allowing easy references to other packages using the bracket syntax. However, to have this variables and mixin files included in my package, I need to mark these as an asset. But I guess that'll make them also included in the final build (meteor build) and available via the webapp), which is not what I need/want.

**Comment by Slava** [comment]
@sebakerckhof I didn't quite understand what you mean, but the cross-packages imports system doesn't require anything to be marked as an asset. The only distinction the new `less` and `stylus` packages care about is the `isImport` property.

If you have any further concerns, please help me understand them better with more code samples or example apps repos.

**Comment by rclai** [comment]
Thanks for the fix @Slava, do you know when you guys will do another preview release?

**Comment by sebakerckhof** [comment]
@Slava okay, first time I hear of the isImport property. I looked it up in the less package, and that does what I meant :).

**Comment by mizzao** [comment]
@rclai getting the same error and also waiting for an updated release.

In the meantime, removing `standard-minifiers` allows the app to work now in development mode.

**Comment by sayawan** [comment]
ES2015+ features don't work on the server side unless I manually install `ecmascript` package. I created definitely same files on the client and the server. Works on client, not server.

```
let test = "testing";
^^^
SyntaxError: Unexpected strict mode reserved word
```

Release: PLUGINS-PREVIEW@2

**Comment by Slava** [comment]
@sayawan  this is by design. The new ES2015 compiler is enabled only if your app uses this package `ecmascript`. Same goes for packages.

We do add the `ecmascript` package by default to every *new* app. The existing apps would need to add it explicitly if they want to start using it..

**Comment by rclai** [comment]
Is `ecmascript` not available on `1.1.0.2` or does it only work in the preview release only?

```
While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: ecmascript 0.1.3-plugins.1

```

**Comment by Slava** [comment]
@rclai correct, it only works in the preview and is planned to be shipped with 1.2.

**Comment by raix** [comment]
`PLUGINS-PREVIEW@2`
`$ meteor run android` results in:
```bash
Error while running for mobile platforms: Error running
/Users/raix/.meteor/packages/meteor-tool/.1.1.4-plugins.3.1ko6pzy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Current working directory is not a Cordova-based project.
```
*I've tried reinstalling meteor*

**Comment by woniesong92** [comment]
for `devel` branch I am getting

```
* These packages have been updated to new versions that are not backwards
compatible.
Error while running for mobile platforms: ENOENT, open                             
'~/meteorRepos/meteorDevelop/tools/cli/static-assets/cordova-bootstrap-page/meteor_cordova_loader.js'
```

any ideas?

**Comment by Sanjo** [comment]
I can no longer add a file as source file and also as asset:

```
api.addFiles(['src/lib/VelocityTestReporter.js'], ['server', 'client'])
api.addFiles(['src/lib/VelocityTestReporter.js'], 'server', {isAsset: true})
```

Now gives the error:

```
=> Errors prevented startup:                  
   
   While reading package from `/Users/jonas/Projects/sanjo:jasmine/test-app/packages/sanjo-jasmine`:
   package.js:118:7: Duplicate source file: src/lib/VelocityTestReporter.js
   at package.js:118:7
   at 
   
   
=> Your application has errors. Waiting for file change.
```

I can work around that if you decide to leave it like that. Just wanted to let you know that this is a breaking change.

**Comment by woniesong92** [comment]
+1 on `Current working directory is not a Cordova-based project` with the latest devel branch

**Comment by dgreensp** [comment]
`devel` currently has some Cordova issues, but the relevant code has been rewritten in a branch that is going to land soon, so hang tight.

**Comment by stubailo** [comment]
This is the new place to comment about Release 1.2 stuff: https://github.com/meteor/meteor/issues/4943

You can also file a new issue, just put [Release 1.2] in the title.
