### ISSUE TITLE
meteor run ios-device serves old code

### ISSUE THREAD

**Issue by woniesong92** [meteor/meteor#4883]
Reproduce:

1. meteor run ios-device
2. run the app from xcode
3. make some changes
4. you will notice that the app is broken. From xcode, terminate the app and run again.
5. the changes you made from step 3. are not applied.
6. Terminate the app from xcode, terminate the connection from terminal (ctrl-c).
7. Do meteor run ios-device again
8. Run the app from xcode agin
9. The app finally has the changes from step 3.

This happens sporadically (and very frequently), forcing you to disconnect from terminal every time you make some changes. If all the code changes are correctly "hot pushed" to the device, it would be wonderful. I was under the impression that I was doing something wrong, but another person also reported the same problem on the Meteor [forum](https://forums.meteor.com/t/developing-a-mobile-app-with-meteor/7900/2).

**Comment by avital** [comment]
@martijnwalraven is currently working on a lot of significant changes to our Cordova environment including upgrading lots of Cordova dependencies. I believe he was planning on taking a look at these Cordova hot code push issues, but not sure if he got to them. @martijnwalraven, can you chime in?

**Comment by martijnwalraven** [comment]
There are definitely issues with hot code push, but I'm not sure that's what's going on here.

What changes do you make at step 3, and what does 'the app is broken' mean?

If by 'broken' you mean the server app isn't running anymore, it makes sense the changes are not applied, because there is no way to do a hot code push.

What is puzzling to me is why terminating the server app and doing another `meteor run ios-device` would work, because those same changes that broke the app the first time would still be there. Can you give me more information about those changes and the resulting error?

**Comment by sferoze** [comment]
Noticed the same issue. I cannot even use the command `meteor run ios-device`. 

It always brings up the old app. The reason I want to run ios-device vs just ios is I want to try in different simulators. But I cant do it. I guess I have to try building first.

**Comment by pmwisdom** [comment]
I have a variation of this that happens to me, I cant pin point exactly why or when its happening. I think this is the same thing as the OP is talking about. Still trying to wrap my head around it.

Steps are, 
meteor run ios-device. 
Quit app, quit xcode, uninstall app from device.
Make changes, maybe add a new plugin, code changes, etc, ive seen it mostly when adding / remove plugins.
meteor run ios-device
Now if you look in xcode under plugins it will be the original plugins when you first ran xcode, not the most recent meteor run.

The way i've been getting around this is to do a meteor reset in between meteor run ios-device.

**Comment by dagatsoin** [comment]
Same here.

**Comment by martijnwalraven** [comment]
I believe this has been fixed in Meteor 1.3! A new beta is now available, please give it a try: https://github.com/meteor/meteor/issues/6266.

**Comment by mikeislearning** [comment]
This has been a massive issue for me lately. I've done everything suggested in this list, and it still shows an html and js file in the state I was using 5 hours ago, with none of my modifications.
Upgrading to 1.3 just generates an entirely new set of errors.
What can I do to guarantee I begin with a fresh app? The code reloads fine on web, but it's a nightmare with ios-device.

**Comment by martijnwalraven** [comment]
@mikeislearning: Not sure what your specific issue is, but there have been huge improvements to the Cordova integration and hot code push implementation in Meteor 1.3, so I think it is worth the upgrade.

**Comment by mikeislearning** [comment]
@martijnwalraven Thanks for the quick response.
With the 1.3 upgrade though, I'm getting the same error as @mikepaszkiewicz in https://github.com/meteor/meteor/issues/6050
Ionic-keyboard errors out, even though I have not installed it.

`While adding plugin com.ionic.keyboard@1.0.4 to Cordova project:
   Cordova error: Failed to fetch plugin com.ionic.keyboard@1.0.4 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   Error: Registry returned 404 for GET on http://registry.npmjs.org/com.ionic.keyboard
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)`

Using --verbose doesn't help much.

**Comment by martijnwalraven** [comment]
`com.ionic.keyboard` is probably a dependency of one of the other plugins you have installed. Could you post a list of the plugins and versions in your project?

**Comment by mikeislearning** [comment]
Damn, crazy fast :P
I am using the Meteoric package, so I'd say there's a good chance it's in there.
However, that package provides the entire UI for the app. If I have to remove it, that would not be ideal.

Here's the list
`accounts-ui                  1.1.6  Simple templates to add login widgets to an app
alanning:roles               1.2.14* Authorization package for Meteor
aldeed:collection2           2.7.0* Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema         1.5.1* A simple schema validation object with reactivity. Used by collection2 and autoform.
blaze-html-templates         1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                        1.1.1-cordova.5* Check whether a value matches a pattern
dburles:collection-helpers   1.0.4  Transform your collections with helpers that you define
ddp                          1.2.2  Meteor's latency-compensated distributed data framework
ddp-rate-limiter             1.0.1-cordova.5* The DDPRateLimiter allows users to add rate limits to DDP methods and subscriptions.
ecmascript                   0.4.0-cordova.5* Compiler plugin that supports ES2015+ in all .js files
ejson                        1.0.8-cordova.5* Extended and Extensible JSON library
fastclick                    1.0.8-cordova.5* Faster touch events on mobile
fourseven:scss               2.1.1* Style with attitude. Sass and SCSS support for Meteor.js (with autoprefixer and sourcemaps).
houston:admin                2.0.6  A zero-config Meteor Admin
http                         1.1.2-cordova.5* Make HTTP calls to remote servers
iron:layout                  1.0.12  Dynamic layouts which enable rendering dynamic templates into regions on a page.
iron:router                  1.0.12  Routing specifically designed for Meteor
jquery                       1.11.5-cordova.5* Manipulate the DOM using CSS selectors
kadira:debug                 2.2.4* Full Stack Debugging Solution for Meteor
localstorage                 1.0.6-cordova.5* Simulates local storage on IE 6,7 using userData
logging                      1.0.9-cordova.5* Logging facility.
manuel:reactivearray         1.0.5  Reactive Array for Meteor
matb33:collection-hooks      0.8.1  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteor-base                  1.0.1  Packages that every Meteor app needs
meteorhacks:kadira           2.26.3* Performance Monitoring for Meteor
meteorhacks:kadira-profiler  1.2.1  CPU Profiler for Meteor (used with Kadira)
meteoric:ionic               0.1.19* Ionic components for Meteor. No Angular!
meteoric:ionic-sass          0.1.9* Ionic's CSS Framework in SASS and bundled for Meteor.
meteoric:ionicons-sass       0.1.6* Ionic's Ionicons library in SASS and bundled for Meteor.
mobile-experience            1.0.1  Packages for a great mobile user experience
modules                      0.5.0-cordova.5* CommonJS module system
momentjs:moment              2.10.6* Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                        1.1.4-cordova.5* Adaptor for using MongoDB and Minimongo over DDP
npm-bcrypt                   0.7.8_2  Wrapper around the bcrypt npm package
particle4dev:cordova-fb      1.1.3  Login service for Facebook accounts (works with cordova)
percolate:momentum           0.7.2  Reactive animations
random                       1.0.6-cordova.5* Random number generator and utilities
rate-limit                   1.0.1-cordova.5* An algorithm for rate limiting anything
reactive-var                 1.0.6  Reactive variable
reload                       1.1.5-cordova.5* Reload the page while preserving application state.
reywood:publish-composite    1.4.2  Publish a set of related documents from multiple collections with a reactive join
service-configuration        1.0.6-cordova.5* Manage the configuration for third-party services
session                      1.1.2-cordova.5* Session variable
sha                          1.0.4  SHA256 implementation
spacebars                    1.0.8-cordova.5* Handlebars-like template language for Meteor
srp                          1.0.5-cordova.5* Library for Secure Remote Password (SRP) exchanges
standard-minifier-css        1.0.3-beta.12  Standard css minifier used with Meteor apps by default.
standard-minifier-js         1.0.3-beta.12  Standard javascript minifiers used with Meteor apps by default.
tracker                      1.0.10-cordova.5* Dependency tracker to allow reactive callbacks
underscore                   1.0.5-cordova.5* Collection of small helpers: _.map, _.each, ...`

Also, how are we supposed to install cordova plugins now?

**Comment by martijnwalraven** [comment]
Yeah, `meteoric:ionic` indeed seems to be the culprit. Looking at the [`package.js`](https://github.com/meteoric/meteor-ionic/blob/master/package.js) shows it depends on `ionic-plugin-keyboard`. That shouldn't be a problem, but you are somehow depending on an older version of `meteoric:ionic` that still depends on `com.ionic.keyboard` (the old name, before the move to npm). Any idea what could be causing `meteoric:ionic` to be held back (the current version seems to be 0.2.0)?

Nothing has changed about the way plugins are installed. You can either install them as part of package dependencies or add them directly (`meteor add cordova:cordova-plugin-...`).

**Comment by martijnwalraven** [comment]
And I notice a lot of `-cordova.5` version in there. The most recent version of 1.3 is `beta.12`, so you should really update to that (`meteor update --release 1.3-beta.12`).

**Comment by mikeislearning** [comment]
I've tried to update meteoric:ionic, but it says:
`The specified packages are at their latest compatible versions.`

The only thing I can think is that ionic-sass and ionicons-sass cause an error with fourseven:scss version 3 or higher, so I install version 2, which prevents the errors.
Yay mess!

Am I stuck?

**Comment by martijnwalraven** [comment]
Good to hear that worked!
