### ISSUE TITLE
[1.3-beta2] TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by mquandalle** [meteor/meteor#5871]
I’m not sure how the following exception relates to the actual application code (I wasn’t able to recognize anything from it in the trace) but launching Wekan fails on the latest `1.3-modules-beta.2`:

```
➜  wekan git:(meteor-1.3) meteor
[[[[[ ~/meteor/wekan ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
                                              
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.pathJoin (/home/maxime/.meteor/packages/meteor-tool/.1.1.11-modules.3.bm8prf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/static-assets/server/mini-files.js:86:16)
    at /tools/isobuild/import-scanner.js:52:23
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:51:11)
    at Object.fullLink (/tools/isobuild/linker.js:968:8)
    at /tools/isobuild/compiler-plugin.js:686:28
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at PackageSourceBatch._linkJS (/tools/isobuild/compiler-plugin.js:685:18)
    at PackageSourceBatch.getResources (/tools/isobuild/compiler-plugin.js:586:48)
    at /tools/isobuild/bundler.js:753:37
    at Array.forEach (native)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:736:19)
    at /tools/isobuild/bundler.js:515:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:506:18)
    at /tools/isobuild/bundler.js:2199:14
    at /tools/isobuild/bundler.js:2288:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/maxime/.meteor/packages/meteor-tool/.1.1.11-modules.3.bm8prf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2287:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2180:31)
    at /tools/runners/run-app.js:585:36
    at time (/tools/tool-env/profile.js:238:28)
    at Function.run (/tools/tool-env/profile.js:391:12)
    at bundleApp (/tools/runners/run-app.js:575:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:628:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:402:12
```

You can reproduce the issue by downloading Wekan:

```
$ git clone -b meteor-1.3 --depth 1 git@github.com:wekan/wekan.git
```

**Comment by laurentpayot** [comment]
+1

**Comment by laurentpayot** [comment]
(and I'm simply trying to make the React version of the Simple Todos app work)

**Comment by johanbrook** [comment]
I'm getting a similar issue on the client side: a 3rd party package is using the `templating` package, and utilizes the `Spacebars` global, which is undefined on runtime in the browser when running 1.3-beta.2, but not when accessing it throught `Package.spacebars`.

**Comment by jiku** [comment]
Also having this with a few packages (from #5799). Repro's here with [lalomartins:markd](https://github.com/jiku/meteor-modules/tree/1.3b2) and [ccorcos:cjsx](https://github.com/jiku/meteor-modules/tree/1.3b2-ccorcos-cjsx).

**Comment by avital** [comment]
Should be fixed by https://github.com/meteor/meteor/commit/221d8af44b62b91de50f93077c2b488db4a06dc4 and will be out with `1.3-modules-beta.3` later today.

**Comment by jiku** [comment]
Thanks @benjamn @avital 221d8af checkout seems to fix it here.

**Comment by avital** [comment]
`1.3-modules-beta.3` was just released.

**Comment by newsiberian** [comment]
Hello, I see this error while trying to run `1.3-modules-beta.4` on [reaction](https://github.com/reactioncommerce/reaction)

**Comment by aaronmyhre** [comment]
+1 also getting on 1.3-modules-beta.4

**Comment by benjamn** [comment]
This seems to be fixed in `1.3-modules-beta.7` (and possible before that, too).

**Comment by newsiberian** [comment]
@benjamn, nope, bug still presents. At least in [`reaction`](https://github.com/reactioncommerce/reaction) with `beta.7`

**Comment by newsiberian** [comment]
For me it become work again after commenting out [this](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/package.js#L260-L261) lines and [this](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/package.js#L308-L314)

**Comment by aaronmyhre** [comment]
+1 still doesn't work in beta.7 

Any explanation of whats causing this bug, or how it can be resolved on our end?

**Comment by aaronmyhre** [comment]
Still doesn't work in beta.8

**Comment by avital** [comment]
@newsiberian When I try running reaction with 1.3-modules-beta.8 I get:

```
=> Using Meteor 1.3-modules-beta.8 as requested (overriding Meteor 1.2.1)

[[[[[ ~/tmp/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building package reactioncommerce:core:
   error: Bower dependencies list must be a dictionary in lib/bower/classie/bower.json
   error: Bower dependencies list must be a dictionary in lib/bower/eventEmitter/bower.json
   error: Bower dependencies list must be a dictionary in lib/bower/eventie/bower.json
   error: Bower dependencies list must be a dictionary in lib/bower/get-style-property/bower.json
   error: Bower dependencies list must be a dictionary in lib/bower/jquery/bower.json
   error: Bower dependencies list must be a dictionary in lib/bower/tether/bower.json

=> Your application has errors. Waiting for file change.
```

Can someone describe how to reproduce this problem?

**Comment by newsiberian** [comment]
@avital, hello, I don't see this bug after `beta-8`. This bower errors could be fixed by adding `dependencies: {}` to those JSON files

**Comment by zol** [comment]
Looks like this is fixed in the latest betas. Please re-open if it returns.

**Comment by aaronmyhre** [comment]
I still get this error in beta.11

`TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /Users/aaronmyhre/.meteor/packages/meteor-tool/.1.1.13-beta.11.m84s9s++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:86:16
    at /tools/isobuild/import-scanner.js:87:23
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:86:11)
    at /tools/isobuild/compiler-plugin.js:691:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:672:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/aaronmyhre/.meteor/packages/meteor-tool/.1.1.13-beta.11.m84s9s++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

Process finished with exit code 8`

**Comment by luisatlive** [comment]
Ditto, trying to build workpop

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /Users/luis/.meteor/packages/meteor-tool/.1.1.13-beta.11.sne8ed++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:86:16
    at /tools/isobuild/import-scanner.js:87:23
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:86:11)
    at /tools/isobuild/compiler-plugin.js:691:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:672:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/luis/.meteor/packages/meteor-tool/.1.1.13-beta.11.sne8ed++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

**Comment by hunius** [comment]
Same here with beta.11 after adding poetic:react-autoform-material-ui, aldeed:autoform and react:

=> Started proxy.
=> Started MongoDB.

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at /Users/hunius/.meteor/packages/meteor-tool/.1.1.13-beta.11.uoh1tu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:86:16
    at /tools/isobuild/import-scanner.js:87:23
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:86:11)
    at /tools/isobuild/compiler-plugin.js:691:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:672:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/hunius/.meteor/packages/meteor-tool/.1.1.13-beta.11.uoh1tu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

**Comment by hunius** [comment]
Works for me. Thanks a lot!

**Comment by benjamn** [comment]
Wekan works in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852) for me now, so I'm tentatively optimistic that this bug has finally been squashed.

**Comment by aaronmyhre** [comment]
Woot - works on beta.12 for me as well. Thanks! Excited to try out 1.3!
