### ISSUE TITLE
.babelrc in toplevel folder causes meteor failed to start.

### ISSUE THREAD

**Issue by haiodo** [meteor/meteor#6016]
Steps to reproduce:

1. mkdir somedir && cd somedir
2. Create file echo "{\"presets\": [\"es2015\", \"react\"]}" > .babelrc
3. meteor create myapp
4. cd myapp
5. meteor 

So it fail.

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):

   /Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
   [BABEL] random.js: Unknown option: /Users/haiodo/Develop/git/meteor-fail/.babelrc.presets
   at Logger.error
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
   at OptionManager.mergeOptions
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
   at OptionManager.addConfig
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
   at OptionManager.findConfigs
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
   at OptionManager.init
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
   at File.initOptions
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
   at new File
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
   at Pipeline.transform
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)
   
   
   While processing files with ecmascript (for target os.osx.x86_64):

   /Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11:
   [BABEL] ecmascript.js: Unknown option: /Users/haiodo/Develop/git/meteor-fail/.babelrc.presets
   at Logger.error
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
   at OptionManager.mergeOptions
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
   at OptionManager.addConfig
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
   at OptionManager.findConfigs
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
   at OptionManager.init
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
   at File.initOptions
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
   at new File
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
   at Pipeline.transform
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
   at
   /Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:26:18
   at Cache.Cp.get
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/cache.js:89:19)
   at Object.compile
   (/Users/haiodo/.meteor/packages/ecmascript/.0.1.6.ubrk56++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/babel-compiler/node_modules/meteor-babel/index.js:20:23)
   at Object.Babel.compile (packages/babel-compiler/babel.js:42:1)
   at packages/babel-compiler/babel-compiler.js:58:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:17:1)
   
   
=> Your application has errors. Waiting for file change.

```

So question is why meteor care *.babelrc* folder not in meteor folder?

Thanks.

**Comment by stubailo** [comment]
@benjamn, could you take a look at this?

**Comment by jlipps** [comment]
I am also experiencing this issue setting up a new meteor + babel project

**Comment by pscanf** [comment]
Same issue, though the use case is a bit different. The meteor application is in a sub-folder of a "standard" node project, which has a `.babelrc` file at root level. Meteor still picks it up and fails to start.

Strangely, the issue "comes and goes" in my local environment (not on travis though), but I haven't been able to identify what causes it.

**Comment by thomasvanlankveld** [comment]
Same problem here. Tried moving babel configuration to `package.json`, which doesn't change much.

Is there a way to have Meteor ignore external configuration for Meteor's `ecmascript` package? I'm using `.babelrc` to ESNext Cucumber tests that I run with `babel-node`, so I don't need the babel configuration for my Meteor project.

**Comment by grsabreu** [comment]
Same problem here

**Comment by grsabreu** [comment]
Even if the meteor app is nested with the main git dir and the packages.json with babel option or .babelrc on the top level it still getting the issue.
Something like this.

```
toplevel/
--app/
--.babelrc
```

**Comment by grsabreu** [comment]
For now the workaround I'm using is to use the option `env` within my .babelrc:

```json
{
  "env": {
    "dev": {
      "presets": ["es2015", "stage-2"],
      "plugins": ["babel-root-slash-import"]
    }
  }
}
```

then run my npm command with the env

```sh
BABEL_ENV=dev npm run testonly
```

**Comment by bpartridge** [comment]
Also needed to work around this in our app, which builds on https://github.com/jedwards1211/meteor-webpack-react to compile (using webpack) into a subdirectory in which Meteor runs. Therefore, our top-level .babelrc was messing things up per this bug. Needed to move all the .babelrc options into https://github.com/babel/babel-loader `query` param as a workaround.

**Comment by thomasvanlankveld** [comment]
Moved config to `tests/.babelrc`. I can now run my app with `meteor` and my tests with `babel-node`.

**Comment by benjamn** [comment]
I think this can be fixed in the `babel-compiler` package by passing `{ babelrc: false}` to `Babel.transform`.

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852), though we may try to reenable Babel configuration files (either `.babelrc` or `package.json`) in the 1.3.1 release.

**Comment by vonwao** [comment]
I upgraded to beta.12, and I'm still getting this "Missing class properties transform." 

So I can't configure babel via .babelrc?  How am I supposed to get things working...

React requires class properties in some cases (e.g. childContextTypes).  Do I have to rewrite my code to not use React class syntax?

**Comment by alphashuro** [comment]
I'm getting the class properties error too, if i understand correctly using stage-0 or stage-1 presets solves this, how do we configure babel to use them now?

**Comment by jedwards1211** [comment]
Is there any way to remove the `babel-compiler` Meteor package completely?  I'm not even using it, I just compile all of my code with Webpack and `babel-loader`.  Yet it still runs even if `babel-compiler` is not in my top-level `packages`.

**Comment by gitTerebi** [comment]
Meteor isn't ignoring the .babelrc file

**Comment by jedwards1211** [comment]
For those who are having problems feel free to try https://github.com/jcoreio/crater, which puts you fully in charge of babel and webpack processing of your own code, instead of having to run it through isobuild.
