### ISSUE TITLE
[1.3-modules-beta.4] react-jade: dependencies not found, and more...

### ISSUE THREAD

**Issue by laurentpayot** [meteor/meteor#6035]
Hi, like <i>many</i> people I'm trying to use the [react-jade](https://github.com/pugjs/react-jade) npm package with meteor **1.3** beta.X.

I'm installing the simple todos app and simply trying to "import" the react-jade module this way:
```
meteor create --example simple-todos-react
cd simple-todos-react/
meteor update --release 1.3-modules-beta.4
meteor update
npm install react-jade
mkdir client
echo "var jade = require('react-jade');" >> client/rj.js
meteor
```

Because in my browser console I get `Cannot find module 'stream'` and `Cannot find module 'emitter'` (not a good sign) I have to do the following:
```
npm install stream
npm install emitter
```

Then I'm stuck because of `Uncaught TypeError: Emitter is not a function` after the following code of `index.js` of the `stream` module is executed:

```javascript
var Emitter = require('emitter');

function Stream() {
  Emitter.call(this);
}
Stream.prototype = new Emitter();
```

Am I doing something wrong? Any idea of a workaround?

**Comment by benjamn** [comment]
Core Node modules are currently only importable on the server, which is why you have to install your own mock packages to use them on the client.

I think the `emitter` package you're installing has a slightly different API than you expect. Try `var Emitter = require("emitter").EventEmitter`?

**Comment by laurentpayot** [comment]
Thanks @benjamn, replacing `var Emitter = require("emitter")` by `var Emitter = require("emitter").EventEmitter` in the `stream` module makes the build go further :+1: 

To make it go even further I had to install `fs`, `path`, [buffer](https://github.com/feross/buffer) and `events` modules 
and to add the following line at the beginning of my 'client/rj.js` file:
```javascript
Buffer = require('buffer').Buffer; // global
```

But now I'm stuck with `util.inherits is not a function` in `meteor://💻app/node_modules/readable-stream/lib/_stream_readable.js`. In this file you can see the following code:
```javascript
var util = require('core-util-is');
util.inherits = require('inherits');
```
`require('inherits')` is actually <b>undefined</b>.
Installing `inherits` module didn't change anything. Any idea?

**Comment by benjamn** [comment]
Umbrella issue tracking support for stub versions of built-in modules: https://github.com/meteor/meteor/issues/6056

**Comment by bompi88** [comment]
I got the same error `util.inherits is not a function` when trying to use the latest version of npm package `elasticsearch`. While I'm waiting for the shims for the built-in modules, I decided to add the meteor package `meteorhacks:npm` and put my dependencies inside the newly created `packages.json`. I then can use Elasticsearch by doing the following:

``` js
ElasticSearch = Meteor.npmRequire('elasticsearch');
```

It works as a work-around for the time being. When the shims arrives, I'll just remove `packages.json` (__NOT__ `package.json`), remove the package `meteorhacks:npm` and rewrite my import to something like:

``` js
ElasticSearch = require('elasticsearch');
```

**Comment by laurentpayot** [comment]
Thanks @bompi88 , but the `npmRequire` function is server-side only. Tomorrow I will to make it work client-side with method calls and see what I get...

**Comment by laurentpayot** [comment]
@bompi88 unfortunately `Meteor.npmRequire()` is server-side only.
Now I remember that a long time ago I tried to make [meteorhacks:npm + cosmos:browserify](https://react-in-meteor.readthedocs.org/en/latest/client-npm/) work with react-jade client-side but it was just not working. Other people couldn't make it work either.

**Comment by benjamn** [comment]
This should be fixed in beta.16, thanks to #6056.

**Comment by laurentpayot** [comment]
Still can't make `react-jade` work with beta 16.
I have to do the following (long) sequence of commands :
```
meteor create --example simple-todos-react
cd simple-todos-react/
meteor update --release 1.3-beta.16
meteor update
mkdir client
echo "Buffer = require('buffer/').Buffer;" >> client/rj.js
echo "var jade = require('react-jade');" >> client/rj.js
npm install react-jade
npm install stream
npm install emitter
npm install fs
npm install path
npm install buffer
npm install events
npm install assert
sed -i s/"require('emitter');"/"require('emitter').EventEmitter;"/ node_modules/stream/index.js
meteor
```
and then I get :
> Uncaught TypeError: fs.realpathSync is not a function

`fs` module seems to be an empty shell. Is that normal ?

**Comment by laurentpayot** [comment]
On client side `fs` module is just a stub, simply "commenting" the file requiring it :
`echo "" > node_modules/uglify-js/tools/node.js`

Then I get :
> Uncaught Error: Cannot find module 'vm'

And I'm stuck...
