### ISSUE TITLE
Beta 11 - `...args` not working on inner function - Babel error?

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#6312]
Using beta 11 with the latest version of flow-router-ssr, I've been tracking down a new issue relating to the handling of triggers. It seems that the problem is caused by an issue with the Babel compilation.

The original source looks like this:

```javascript
  _runTriggers(triggers, context) {
    let redirectArgs;
    const redirectFn = (...args) => {
      if (/^http(s)?:\/\//.test(args[0])) {
        const message = `
          Redirects to URLs outside of the app are not supported
          in this version of Flow Router.
          Use 'window.location = yourUrl' instead.
        `;
        throw new Error(message);
      }
      redirectArgs = args;
    };

   ... 
```

This is transpiled into the following javascript:

```javascript

Router.prototype._runTriggers = function () { 
    function _runTriggers(triggers, context) {
      var redirectArgs = undefined; 
      var redirectFn = function () { 
        function redirectFn() {
          for (var _len = _arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
            args[_key] = _arguments[_key];
          }

          if (/^http(s)?:\/\//.test(args[0])) {
            var message = '\n          Redirects to URLs outside of the app are not supported\n          in this version of Flow Router.\n          Use \'window.location = yourUrl\' instead.\n        ';
            throw new Error(message);
          } 
          redirectArgs = args; 
        }

        return redirectFn;
      }();    

   ...
```

Note how the `redirectFn` uses `_arguments`. When tracing the code `_arguments` has this value:

```
[require(id), Object, Module, "/node_modules/meteor/kadira:flow-router-ssr/client/router.js", "/node_modules/meteor/kadira:flow-router-ssr/client"]
```

whereas if I print `arguments` (without the underscore) I get the arguments that are passed in:

```
["/browse", undefined, undefined]
```

Clearly the generated code is doing the wrong thing. It should be accessing `arguments` instead of `_arguments`.

**Comment by benjamn** [comment]
This will be fixed in the next beta.

**Comment by benjamn** [comment]
Fixed in [`beta.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-190789852).

**Comment by timothyarmes** [comment]
I'm testing the beta 1.3 release candidate and this bug still isn't fixed.

**Comment by dufia** [comment]
Same here, I get:

```
Uncaught TypeError: str.slice is not a function
```
