### ISSUE TITLE
[1.3b12 - aws-sdk npm still isn't working]

### ISSUE THREAD

**Issue by ciwolsey** [meteor/meteor#6373]
Trying to use the s3/aws-sdk, when importing or requiring aws-sdk npm I get:
```
Error: Cannot find module '/node_modules/aws-sdk/apis/metadata.json'
```

There's a previous issue that's been closed stating it will work in beta 12 on the client but I'm trying to import it on the server and it's not working.

**Comment by benjamn** [comment]
The problem on the server is that we don't bundle files that are not imported, and `aws-sdk` relies on dynamic `require` calls (on the server). The workaround is to continue using a Meteor wrapper package like `peerlibrary:aws-sdk`, which uses the old `Npm.depends` and `Npm.require`: https://github.com/meteor/meteor/issues/6285#issuecomment-189926817

**Comment by benjamn** [comment]
If you really want to use `npm install aws-sdk` on the server, you can give the dependency scanner clues so that dynamic `require` calls will succeed at runtime, e.g. explicitly calling `require("aws-sdk/apis/metadata.json")` in your own code.

Bundling all possible files on the server is a possibility, but not worth the extra build time, given these workarounds. Happy to take feedback on that tradeoff, though!

**Comment by ciwolsey** [comment]
thanks

**Comment by benjamn** [comment]
This is fixed in beta.16, thanks to #6398.

**Comment by gsabran** [comment]
very nice

**Comment by vladgolubev** [comment]
@benjamn Still occurs on 1.4 when my npm package requires aws-sdk. Didn't happen on 1.3.2.4.

**Comment by abernix** [comment]
@vladgolubev This issue is closed and resolved.  Please make a basic reproduction of your problem in a new Meteor project per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) instructions and open a new repository.  We will not be able to investigate your issue without this.
