### ISSUE TITLE
[1.3-beta.16] Error: Can't find npm module 'meteor-deque'

### ISSUE THREAD

**Issue by Deadly0** [meteor/meteor#6448]
Got error after updating from beta 12 to beta 16:
``Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?``

I need to install it manually now?

Windows 8.1

**Comment by stphdenis** [comment]
It is the same with a fresh install.

**Comment by Deadly0** [comment]
@stphdenis what is your OS?

**Comment by hakima** [comment]
Got the same error.

Windows 10 64Bit

**Comment by staskorz** [comment]
Same here: Windows 7 SP1 64bit

**Comment by lyquocnam** [comment]
same here, windows 10 x64, this awesome :3

**Comment by gbersani** [comment]
Same error.
Windows 10 x64

**Comment by AnnotatedJS** [comment]
I have closed, [1.3-beta.16] [Windows] Did you forget to call 'Npm.depends' #6474

**Comment by Vincent-P** [comment]
Same here, it seems to be Windows specific.

**Comment by Rebolon** [comment]
same with W10 64bits

**Comment by alexyuly** [comment]
Same here. Windows 8.1 64-bit.

**Comment by tab00** [comment]
Is this fixed yet? rc1 is out.

**Comment by brucejo75** [comment]
Don't know if this is helpful or not.  But in an attempt to get past this I ran "meteor reset".  Once I did this, I no longer got the `can't find npm module: meteor-deque` error.  Now I get this:

   `While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:flow-router/client.browserify.js: Cannot read property '0' of undefined`  

   `Browserify options:`
   `\>  undefined`

### my environment:
* Windows 10 Pro x64
* my project is on the E: drive and my meteor install is on the C: drive
* node v5.8.0 x64

### my repro:

1. `meteor create` a new project.
2. add `kadira:flow-router` as the only extra package.
3. `meteor update -release 1.3-beta.16`
4. run `meteor`.  ==> Produces the `can't find npm module: meteor-deque` error
5. `meteor reset`
6. run `meteor` ==> now I get a new error:

`While processing files with cosmos:browserify (for target web.browser): packages/kadira:flow-router/client.browserify.js: Cannot read property '0' of undefined`  
`Browserify options:`
`\>  undefined `

Note: without adding `kadira:flow-router` I continue to get the `can't find npm module: meteor-deque` error.

**Comment by gbersani** [comment]
That's because Meteor is not loading any modules on Windows atm.
Installing meteor-deque manually with npm install will cause another default module to fail.
(in my case, mongodb)

**Comment by Laurentiu-Andronache** [comment]
Same issue here with rc.2

I believe that not properly supporting Meteor.rc on Windows is racism.

**Comment by jakobrosenberg** [comment]
Same issue. I call sexism.

**Comment by redwards1966** [comment]
Same here with rc.2, Windows 10 x64

**Comment by Klatalk** [comment]
Same. rc.2, Windows 8 x64

**Comment by Goatic** [comment]
I've had this issue since trying to upgrade from `beta.8` to `beta.12+`

**Comment by gsabran** [comment]
I've had the same on mac. @brucejo75 don't know if it's related to this https://github.com/meteor/meteor/issues/6449

**Comment by Vincent-P** [comment]
I dont think this error is related to #6449 because #6449 is an error in flow-router whereas Can't find npm module 'meteor-deque'. happend in blanks projects.

**Comment by aqib1604** [comment]
I installed meteor-deque packet manually bt npm install meteor-deque and that resolved the error for me in meteor 1.3 beta 16.

**Comment by tab00** [comment]
> I installed meteor-deque packet manually by "npm install meteor-deque"

I tried that in rc.2 and then got this error when I try to run:
`Can't find npm module 'mailcomposer/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'email' package?`

**Comment by aqib1604** [comment]
> I tried that in rc.2 and then got this error when I try to run:
Can't find npm module 'mailcomposer/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'email' package?

You will get npm modules error you have to install them one by one. Like "npm install mailcomposer"
You have to install all the package dependencies.

**Comment by JeremyBYU** [comment]
Same problem for me.  Windows 10 64 bit, Meteor 1.3 RC2.

**Comment by benjamn** [comment]
This will be fixed in the next RC (`1.3-rc.3` most likely).

**Comment by gsabran** [comment]
Great work! any idea on the timeline?

**Comment by Deadly0** [comment]
1.3-rc.3 works on Windlows! Thank you, guys!

**Comment by gsabran** [comment]
still failing on rc3 on ubuntu when deploying (with meteor up)
```
/opt/appName/app/programs/server/boot.js:324
}).run();
   ^
Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
    at Object.Npm.require (/opt/appName/app/programs/server/boot.js:195:17)
    at Meteor.startup (/opt/appName/app/programs/server/packages/meteor.js:666:32)
    at /opt/appName/app/programs/server/packages/meteor.js:835:4
    at /opt/appName/app/programs/server/packages/meteor.js:1353:3
    at /opt/appName/app/programs/server/boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/appName/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/appName/app/programs/server/boot.js:133:5
error: Forever detected script exited with code: 8
error: Script restart attempt #9
```

**Comment by aqib1604** [comment]
Issue resolved in 1.3-rc.3. yay! :+1:

**Comment by Goatic** [comment]
it is resolved for me too! :+1: feel free to close

**Comment by bevinhex** [comment]
Still have the same issue with ubuntu here people, and now I realize that meteor 1.3 is the most buggy software I've even encounted so far. None of the stuff working with 1.3, ES2015 sucks!

**Comment by Goatic** [comment]
That was a bit emotional... I'm running a Ubuntu 14.04 variant myself, and I have no issues. 
- How is your issues with 1.3 related to ES2015?
- Have you checked versions of your installed sofware and made sure everything is up to date?
- Have you tried reinstalling?

**Comment by bevinhex** [comment]
Indeed, I've been emotional for the past few days, under great depression. Spent days trying to make flow-router work with react-dom as I used to the same with 1.2, but it keeps printing something like cannot find route for '/', Didn't wanted to write react-mount code , it make my code pretty ugly, then end up having to use react-router , a little bit cleaner. Then I tried to use Session.set , well ... got Session undefined, so as the document says, wrote "import { Session } from 'meteor/session'" guess what I got this time!? something like "no npm package found ....", I tried to upgrade my old projects to 1.3 , well... lot's of error messages... 
I gave up using 5 cent OTP microcontrollers because I have to use assembly, really annoying. 
Programming supposed to be fun and "spending whole days trying to figureout why old code doesn't work as it was" isn't in my definition of fun.
Not much people use Ada these days only because it's complicated than C++.

**Comment by janat08** [comment]
still crops up in docker container for meteor on codenvy.

**Comment by jamesgibson14** [comment]
I will get this error message, when I make changes to my package directory or package.js file which usually has nothing to do with the package in the error. Then I can do something like add/remove a semicolon in the package.js file and it will rebuild without any errors.

**Comment by adamgins** [comment]
Hi I am getting this issue while trying to install Meteor 1.5 on IBM Bluemix / Cloud Foundry any ideas pls?
