### ISSUE TITLE
Invalid source maps generated for some of the files

### ISSUE THREAD

**Issue by MasterAM** [meteor/meteor#6506]
I am using v1.3-rc.[1-2] on Ubuntu 14.04.

Since 1.3-rc.1 (or maybe `rc.0`) some of the generated source maps are invalid.
This leads to :

Chrome
 - printing lots of errors to the console (`Failed to parse SourceMap: ...`)
 - not showing the original source file in the `Sources` panel

Firefox
 - not listing those files in the `Debugger`'s `Sources` panel

I assume that it is related to commit https://github.com/meteor/meteor/commit/ad3f56a0bf0de4f28a2476a83f5b695e3ab1d1a0.

Reproduction:
 - Create a Meteor application using the default settings:
```sh
$ meteor create old --release 1.3-beta.16
$ meteor create new --release 1.3-rc.1
$ cd old && meteor --port 4040
# in another terminal
$ cd new && meteor --port 5050
```
 - View the page in Chrome/Firefox and check the developer tools.
 - Look at some of the maps, e.g, `.meteor/local/build/programs/web.browser/packages/base64.js.map`

This may be the intended behavior in order to speed up the build process, but it is worth noting the side-effects and figuring out a better way to handle this.

**Comment by benjamn** [comment]
It's not likely that this has anything to do with https://github.com/meteor/meteor/commit/ad3f56a0bf0de4f28a2476a83f5b695e3ab1d1a0, because the affected files end up not having a source map, rather than having a source map that could be invalid.

**Comment by benjamn** [comment]
Fixed in [`1.3-rc.5`](https://github.com/meteor/meteor/issues/6266#issuecomment-199632139), though I recommend updating to [`1.3-rc.6`](https://github.com/meteor/meteor/issues/6266#issuecomment-199903292) to avoid #6555.

**Comment by tomitrescak** [comment]
I am still getting invalid source maps with 1.3.4. Just install semantic:ui package and you'll get the error.
