### ISSUE TITLE
Meteor keeps restarting

### ISSUE THREAD

**Issue by CTimmerman** [meteor/meteor#6574]
Here's a minimal reproduction: https://github.com/CTimmerman/meteor-xmllint-bug

I'm using Chrome on Windows 10.

**Comment by benjamn** [comment]
Should be fixed in [`1.3-rc.12`](https://github.com/meteor/meteor/issues/6266#issuecomment-201058454).

**Comment by CTimmerman** [comment]
Looping appears to be fixed, but the try catch is still broken:

```
test: updated to Meteor 1.3.

Changes to your project's package version selections from updating package versions:

standard-minifiers  removed from your project


C:\code\Meteor\test>meteor
[[[[[ C:\code\Meteor\test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

I20160329-12:01:58.750(2)?
I20160329-12:01:58.751(2)? RESULT { errors: [ 'file_0.xml:2: element Article: Schemas validity error : Element \'Article\': No matching global declaration available for the validation root.' ] }
=> Exited with code: 3
I20160329-12:02:28.369(2)?
I20160329-12:02:28.371(2)? RESULT { errors: [ 'file_0.xml:2: element Article: Schemas validity error : Element \'Article\': No matching global declaration available for the validation root.' ] }
=> Meteor server restarted
=> Exited with code: 3
I20160329-12:02:47.187(2)?
I20160329-12:02:47.202(2)? RESULT { errors: [ 'file_0.xml:2: element Article: Schemas validity error : Element \'Article\': No matching global declaration available for the validation root.' ] }
=> Meteor server restarted
=> Exited with code: 3
=> Your application is crashing. Waiting for file change.
```

**Comment by CTimmerman** [comment]
I've opened bug 7012 to deal with the remaining issue.
