### ISSUE TITLE
[1.3-rc.10] Build Error: sourcePath outside sourceRoot

### ISSUE THREAD

**Issue by smeijer** [meteor/meteor#6586]
I'm trying to run version **1.3-rc.10** on **Windows 10, x64.** But during build I receive the following error:

```console
c:\dev\my-project\src
$ meteor
[[[[[ c:\dev\my-project\src ]]]]]

=> Started proxy.

C:\Users\Stephan\AppData\Local\.meteor\packages\coffeescript\1.0.15-rc.10\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: sourcePath outside sourceRoot: ../../../../dev/my-project/src/project-tap.i18n
    at ImportScanner._ensureSourcePath (C:\tools\isobuild\import-scanner.js:262:17)
    at C:\tools\isobuild\import-scanner.js:120:28
    at Array.forEach (native)
    at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:119:11)
    at C:\tools\isobuild\compiler-plugin.js:756:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:726:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:910:8)
    at C:\tools\isobuild\bundler.js:677:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:668:18)
    at C:\tools\isobuild\bundler.js:2509:14
    at C:\tools\isobuild\bundler.js:2599:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Stephan\AppData\Local\.meteor\packages\meteor-tool\1.2.5-rc.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2598:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2490:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12
```

I don't think it is related, but the stacktrace is incorrect as well. `C:\tools` doesn't exists. That should be `C:\Users\Stephan\AppData\Local\.meteor\packages\meteor-tool\1.2.5-rc.10\mt-os.windows.x86_32\tools` instead.

**Comment by kamilkisiela** [comment]
Yeah, I ran into it yesterday using `tutorial-viewer` with latest meteor (`release-1.3` branch).

**Comment by smeijer** [comment]
Removing TAP:i18n from the project fixes the problem for now. So `1.3-rc.10` is "working" for me, although having a working internationalization package is a real requirement. So I guess it's working, but not usable.

**Comment by oliverlloyd** [comment]
We've been seeing the same error since around beta16 (using OSX). rc10 gives the same.

    Error: sourcePath outside sourceRoot: ../../../../../../../packages/kadira_dochead.js at ImportScanner._ensureSourcePath (/Users/oliver/.meteor/packages/meteor-tool/.1.2.5-rc.10.114baz7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:280:17

Removing `kadira:stripe-konnect` (which depends on `kadira:dochead`) prevents it happening.

**Comment by benjamn** [comment]
Should be fixed in [`1.3-rc.11`](https://github.com/meteor/meteor/issues/6266#issuecomment-201058454).

**Comment by oliverlloyd** [comment]
I'm still seeing this error with `rc.11` using `kadira:stripe-konnect`.

Might be worth noting that although the error message we see references `kadira_dochead.js` adding the package `kadira:dochead` directly doesn't cause the error, only with `kadira:stripe-konnect`.

```
$ meteor create sourceroot_error
$ cd sourceroot_error
$ meteor add kadira:stripe-konnect
$ meteor update --release 1.3-rc.11
$ meteor
/Users/oliver/.meteor/packages/templating/.1.1.7-rc.11.cddmrb++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: sourcePath outside sourceRoot: ../../../../../../../packages/kadira_dochead.js
    at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:262:17)
...
```
