### ISSUE TITLE
meteor npm shrinkwrap not working

### ISSUE THREAD

**Issue by nerdmed** [meteor/meteor#6746]
Dear Team, i am having some trouble using the shrinkwrap command - i am using it with the meteor prefix.

```
meteor npm shrinkwrap
```

I am on Meteor 1.3.1 and have this issue on completely fresh meteor projects, wihtout any modification.

The error i get in the console is the following:

```
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/USERNAME/.meteor/packages/meteor-tool/.1.3.1.1i35ljv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "shrinkwrap"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: balanced-match@0.3.0 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/balanced-match
npm ERR! extraneous: brace-expansion@1.1.3 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/brace-expansion
npm ERR! extraneous: concat-map@0.0.1 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/concat-map
npm ERR! extraneous: glob@7.0.0 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/glob
npm ERR! extraneous: inflight@1.0.4 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/inflight
npm ERR! extraneous: minimatch@3.0.0 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/minimatch
npm ERR! extraneous: once@1.3.3 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/once
npm ERR! extraneous: path-is-absolute@1.0.0 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/path-is-absolute
npm ERR! extraneous: wrappy@1.0.1 /Users/USERNAME/test-app-1.3/node_modules/meteor-node-stubs/node_modules/wrappy
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

I assume it to be an issue with the meteor-node-stubs npm package.
I get similar error when addind meteor-node-stubs to an empty npm project.
Before adding meteor-node-stubs, shrinkwraps are created without any problems.

Here is the log from an empty npm project.

```
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "~/.meteor/packages/meteor-tool/.1.3.1.1i35ljv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "shrinkwrap"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: meteor-node-stubs@0.2.1 /Users/USERNAME/empty-npm/npmtest/node_modules/meteor-node-stubs
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/USERNAME/empty-npm/npmtest/npm-debug.log
```

Same happens with the global npm binary.

**Comment by benjamn** [comment]
Fixed by https://github.com/meteor/node-stubs/commit/899d3b8a40c6db229cc4d214e92a5127e3f93509. Try `meteor npm install meteor-node-stubs@0.2.3` now?

**Comment by nerdmed** [comment]
@benjamn - yes great version 0.2.3 fixes the issue!

**Comment by jancurn** [comment]
Hey guys, I have the same problem again in Meteor 1.4.4.3. Basically running `meteor npm shrinkwrap` produces a number of `npm ERR! extraneous: balanced-match@0.4.2 .../web/node_modules/meteor-node-stubs/node_modules/balanced-match` errors. This used to work before, but now for some reason it doesn't (we added new NPM packages). I tried `meteor npm prune` and `meteor npm cache clean`, but it doesn't help.

Here's the output of the commands I'm using in our Meteor directory:

```
jan:web$ meteor node -v
v4.8.3
jan:web$ meteor npm -v
4.5.0
jan:web$ meteor npm install --no-optional
npm WARN deprecated mimelib@0.2.14: This module is deprecated

> bcrypt@1.0.2 install /Users/jan/Projects/Apifier/src/web/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.3 (node-v46 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  COPY /Users/jan/Projects/Apifier/src/web/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp

> bufferutil@3.0.1 install /Users/jan/Projects/Apifier/src/web/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.2
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/jan/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/jan/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/jan/Projects/Apifier/src/web/node_modules/bufferutil/build/Release/bufferutil.node
prebuild-install info unpack required /Users/jan/Projects/Apifier/src/web/node_modules/bufferutil/build/Release/bufferutil.node successfully
prebuild-install info install Prebuild successfully installed!
apifier-web@1.0.0 /Users/jan/Projects/Apifier/src/web
├─┬ apifier-commons@1.1.0 
│ ├── bluebird@3.5.0  deduped
│ ├── bson@1.0.4 
│ ├─┬ emailjs@1.0.9 
│ │ ├── addressparser@0.3.2 
│ │ ├─┬ mimelib@0.2.14 
│ │ │ ├── addressparser@0.2.1 
│ │ │ └─┬ encoding@0.1.12 
│ │ │   └── iconv-lite@0.4.18 
│ │ ├── moment@2.11.2  deduped
│ │ └── starttls@1.0.1 
│ ├─┬ js2xmlparser@3.0.0 
│ │ └── xmlcreate@1.0.2 
│ ├─┬ request@2.81.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├── aws4@1.6.0 
│ │ ├── caseless@0.12.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── extend@3.0.1 
│ │ ├── forever-agent@0.6.1 
│ │ ├─┬ form-data@2.1.4 
│ │ │ ├── asynckit@0.4.0 
│ │ │ ├── combined-stream@1.0.5  deduped
│ │ │ └── mime-types@2.1.15  deduped
│ │ ├─┬ har-validator@4.2.1 
│ │ │ ├── ajv@4.11.8  deduped
│ │ │ └── har-schema@1.0.5 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├─┬ boom@2.10.1 
│ │ │ │ └── hoek@2.16.3  deduped
│ │ │ ├─┬ cryptiles@2.0.5 
│ │ │ │ └── boom@2.10.1  deduped
│ │ │ ├── hoek@2.16.3 
│ │ │ └─┬ sntp@1.0.9 
│ │ │   └── hoek@2.16.3  deduped
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.4.0 
│ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ └─┬ verror@1.3.6 
│ │ │ │   └── extsprintf@1.0.2  deduped
│ │ │ └─┬ sshpk@1.13.1 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├── assert-plus@1.0.0 
│ │ │   ├─┬ dashdash@1.14.1 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   └─┬ getpass@0.1.7 
│ │ │     └── assert-plus@1.0.0 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.15 
│ │ │ └── mime-db@1.27.0 
│ │ ├── oauth-sign@0.8.2 
│ │ ├── performance-now@0.2.0 
│ │ ├── qs@6.4.0 
│ │ ├── safe-buffer@5.1.0 
│ │ ├── stringstream@0.0.5 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├─┬ tunnel-agent@0.6.0 
│ │ │ └── safe-buffer@5.1.0  deduped
│ │ └── uuid@3.0.1  deduped
│ ├── underscore@1.8.3  deduped
│ └─┬ worker-farm@1.3.1 
│   ├─┬ errno@0.1.4 
│   │ └── prr@0.0.0 
│   └── xtend@4.0.1 
├─┬ apifier-storage@1.0.0 
│ ├── apifier-commons@1.1.0  deduped
│ ├── bluebird@3.5.0  deduped
│ └── underscore@1.8.3  deduped
├─┬ async@2.4.1 
│ └── lodash@4.17.4 
├─┬ aws-sdk@2.69.0 
│ ├─┬ buffer@5.0.6 
│ │ ├── base64-js@1.2.0 
│ │ └── ieee754@1.1.8 
│ ├── crypto-browserify@1.0.9 
│ ├── jmespath@0.15.0 
│ ├── querystring@0.2.0 
│ ├── sax@1.2.1 
│ ├─┬ url@0.10.3 
│ │ ├── punycode@1.3.2 
│ │ └── querystring@0.2.0  deduped
│ ├── uuid@3.0.1 
│ ├─┬ xml2js@0.4.17 
│ │ ├── sax@1.2.1  deduped
│ │ └── xmlbuilder@4.2.1  deduped
│ └─┬ xmlbuilder@4.2.1 
│   └── lodash@4.17.4  deduped
├─┬ babel-runtime@6.23.0 
│ ├── core-js@2.4.1 
│ └── regenerator-runtime@0.10.5 
├─┬ bcrypt@1.0.2 
│ ├── bindings@1.2.1 
│ ├── nan@2.5.0 
│ └─┬ node-pre-gyp@0.6.32 
│   ├── mkdirp@0.5.1  deduped
│   ├─┬ nopt@3.0.6 
│   │ └── abbrev@1.1.0 
│   ├─┬ npmlog@4.1.0 
│   │ ├─┬ are-we-there-yet@1.1.4 
│   │ │ ├── delegates@1.0.0 
│   │ │ └── readable-stream@2.2.11  deduped
│   │ ├── console-control-strings@1.1.0 
│   │ ├─┬ gauge@2.7.4 
│   │ │ ├── aproba@1.1.2 
│   │ │ ├── console-control-strings@1.1.0  deduped
│   │ │ ├── has-unicode@2.0.1 
│   │ │ ├── object-assign@4.1.1  deduped
│   │ │ ├── signal-exit@3.0.2 
│   │ │ ├── string-width@1.0.2  deduped
│   │ │ ├── strip-ansi@3.0.1  deduped
│   │ │ └─┬ wide-align@1.1.2 
│   │ │   └── string-width@1.0.2  deduped
│   │ └── set-blocking@2.0.0 
│   ├─┬ rc@1.1.7 
│   │ ├── deep-extend@0.4.2 
│   │ ├── ini@1.3.4 
│   │ ├── minimist@1.2.0 
│   │ └── strip-json-comments@2.0.1  deduped
│   ├── request@2.81.0  deduped
│   ├─┬ rimraf@2.5.4 
│   │ └── glob@7.1.2  deduped
│   ├── semver@5.3.0 
│   ├─┬ tar@2.2.1 
│   │ ├─┬ block-stream@0.0.9 
│   │ │ └── inherits@2.0.3  deduped
│   │ ├─┬ fstream@1.0.11 
│   │ │ ├── graceful-fs@4.1.11  deduped
│   │ │ ├── inherits@2.0.3  deduped
│   │ │ ├── mkdirp@0.5.1  deduped
│   │ │ └── rimraf@2.5.4  deduped
│   │ └── inherits@2.0.3  deduped
│   └─┬ tar-pack@3.3.0 
│     ├── debug@2.2.0  deduped
│     ├── fstream@1.0.11  deduped
│     ├─┬ fstream-ignore@1.0.5 
│     │ ├── fstream@1.0.11  deduped
│     │ ├── inherits@2.0.3  deduped
│     │ └── minimatch@3.0.4  deduped
│     ├─┬ once@1.3.3 
│     │ └── wrappy@1.0.2  deduped
│     ├─┬ readable-stream@2.1.5 
│     │ ├── buffer-shims@1.0.0 
│     │ ├── core-util-is@1.0.2  deduped
│     │ ├── inherits@2.0.3  deduped
│     │ ├── isarray@1.0.0  deduped
│     │ ├── process-nextick-args@1.0.7  deduped
│     │ ├── string_decoder@0.10.31 
│     │ └── util-deprecate@1.0.2  deduped
│     ├── rimraf@2.5.4  deduped
│     ├── tar@2.2.1  deduped
│     └── uid-number@0.0.6 
├── bluebird@3.5.0 
├─┬ braintree@2.1.1 
│ ├── dateformat@1.0.1-1.2.3 
│ ├── depd@1.1.0 
│ ├─┬ readable-stream@1.1.10 
│ │ ├── core-util-is@1.0.2 
│ │ └── string_decoder@0.10.31 
│ ├── semver@5.1.0 
│ ├── underscore@1.8.3  deduped
│ ├── wrap-promise@1.1.0  (git://github.com/braintree/wrap-promise.git#daa66452aa0d6fe9559be68e34e880ec52e8bf1f)
│ └─┬ xml2js@0.1.13 
│   └── sax@1.2.1  deduped
├─┬ bufferutil@3.0.1 
│ ├── bindings@1.2.1  deduped
│ ├── nan@2.6.2 
│ └─┬ prebuild-install@2.1.2 
│   ├── expand-template@1.0.3 
│   ├── github-from-package@0.0.0 
│   ├── minimist@1.2.0 
│   ├── mkdirp@0.5.1  deduped
│   ├── node-abi@2.0.3 
│   ├── noop-logger@0.1.1 
│   ├── npmlog@4.1.0  deduped
│   ├── os-homedir@1.0.2 
│   ├─┬ pump@1.0.2 
│   │ ├─┬ end-of-stream@1.4.0 
│   │ │ └── once@1.4.0  deduped
│   │ └── once@1.4.0  deduped
│   ├── rc@1.1.7  deduped
│   ├─┬ simple-get@1.4.3 
│   │ ├── once@1.4.0  deduped
│   │ ├── unzip-response@1.0.2 
│   │ └── xtend@4.0.1  deduped
│   ├─┬ tar-fs@1.15.3 
│   │ ├── chownr@1.0.1 
│   │ ├── mkdirp@0.5.1  deduped
│   │ ├── pump@1.0.2  deduped
│   │ └─┬ tar-stream@1.5.4 
│   │   ├─┬ bl@1.2.1 
│   │   │ └── readable-stream@2.2.11  deduped
│   │   ├── end-of-stream@1.4.0  deduped
│   │   ├── readable-stream@2.2.11  deduped
│   │   └── xtend@4.0.1  deduped
│   ├── tunnel-agent@0.4.3 
│   └── xtend@4.0.1  deduped
├─┬ chart.js@2.6.0 
│ ├─┬ chartjs-color@2.1.0 
│ │ ├─┬ chartjs-color-string@0.4.0 
│ │ │ └── color-name@1.1.2 
│ │ └── color-convert@0.5.3 
│ └── moment@2.11.2 
├── countries-list@1.4.1 
├─┬ cron-parser@2.4.0 
│ ├─┬ is-nan@1.2.1 
│ │ └─┬ define-properties@1.1.2 
│ │   ├── foreach@2.0.5 
│ │   └── object-keys@1.0.11 
│ └─┬ moment-timezone@0.5.13 
│   └── moment@2.11.2  deduped
├── discourse-sso@1.0.3 
├─┬ eslint@3.19.0 
│ ├─┬ babel-code-frame@6.22.0 
│ │ ├── chalk@1.1.3  deduped
│ │ ├── esutils@2.0.2  deduped
│ │ └── js-tokens@3.0.1 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1  deduped
│ │ ├─┬ strip-ansi@3.0.1 
│ │ │ └── ansi-regex@2.1.1  deduped
│ │ └── supports-color@2.0.0 
│ ├─┬ concat-stream@1.6.0 
│ │ ├── inherits@2.0.3 
│ │ ├─┬ readable-stream@2.2.11 
│ │ │ ├── core-util-is@1.0.2  deduped
│ │ │ ├── inherits@2.0.3  deduped
│ │ │ ├── isarray@1.0.0  deduped
│ │ │ ├── process-nextick-args@1.0.7 
│ │ │ ├── safe-buffer@5.0.1 
│ │ │ ├─┬ string_decoder@1.0.2 
│ │ │ │ └── safe-buffer@5.0.1 
│ │ │ └── util-deprecate@1.0.2 
│ │ └── typedarray@0.0.6 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├─┬ doctrine@2.0.0 
│ │ ├── esutils@2.0.2  deduped
│ │ └── isarray@1.0.0 
│ ├─┬ escope@3.6.0 
│ │ ├─┬ es6-map@0.1.5 
│ │ │ ├─┬ d@1.0.0 
│ │ │ │ └── es5-ext@0.10.23  deduped
│ │ │ ├─┬ es5-ext@0.10.23 
│ │ │ │ ├── es6-iterator@2.0.1  deduped
│ │ │ │ └── es6-symbol@3.1.1  deduped
│ │ │ ├─┬ es6-iterator@2.0.1 
│ │ │ │ ├── d@1.0.0  deduped
│ │ │ │ ├── es5-ext@0.10.23  deduped
│ │ │ │ └── es6-symbol@3.1.1  deduped
│ │ │ ├─┬ es6-set@0.1.5 
│ │ │ │ ├── d@1.0.0  deduped
│ │ │ │ ├── es5-ext@0.10.23  deduped
│ │ │ │ ├── es6-iterator@2.0.1  deduped
│ │ │ │ ├── es6-symbol@3.1.1  deduped
│ │ │ │ └── event-emitter@0.3.5  deduped
│ │ │ ├─┬ es6-symbol@3.1.1 
│ │ │ │ ├── d@1.0.0  deduped
│ │ │ │ └── es5-ext@0.10.23  deduped
│ │ │ └─┬ event-emitter@0.3.5 
│ │ │   ├── d@1.0.0  deduped
│ │ │   └── es5-ext@0.10.23  deduped
│ │ ├─┬ es6-weak-map@2.0.2 
│ │ │ ├── d@1.0.0  deduped
│ │ │ ├── es5-ext@0.10.23  deduped
│ │ │ ├── es6-iterator@2.0.1  deduped
│ │ │ └── es6-symbol@3.1.1  deduped
│ │ ├─┬ esrecurse@4.1.0 
│ │ │ ├── estraverse@4.1.1 
│ │ │ └── object-assign@4.1.1  deduped
│ │ └── estraverse@4.2.0  deduped
│ ├─┬ espree@3.4.3 
│ │ ├── acorn@5.0.3 
│ │ └─┬ acorn-jsx@3.0.1 
│ │   └── acorn@3.3.0 
│ ├─┬ esquery@1.0.0 
│ │ └── estraverse@4.2.0  deduped
│ ├── estraverse@4.2.0 
│ ├── esutils@2.0.2 
│ ├─┬ file-entry-cache@2.0.0 
│ │ ├─┬ flat-cache@1.2.2 
│ │ │ ├── circular-json@0.3.1 
│ │ │ ├─┬ del@2.2.2 
│ │ │ │ ├─┬ globby@5.0.0 
│ │ │ │ │ ├─┬ array-union@1.0.2 
│ │ │ │ │ │ └── array-uniq@1.0.3 
│ │ │ │ │ ├── arrify@1.0.1 
│ │ │ │ │ ├── glob@7.1.2  deduped
│ │ │ │ │ ├── object-assign@4.1.1  deduped
│ │ │ │ │ ├── pify@2.3.0  deduped
│ │ │ │ │ └── pinkie-promise@2.0.1  deduped
│ │ │ │ ├── is-path-cwd@1.0.0 
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0 
│ │ │ │ │ └─┬ is-path-inside@1.0.0 
│ │ │ │ │   └── path-is-inside@1.0.2  deduped
│ │ │ │ ├── object-assign@4.1.1  deduped
│ │ │ │ ├── pify@2.3.0 
│ │ │ │ ├─┬ pinkie-promise@2.0.1 
│ │ │ │ │ └── pinkie@2.0.4 
│ │ │ │ └── rimraf@2.5.4  deduped
│ │ │ ├── graceful-fs@4.1.11 
│ │ │ └─┬ write@0.2.1 
│ │ │   └── mkdirp@0.5.1  deduped
│ │ └── object-assign@4.1.1 
│ ├─┬ glob@7.1.2 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ ├── once@1.4.0  deduped
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.3  deduped
│ │ ├── minimatch@3.0.4  deduped
│ │ ├─┬ once@1.4.0 
│ │ │ └── wrappy@1.0.2  deduped
│ │ └── path-is-absolute@1.0.1 
│ ├── globals@9.18.0 
│ ├── ignore@3.3.3 
│ ├── imurmurhash@0.1.4 
│ ├─┬ inquirer@0.12.0 
│ │ ├── ansi-escapes@1.4.0 
│ │ ├── ansi-regex@2.1.1 
│ │ ├── chalk@1.1.3  deduped
│ │ ├─┬ cli-cursor@1.0.2 
│ │ │ └─┬ restore-cursor@1.0.1 
│ │ │   ├── exit-hook@1.1.1 
│ │ │   └── onetime@1.1.0 
│ │ ├── cli-width@2.1.0 
│ │ ├─┬ figures@1.7.0 
│ │ │ ├── escape-string-regexp@1.0.5  deduped
│ │ │ └── object-assign@4.1.1  deduped
│ │ ├── lodash@4.17.4  deduped
│ │ ├─┬ readline2@1.0.1 
│ │ │ ├── code-point-at@1.1.0 
│ │ │ ├─┬ is-fullwidth-code-point@1.0.0 
│ │ │ │ └── number-is-nan@1.0.1 
│ │ │ └── mute-stream@0.0.5 
│ │ ├─┬ run-async@0.1.0 
│ │ │ └── once@1.4.0  deduped
│ │ ├── rx-lite@3.1.2 
│ │ ├─┬ string-width@1.0.2 
│ │ │ ├── code-point-at@1.1.0  deduped
│ │ │ ├── is-fullwidth-code-point@1.0.0  deduped
│ │ │ └── strip-ansi@3.0.1  deduped
│ │ ├── strip-ansi@3.0.1  deduped
│ │ └── through@2.3.8 
│ ├─┬ is-my-json-valid@2.16.0 
│ │ ├── generate-function@2.0.0 
│ │ ├─┬ generate-object-property@1.2.0 
│ │ │ └── is-property@1.0.2 
│ │ ├── jsonpointer@4.0.1 
│ │ └── xtend@4.0.1  deduped
│ ├─┬ is-resolvable@1.0.0 
│ │ └── tryit@1.0.3 
│ ├─┬ js-yaml@3.8.4 
│ │ ├─┬ argparse@1.0.9 
│ │ │ └── sprintf-js@1.0.3 
│ │ └── esprima@3.1.3 
│ ├─┬ json-stable-stringify@1.0.1 
│ │ └── jsonify@0.0.0 
│ ├─┬ levn@0.3.0 
│ │ ├── prelude-ls@1.1.2 
│ │ └─┬ type-check@0.3.2 
│ │   └── prelude-ls@1.1.2  deduped
│ ├── lodash@4.17.4  deduped
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├── natural-compare@1.4.0 
│ ├─┬ optionator@0.8.2 
│ │ ├── deep-is@0.1.3 
│ │ ├── fast-levenshtein@2.0.6 
│ │ ├── levn@0.3.0  deduped
│ │ ├── prelude-ls@1.1.2  deduped
│ │ ├── type-check@0.3.2  deduped
│ │ └── wordwrap@1.0.0 
│ ├── path-is-inside@1.0.2 
│ ├── pluralize@1.2.1 
│ ├── progress@1.1.8 
│ ├─┬ require-uncached@1.0.3 
│ │ ├─┬ caller-path@0.1.0 
│ │ │ └── callsites@0.2.0 
│ │ └── resolve-from@1.0.1 
│ ├─┬ shelljs@0.7.8 
│ │ ├── glob@7.1.2  deduped
│ │ ├── interpret@1.0.3 
│ │ └─┬ rechoir@0.6.2 
│ │   └── resolve@1.3.3  deduped
│ ├── strip-bom@3.0.0 
│ ├── strip-json-comments@2.0.1 
│ ├─┬ table@3.8.3 
│ │ ├─┬ ajv@4.11.8 
│ │ │ ├── co@4.6.0 
│ │ │ └── json-stable-stringify@1.0.1  deduped
│ │ ├── ajv-keywords@1.5.1 
│ │ ├── chalk@1.1.3  deduped
│ │ ├── lodash@4.17.4  deduped
│ │ ├── slice-ansi@0.0.4 
│ │ └─┬ string-width@2.0.0 
│ │   ├── is-fullwidth-code-point@2.0.0 
│ │   └── strip-ansi@3.0.1  deduped
│ ├── text-table@0.2.0 
│ └─┬ user-home@2.0.0 
│   └── os-homedir@1.0.2  deduped
├─┬ eslint-config-airbnb@15.0.1 
│ └── eslint-config-airbnb-base@11.2.0  deduped
├── eslint-config-airbnb-base@11.2.0 
├─┬ eslint-plugin-import@2.3.0 
│ ├── builtin-modules@1.1.1 
│ ├── contains-path@0.1.0 
│ ├── debug@2.2.0  deduped
│ ├─┬ doctrine@1.5.0 
│ │ ├── esutils@2.0.2  deduped
│ │ └── isarray@1.0.0  deduped
│ ├─┬ eslint-import-resolver-node@0.2.3 
│ │ ├── debug@2.2.0  deduped
│ │ ├── object-assign@4.1.1  deduped
│ │ └─┬ resolve@1.3.3 
│ │   └── path-parse@1.0.5 
│ ├─┬ eslint-module-utils@2.0.0 
│ │ ├── debug@2.2.0  deduped
│ │ └─┬ pkg-dir@1.0.0 
│ │   └─┬ find-up@1.1.2 
│ │     ├─┬ path-exists@2.1.0 
│ │     │ └── pinkie-promise@2.0.1  deduped
│ │     └── pinkie-promise@2.0.1  deduped
│ ├─┬ has@1.0.1 
│ │ └── function-bind@1.1.0 
│ ├── lodash.cond@4.5.2 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.8 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ └─┬ read-pkg-up@2.0.0 
│   ├─┬ find-up@2.1.0 
│   │ └─┬ locate-path@2.0.0 
│   │   ├─┬ p-locate@2.0.0 
│   │   │ └── p-limit@1.1.0 
│   │   └── path-exists@3.0.0 
│   └─┬ read-pkg@2.0.0 
│     ├─┬ load-json-file@2.0.0 
│     │ ├── graceful-fs@4.1.11  deduped
│     │ ├─┬ parse-json@2.2.0 
│     │ │ └─┬ error-ex@1.3.1 
│     │ │   └── is-arrayish@0.2.1 
│     │ ├── pify@2.3.0  deduped
│     │ └── strip-bom@3.0.0  deduped
│     ├─┬ normalize-package-data@2.3.8 
│     │ ├── hosted-git-info@2.4.2 
│     │ ├─┬ is-builtin-module@1.0.0 
│     │ │ └── builtin-modules@1.1.1  deduped
│     │ ├── semver@5.3.0  deduped
│     │ └─┬ validate-npm-package-license@3.0.1 
│     │   ├─┬ spdx-correct@1.0.2 
│     │   │ └── spdx-license-ids@1.2.2 
│     │   └── spdx-expression-parse@1.0.4 
│     └─┬ path-type@2.0.0 
│       └── pify@2.3.0  deduped
├─┬ eslint-plugin-jsx-a11y@5.0.3 
│ ├─┬ aria-query@0.5.0 
│ │ └── ast-types-flow@0.0.7  deduped
│ ├─┬ array-includes@3.0.3 
│ │ ├── define-properties@1.1.2  deduped
│ │ └─┬ es-abstract@1.7.0 
│ │   ├─┬ es-to-primitive@1.1.1 
│ │   │ ├── is-callable@1.1.3  deduped
│ │   │ ├── is-date-object@1.0.1 
│ │   │ └── is-symbol@1.0.1 
│ │   ├── function-bind@1.1.0  deduped
│ │   ├── is-callable@1.1.3 
│ │   └─┬ is-regex@1.0.4 
│ │     └── has@1.0.1  deduped
│ ├── ast-types-flow@0.0.7 
│ ├─┬ axobject-query@0.1.0 
│ │ └── ast-types-flow@0.0.7  deduped
│ ├── damerau-levenshtein@1.0.4 
│ ├── emoji-regex@6.4.2 
│ └── jsx-ast-utils@1.4.1 
├── eslint-plugin-promise@3.5.0 
├─┬ eslint-plugin-react@7.1.0 
│ ├── doctrine@2.0.0  deduped
│ ├── has@1.0.1  deduped
│ └── jsx-ast-utils@1.4.1  deduped
├── html-pdf@2.1.0 
├─┬ meteor-node-stubs@0.2.11 
│ ├─┬ asn1.js@4.9.0 
│ │ ├── bn.js@4.11.6  deduped
│ │ ├── inherits@2.0.1  deduped
│ │ └── minimalistic-assert@1.0.0  deduped
│ ├─┬ assert@1.4.1 
│ │ └── util@0.10.3  deduped
│ ├── balanced-match@0.4.2 
│ ├── Base64@0.2.1 
│ ├── base64-js@1.2.0 
│ ├── bn.js@4.11.6 
│ ├─┬ brace-expansion@1.1.7 
│ │ ├── balanced-match@0.4.2  deduped
│ │ └── concat-map@0.0.1  deduped
│ ├── brorand@1.0.6 
│ ├─┬ browserify-aes@1.0.6 
│ │ ├── buffer-xor@1.0.3  deduped
│ │ ├── cipher-base@1.0.3  deduped
│ │ ├── create-hash@1.1.2  deduped
│ │ ├── evp_bytestokey@1.0.0  deduped
│ │ └── inherits@2.0.1  deduped
│ ├─┬ browserify-cipher@1.0.0 
│ │ ├── browserify-aes@1.0.6  deduped
│ │ ├── browserify-des@1.0.0  deduped
│ │ └── evp_bytestokey@1.0.0  deduped
│ ├─┬ browserify-des@1.0.0 
│ │ ├── cipher-base@1.0.3  deduped
│ │ ├── des.js@1.0.0  deduped
│ │ └── inherits@2.0.1  deduped
│ ├─┬ browserify-rsa@4.0.1 
│ │ ├── bn.js@4.11.6  deduped
│ │ └── randombytes@2.0.3  deduped
│ ├─┬ browserify-sign@4.0.0 
│ │ ├── bn.js@4.11.6  deduped
│ │ ├── browserify-rsa@4.0.1  deduped
│ │ ├── create-hash@1.1.2  deduped
│ │ ├── create-hmac@1.1.4  deduped
│ │ ├── elliptic@6.3.2  deduped
│ │ ├── inherits@2.0.1  deduped
│ │ └── parse-asn1@5.0.0  deduped
│ ├─┬ browserify-zlib@0.1.4 
│ │ └── pako@0.2.9  deduped
│ ├─┬ buffer@4.9.1 
│ │ ├── base64-js@1.2.0  deduped
│ │ ├── ieee754@1.1.8  deduped
│ │ └── isarray@1.0.0  deduped
│ ├── buffer-xor@1.0.3 
│ ├─┬ cipher-base@1.0.3 
│ │ └── inherits@2.0.1  deduped
│ ├── concat-map@0.0.1 
│ ├─┬ console-browserify@1.1.0 
│ │ └── date-now@0.1.4  deduped
│ ├── constants-browserify@1.0.0 
│ ├─┬ create-ecdh@4.0.0 
│ │ ├── bn.js@4.11.6  deduped
│ │ └── elliptic@6.3.2  deduped
│ ├─┬ create-hash@1.1.2 
│ │ ├── cipher-base@1.0.3  deduped
│ │ ├── inherits@2.0.1  deduped
│ │ ├── ripemd160@1.0.1  deduped
│ │ └── sha.js@2.4.8  deduped
│ ├─┬ create-hmac@1.1.4 
│ │ ├── create-hash@1.1.2  deduped
│ │ └── inherits@2.0.1  deduped
│ ├─┬ crypto-browserify@3.11.0 
│ │ ├── browserify-cipher@1.0.0  deduped
│ │ ├── browserify-sign@4.0.0  deduped
│ │ ├── create-ecdh@4.0.0  deduped
│ │ ├── create-hash@1.1.2  deduped
│ │ ├── create-hmac@1.1.4  deduped
│ │ ├── diffie-hellman@5.0.2  deduped
│ │ ├── inherits@2.0.1  deduped
│ │ ├── pbkdf2@3.0.9  deduped
│ │ ├── public-encrypt@4.0.0  deduped
│ │ └── randombytes@2.0.3  deduped
│ ├── date-now@0.1.4 
│ ├─┬ des.js@1.0.0 
│ │ ├── inherits@2.0.1  deduped
│ │ └── minimalistic-assert@1.0.0  deduped
│ ├─┬ diffie-hellman@5.0.2 
│ │ ├── bn.js@4.11.6  deduped
│ │ ├── miller-rabin@4.0.0  deduped
│ │ └── randombytes@2.0.3  deduped
│ ├── domain-browser@1.1.7 
│ ├─┬ elliptic@6.3.2 
│ │ ├── bn.js@4.11.6  deduped
│ │ ├── brorand@1.0.6  deduped
│ │ ├── hash.js@1.0.3  deduped
│ │ └── inherits@2.0.1  deduped
│ ├── events@1.1.1 
│ ├─┬ evp_bytestokey@1.0.0 
│ │ └── create-hash@1.1.2  deduped
│ ├── fs.realpath@1.0.0 
│ ├─┬ glob@7.1.2 
│ │ ├── fs.realpath@1.0.0  deduped
│ │ ├── inflight@1.0.6  deduped
│ │ ├── inherits@2.0.1  deduped
│ │ ├── minimatch@3.0.4  deduped
│ │ ├── once@1.4.0  deduped
│ │ └── path-is-absolute@1.0.1  deduped
│ ├─┬ hash.js@1.0.3 
│ │ └── inherits@2.0.1  deduped
│ ├─┬ http-browserify@1.7.0 
│ │ ├── Base64@0.2.1  deduped
│ │ └── inherits@2.0.1  deduped
│ ├── https-browserify@0.0.1 
│ ├── ieee754@1.1.8 
│ ├── indexof@0.0.1 
│ ├─┬ inflight@1.0.6 
│ │ ├── once@1.4.0  deduped
│ │ └── wrappy@1.0.2  deduped
│ ├── inherits@2.0.1 
│ ├── isarray@1.0.0 
│ ├─┬ miller-rabin@4.0.0 
│ │ ├── bn.js@4.11.6  deduped
│ │ └── brorand@1.0.6  deduped
│ ├── minimalistic-assert@1.0.0 
│ ├─┬ minimatch@3.0.4 
│ │ └── brace-expansion@1.1.7  deduped
│ ├─┬ once@1.4.0 
│ │ └── wrappy@1.0.2  deduped
│ ├── os-browserify@0.2.1 
│ ├── pako@0.2.9 
│ ├─┬ parse-asn1@5.0.0 
│ │ ├── asn1.js@4.9.0  deduped
│ │ ├── browserify-aes@1.0.6  deduped
│ │ ├── create-hash@1.1.2  deduped
│ │ ├── evp_bytestokey@1.0.0  deduped
│ │ └── pbkdf2@3.0.9  deduped
│ ├── path-browserify@0.0.0 
│ ├── path-is-absolute@1.0.1 
│ ├─┬ pbkdf2@3.0.9 
│ │ └── create-hmac@1.1.4  deduped
│ ├── process@0.11.9 
│ ├── process-nextick-args@1.0.7 
│ ├─┬ public-encrypt@4.0.0 
│ │ ├── bn.js@4.11.6  deduped
│ │ ├── browserify-rsa@4.0.1  deduped
│ │ ├── create-hash@1.1.2  deduped
│ │ ├── parse-asn1@5.0.0  deduped
│ │ └── randombytes@2.0.3  deduped
│ ├── punycode@1.4.1 
│ ├── querystring@0.2.0 
│ ├── querystring-es3@0.2.1 
│ ├── randombytes@2.0.3 
│ ├─┬ readable-stream@2.2.10  (git+https://github.com/meteor/readable-stream.git#2e9112d7d31a2af6e0682db0e18679b1e5fd4694)
│ │ ├── inherits@2.0.1  deduped
│ │ ├── isarray@1.0.0  deduped
│ │ ├── process-nextick-args@1.0.7  deduped
│ │ ├── safe-buffer@5.0.1  deduped
│ │ ├── string_decoder@1.0.1  deduped
│ │ └── util-deprecate@1.0.2  deduped
│ ├── rimraf@2.6.1  extraneous
│ ├── ripemd160@1.0.1 
│ ├── safe-buffer@5.0.1 
│ ├─┬ sha.js@2.4.8 
│ │ └── inherits@2.0.1  deduped
│ ├─┬ stream-browserify@2.0.1 
│ │ ├── inherits@2.0.1  deduped
│ │ └── readable-stream@2.2.10  deduped (git+https://github.com/meteor/readable-stream.git#2e9112d7d31a2af6e0682db0e18679b1e5fd4694)
│ ├─┬ string_decoder@1.0.1 
│ │ └── safe-buffer@5.0.1  deduped
│ ├─┬ timers-browserify@1.4.2 
│ │ └── process@0.11.9  deduped
│ ├── tty-browserify@0.0.0 
│ ├─┬ url@0.11.0 
│ │ ├── punycode@1.3.2 
│ │ └── querystring@0.2.0  deduped
│ ├─┬ util@0.10.3 
│ │ └── inherits@2.0.1  deduped
│ ├── util-deprecate@1.0.2 
│ ├─┬ vm-browserify@0.0.4 
│ │ └── indexof@0.0.1  deduped
│ └── wrappy@1.0.2 
├─┬ newrelic@1.40.0 
│ ├─┬ concat-stream@1.6.0 
│ │ ├── inherits@2.0.3 
│ │ ├─┬ readable-stream@2.2.11 
│ │ │ ├── core-util-is@1.0.2 
│ │ │ ├── inherits@2.0.3  deduped
│ │ │ ├── isarray@1.0.0 
│ │ │ ├── process-nextick-args@1.0.7 
│ │ │ ├── safe-buffer@5.0.1 
│ │ │ ├─┬ string_decoder@1.0.2 
│ │ │ │ └── safe-buffer@5.0.1  deduped
│ │ │ └── util-deprecate@1.0.2 
│ │ └── typedarray@0.0.6 
│ ├─┬ https-proxy-agent@0.3.6 
│ │ ├── agent-base@1.0.2 
│ │ ├─┬ debug@2.6.8 
│ │ │ └── ms@2.0.0 
│ │ └── extend@3.0.1 
│ ├── json-stringify-safe@5.0.1 
│ ├─┬ readable-stream@1.1.14 
│ │ ├── core-util-is@1.0.2 
│ │ ├── inherits@2.0.3 
│ │ ├── isarray@0.0.1 
│ │ └── string_decoder@0.10.31 
│ └── semver@5.3.0 
├── screenfull@3.2.1 
├── slugg@1.2.1 
├── underscore@1.8.3 
└─┬ ws@2.3.1 
  ├── safe-buffer@5.0.1 
  └── ultron@1.1.0 

jan:web$ meteor npm shrinkwrap
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: balanced-match@0.4.2 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/balanced-match
npm ERR! extraneous: brace-expansion@1.1.7 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/brace-expansion
npm ERR! extraneous: concat-map@0.0.1 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/concat-map
npm ERR! extraneous: fs.realpath@1.0.0 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/fs.realpath
npm ERR! extraneous: glob@7.1.2 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/glob
npm ERR! extraneous: inflight@1.0.6 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/inflight
npm ERR! extraneous: minimatch@3.0.4 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/minimatch
npm ERR! extraneous: once@1.4.0 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/once
npm ERR! extraneous: path-is-absolute@1.0.1 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/path-is-absolute
npm ERR! extraneous: rimraf@2.6.1 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/rimraf
npm ERR! extraneous: wrappy@1.0.2 /Users/jan/Projects/Apifier/src/web/node_modules/meteor-node-stubs/node_modules/wrappy

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jan/.meteor/packages/meteor-tool/.1.4.4_3.1f3m9pn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-06-14T12_39_06_097Z-debug.log
jan:web$ 
```

**Comment by mhagmajer** [comment]
Same with Meteor 1.5 and `meteor-node-stubs` 0.2.11

```
$ meteor npm shrinkwrap
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: balanced-match@0.4.2 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/balanced-match
npm ERR! extraneous: brace-expansion@1.1.7 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/brace-expansion
npm ERR! extraneous: concat-map@0.0.1 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/concat-map
npm ERR! extraneous: fs.realpath@1.0.0 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/fs.realpath
npm ERR! extraneous: glob@7.1.2 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/glob
npm ERR! extraneous: inflight@1.0.6 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/inflight
npm ERR! extraneous: minimatch@3.0.4 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/minimatch
npm ERR! extraneous: once@1.4.0 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/once
npm ERR! extraneous: path-is-absolute@1.0.1 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/path-is-absolute
npm ERR! extraneous: rimraf@2.6.1 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/rimraf
npm ERR! extraneous: wrappy@1.0.2 /Users/marcin/Repositories/pks/node_modules/meteor-node-stubs/node_modules/wrappy
```

**Comment by nerdmed** [comment]
did you guys try to delete all node_modules with `rm -rf node_modules` and then `npm install` before writing your shrinkwrap?

**Comment by jancurn** [comment]
Yeah, that was the first thing I tried, still the error shows up. These are
the only errors I'm encountering.

**Comment by evolross** [comment]
+1. A work-around is to `meteor npm uninstall meteor-node-stubs` if your project allows it and remove it from your `package.json`.  Then `meteor npm shrinkwrap` works.

**Comment by nerdmed** [comment]
@benjamn this is really an issue right now, we can not deploy in our process without this being fixed. Nearly the same problem after upgrading to meteor 1.5.1 - not sure if it is connected, but how can this kind of issue be avoided? For me the issue looks similar to the others

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: balanced-match@0.4.2 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/balanced-match
npm ERR! extraneous: brace-expansion@1.1.7 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/brace-expansion
npm ERR! extraneous: concat-map@0.0.1 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/concat-map
npm ERR! extraneous: fs.realpath@1.0.0 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/fs.realpath
npm ERR! extraneous: glob@7.1.2 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/glob
npm ERR! extraneous: inflight@1.0.6 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/inflight
npm ERR! extraneous: minimatch@3.0.4 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/minimatch
npm ERR! extraneous: once@1.4.0 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/once
npm ERR! extraneous: path-is-absolute@1.0.1 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/path-is-absolute
npm ERR! extraneous: rimraf@2.6.1 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/rimraf
npm ERR! extraneous: wrappy@1.0.2 /Users/ahmedhassan/github/Projects/flowkey-app-2/node_modules/meteor-node-stubs/node_modules/wrappy
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ahmedhassan/github/Projects/flowkey-app-2/npm-debug.log
```

**Comment by jancurn** [comment]
As a workaround, we're installing the packages using this command:
```
npm install --no-optional --only=prod
```

**Comment by hwillson** [comment]
This issue should be fixed using any version of `meteor-node-stubs` >= 0.2.1. The problem outlined in https://github.com/meteor/meteor/issues/6746#issuecomment-317779477 (and the reason why this issue was re-opened) has since been resolved, so closing this off again. Thanks all!

**Comment by sirpy** [comment]
this should be reopened, it still happens on 1.5.2.2 with stubs 0.2.11

**Comment by mitar** [comment]
I can confirm. On a completely new app, with 1.5.2.2 and stubs 0.2.11, I get this extraneous error and cannot use `meteor npm shrinkwrap`.

**Comment by hwillson** [comment]
I just tried:

```
meteor create --bare --release 1.5.2.2 some-app
cd some-app
meteor npm shrinkwrap
```

and it worked properly for me. The app was using `meteor-node-stubs` 0.2.4, but I also tried bumping it to 0.2.11 and it still works. Just to verify, I also tried the same thing using Meteor 1.6 and `meteor-node-stubs` 0.3.2, and it works as well.

Can someone provide a small runnable reproduction showing this happen?

**Comment by mitar** [comment]
I think I found a reproduction steps which work consistently.

```
meteor create --bare test
cd test
rm -rf node_modules
meteor npm install
meteor npm shrinkwrap
```

So the issue is that instead of `rm -rf node_modules` what happens is that you might clone the repo and install packages.

**Comment by mitar** [comment]
(I would guess that `meteor npm install --no-optional --only=prod` would probably work and be a workaround, but the comment above is saying that it is not needed anymore.)

**Comment by mitar** [comment]
Hm, is maybe this deprecated? It seems with Meteor 1.6 there is now package-lock.json which serves the same purpose, no?

**Comment by hwillson** [comment]
@mitar Not quite - here's a breakdown of the differences: 
https://github.com/npm/npm/blob/latest/doc/spec/package-lock.md

I have been able to re-create the issue using your steps with Meteor 1.5.2.2 (npm 4), but not with Meteor 1.6 (npm 5). Looking at the `meteor-node-stubs` `npm-shrinkwrap.json`, there are packages listed there that aren't  defined as dependencies of `meteor-node-stubs`. This appears to be the cause of the extraneous errors. I'm not sure if this will be updated for Meteor 1.5.x given that the issue doesn't occur with 1.6 (and npm 5), but I'll look into it more thoroughly tomorrow. One more thing - it looks like there is already a issue for this over in the `meteor-node-stubs` repo: https://github.com/meteor/node-stubs/issues/8

**Comment by mitar** [comment]
Interesting:

> package-lock.json, which is ordinarily always present and is never published.

Because when I added a npm package, it said to me that I should add this file to the repo.

So confusing.

**Comment by hwillson** [comment]
I know, it's a bit confusing, but what they mean is that the `package-lock.json` should be committed alongside your source, for these reasons (taken from https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md): 

> * Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> * Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> * To facilitate greater visibility of tree changes through readable source control diffs.
> * And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

The `package-lock.json` can't be published though, which is where the `npm-shrinkwrap.json` comes in. It can be published, but should really only be used/published under certain conditions (taken from https://docs.npmjs.com/files/shrinkwrap.json):

> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies. It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

**Comment by mitar** [comment]
Ah, publishing == publishing on registry, not publishing == publishing to git.

**Comment by hwillson** [comment]
This is no longer an issue with Meteor 1.6.x. If anyone is still encountering this issue with 1.5.x, please consider upgrading (as the fix won't be backported). Thanks!
