### ISSUE TITLE
New bug when I install huttonr:bootstrap3 on Meteor 1.3.2-rc.5

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#6806]
```

=> Started proxy.
=> Started MongoDB.

/Users/alan/.meteor/packages/templating/.1.1.9-rc.5.1797ysm++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  data: <Buffer 2f 2f 20 54 68 65 73 65 20 73 74 79 6c 65 73 20 68 61 76 65 20 61 6c 72 65 61 64 79 20 62 65 65 6e 20 61 70 70 6c 69 65 64 20 74 6f 20 74 68 65 20 64 6f ...>,
  sourcePath: 'client/style/bootstrap-settings.json',
  servePath: '/client/stylesheets/bootstrap/bootstrap.generated.css',
  hash: 'bf5916be0fd88667452ec454871f4856bca634d3',
  sourceMap: undefined,
  lazy: true,
  bare: false,
  mainModule: false,
  imported: false,
  installPath: 'client/style/bootstrap-settings.json' }
{ type: 'js',
  data: <Buffer 4d 65 74 65 6f 72 2e 5f 62 6f 6f 74 73 74 72 61 70 53 65 74 74 69 6e 67 73 46 69 6c 65 4c 6f 61 64 65 64 20 3d 20 74 72 75 65 3b 0a 69 66 20 28 4d 65 74 ...>,
  sourcePath: 'client/style/bootstrap-settings.json',
  servePath: '/client/lib/bootstrap/bootstrap.generated.js',
  hash: 'ea714bcffd9feb404af15da8baf24afe316f7216',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'client/style/bootstrap-settings.json' }

    at checkProperty (/tools/isobuild/import-scanner.js:198:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:187:35)
    at /tools/isobuild/import-scanner.js:177:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:148:11)
    at /tools/isobuild/compiler-plugin.js:825:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:796:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/alan/.meteor/packages/meteor-tool/.1.3.2-rc.5.1b3tzvt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36

$ meteor --version
Meteor 1.3.2-rc.5

$ meteor list
accounts-password      1.1.8-rc.5  Password support for accounts
alanning:roles         1.2.15  Authorization package for Meteor
aldeed:collection2     2.9.1  Automatic validation of insert and update operations on the client a...
autopublish            1.0.7-rc.5  (For prototyping only) Publish the entire database to all clients
blaze-html-templates   1.0.4-rc.5  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript             0.4.3-rc.5  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.5.10-rc.5  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7-rc.5  (For prototyping only) Allow all database writes from the client
jquery                 1.11.8-rc.5  Manipulate the DOM using CSS selectors
less                   2.5.8-rc.5  Leaner CSS language
meteor-base            1.0.4-rc.5  Packages that every Meteor app needs
mobile-experience      1.0.4-rc.5  Packages for a great mobile user experience
mongo                  1.1.7-rc.5  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.9-rc.5  Reactive variable
standard-minifier-css  1.0.6-rc.5  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.0.6-rc.5  Standard javascript minifiers used with Meteor apps by default.
tracker                1.0.13-rc.5  Dependency tracker to allow reactive callbacks

$ uname -a
Darwin alan-MBP-151.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [x] What version of Meteor you're using, and the platform(s) you're running it on
- [x] What packages or other dependencies you're using
- [x] The behavior you expect to see, and the actual behavior
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

**Comment by benjamn** [comment]
Anything in your `node_modules` directory?

**Comment by benjamn** [comment]
This should be fixed if you do `meteor update --release 1.3.2-rc.6`.

**Comment by maxnowack** [comment]
I've got a similar error after upgrading to `1.3.2-rc.6`

````
=> Started proxy.                             
=> Started MongoDB.                           
                                              
/Users/maxnowack/.meteor/packages/stylus/.2.511.5-rc.6.89eugy++os+web.browser+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  sourcePath: 'both/translations/de-XX.i18n.json',
  servePath: 'both/translations/de-XX.i18n.json',
  installPath: 'both/translations/de-XX.i18n.json',
  deps: { './de-XX.i18n.json': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 64 65 2d 58 58 2e 69 31 38 6e 2e 6a 73 6f 6e 22 29 3b 0a>,
  hash: '77c5c4c964109f59f4b8925fc1cf4dc0b4d6ab19' }
{ type: 'js',
  data: <Buffer 76 61 72 20 5f 20 3d 20 50 61 63 6b 61 67 65 2e 75 6e 64 65 72 73 63 6f 72 65 2e 5f 2c 0a 20 20 20 20 70 61 63 6b 61 67 65 5f 6e 61 6d 65 20 3d 20 22 70 ...>,
  sourcePath: '/both/translations/de-XX.i18n.json',
  targetPath: '/both/translations/de-XX.i18n.json',
  servePath: '/both/translations/de-XX.i18n.json',
  hash: '0ea7671114bf065b054904ef50ae541355e9b9d1',
  sourceMap: undefined,
  lazy: undefined,
  bare: false,
  mainModule: false,
  installPath: 'both/translations/de-XX.i18n.json',
  imported: true }

    at checkProperty (/tools/isobuild/import-scanner.js:269:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:258:35)
    at /tools/isobuild/import-scanner.js:187:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:158:11)
    at /tools/isobuild/compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/maxnowack/.meteor/packages/meteor-tool/.1.3.2-rc.6.lsbbl2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
````

**Comment by maxnowack** [comment]
@benjamn I've seen that you have released `1.3.2`. The issue still exists for me ...

**Comment by benjamn** [comment]
@maxnowack I know the error looks similar, but I think the underlying issue is slightly different. Can you put together a small reproduction (including especially the i18n package that you're using), and file a new issue?

**Comment by maxnowack** [comment]
@benjamn sure,  I'll do that :) Should I post the link to the repo here or should I create a new issue?

**Comment by benjamn** [comment]
I should have taken this problem more seriously! Now publishing a 1.3.2.1 patch release for 1.3.2… 😣

**Comment by benlavalley** [comment]
I almost posted this up as a new issue until I updated my Github search filter to show everything instead of it's default of "is:issue is:open" :)

@benjamn Updated to 1.3.2.1 and can confirm this fixes the issue with tap:i18n.

**Comment by trajano** [comment]
Does the issue happen with twbs:bootstrap I think that's the official one from the Twitter Bootstrap team.
