### ISSUE TITLE
[1.3.2] Package testing not working

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6827]
I'm having issues trying to test packages.

When I run:

`meteor test-packages --driver-package practicalmeteor:mocha casalova:user-availability --port 3000`

I get a crash telling me:

```
W20160415-17:08:20.346(-4)? (STDERR) /Users/clayne/.meteor/packages/meteor-tool/.1.3.2.1ki5fk2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160415-17:08:20.346(-4)? (STDERR) 						throw(ex);
W20160415-17:08:20.346(-4)? (STDERR) 						      ^
W20160415-17:08:20.363(-4)? (STDERR) Error: Can't find npm module 'lodash/memoize'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160415-17:08:20.364(-4)? (STDERR)     at Object.Npm.require (/private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1wmvy2i/.meteor/local/build/programs/server/boot.js:195:17)
W20160415-17:08:20.364(-4)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160415-17:08:20.364(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:81:1)
W20160415-17:08:20.364(-4)? (STDERR)     at meteorInstall.node_modules.meteor.casalova:core.both.casalova_ui_utils.js (packages/casalova:core/both/casalova_ui_utils.js:3:1)
W20160415-17:08:20.364(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160415-17:08:20.364(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160415-17:08:20.364(-4)? (STDERR)     at /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1wmvy2i/.meteor/local/build/programs/server/packages/casalova_core.js:322:1
W20160415-17:08:20.364(-4)? (STDERR)     at /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1wmvy2i/.meteor/local/build/programs/server/packages/casalova_core.js:336:3
W20160415-17:08:20.364(-4)? (STDERR)     at /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1wmvy2i/.meteor/local/build/programs/server/boot.js:283:10
W20160415-17:08:20.364(-4)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

I import `lodash/memoize` in one of my packages. If I remove that import, the next `import` of an Npm module that i have in my code fails in exactly the same way.

It looks like the test driver is not using my `node_modules` folder from the root of my project.

**Comment by benjamn** [comment]
This is definitely something we want to fix. I believe the problem is that we create a temporary app directory for running the tests, but we don't copy (or symlink) the app's `node_modules` directory into the temp directory.

cc @tmeasday

**Comment by tmeasday** [comment]
@benjamn - correct. I think we should figure out a correct fix for this.

@clayne11 - there's a workaround however, as you can see here: http://guide.meteor.com/writing-packages.html#testing-with-peer-dependencies

**Comment by clayne11** [comment]
For me,  the workaround basically completely defeats the purpose of unit tests. If the tests take longer than a couple of seconds to run when I make a change I'm simply not going to run them and they're not going to be effective.

In the regular Javascript community we can run hundreds of tests in a matter of seconds. With Meteor, even the package unit tests take a minute or so to start up. I haven't been able to test re-run speeds because of this issue but I doubt it's particularly fast.

Combine that with the fact that I have around 120 packages in my app and even unit testing becomes a nightmare that takes 20-30 minutes. All of this can be resolved by fulling moving to an Npm solution but I think that's still quite a ways away. 

A great stopgap would be to build all the Meteor packages into Npm packages and allow us to run regular unit tests on the built packages. That way we can build the packages once, then employ a test runner like regular `mocha` to run our unit tests extremely quickly. I think it would only work for packages that use explicit `export` and `import` but that's still quite reasonable.

I'm not 100% familiar with the Meteor build system so I'm not sure if what I'm suggesting is currently possible. Any thoughts on this?

**Comment by benjamn** [comment]
Ok! I have a [fix](https://github.com/meteor/meteor/commit/f2591a4ad0f8fa4a3bcf82936800513c417f0727) for this on the https://github.com/meteor/meteor/tree/release-1.3.3 branch. Hopefully we can get a `-beta.0` out for that branch soon.

**Comment by tmeasday** [comment]
That's the direction we are moving in certainly. Current thinking is it'll work pretty well as you've outlined for the core meteor packages that don't depend on build plugins apart from `ecmascript` (which can be simulated with a `babel-plugin`). Other build plugins may not be as easy to deal with an might still require running the meteor build tool (which will be a problem for running external testing tools like mocha).

**Comment by clayne11** [comment]
Not working for me. The `origNodeModulesDir` is a string. I added logging at `package-source.js:1321`:

```
gadicc:babel-compiler-hot: updating npm dependencies -- meteor-babel, meteor-hotload-accelerator, mkdirp...
=> Starting gadicc:ecmascript-hot Accelerator(1) on port 3002.

---- ORIGI NODE MODULE DIR ---- asalova:...  |




/Users/clayne/workspace/r3ntr_meteor/node_modules

/Users/clayne/workspace/meteor/packages/promise/.npm/package/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^

[gadicc:hot] Accelerator(1): disconnect event received, exiting.
TypeError: Object /Users/clayne/workspace/r3ntr_meteor/node_modules has no method 'isDirectory'
    at /tools/isobuild/package-source.js:1324:30
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/clayne/workspace/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at PackageSource._.extend.initFromAppDir (/tools/isobuild/package-source.js:1266:7)
    at /tools/isobuild/bundler.js:2471:19
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2467:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by benjamn** [comment]
Right you are! Fixed in a follow-up commit: https://github.com/meteor/meteor/commit/2c87c0fabe54f1d5e3dff7b7f3edf6a42ccbac7b

**Comment by clayne11** [comment]
Working! Thanks.

**Comment by tmeasday** [comment]
Not working for me here https://github.com/meteor/react-packages/tree/1.3.3-package-tests

1. It'd be great if you ran `meteor test-packages ./` in a package dir that it copied the node_modules out of there (I'm not seeing that when I do that in `packages/react-meteor-data`.

2. As a fallback a test app is acceptable. However it's not working when I do `meteor test-packages` in the `tests/harness` app (which links to the other packages and has the required node modules).

**Comment by benjamn** [comment]
@tmeasday Copying `node_modules` is something I would prefer to avoid in development as much as possible, since `node_modules` directories can get *huge*. This fix simply ensures the app's `node_modules` directory is available to the tests, without copying anything. Any local `node_modules` directories in packages should already be visible, though perhaps not if `Npm.depends` is also used…

**Comment by tmeasday** [comment]
@benjamn you are correct that for packages with a `node_modules/` this already works (although `check-npm-versions` does complain).

**Comment by benjamn** [comment]
This should be fixed if you do `meteor update --release 1.3.3-beta.0`, though `tmeasday:check-npm-versions` may still complain about missing dependencies. The good news is that we can improve that package independent of the Meteor release cycle.

**Comment by tmeasday** [comment]
Tell me how to fix that @benjamn ;)

**Comment by macsj200** [comment]
Hi all, sorry to reopen an old thread, but I think I'm still having this issue with the latest version of Meteor, `test-packages` and `dispatch:mocha` with phantomjs. Any ideas why phantomjs might not be found when testing a package?
