### ISSUE TITLE
windows 10 64 bit issue with meteor

### ISSUE THREAD

**Issue by BahramSoheili** [meteor/meteor#7306]
***2 Upvotes*** I have recently migrated to meteor 1.3.4-1 in windows10 64bit but I couldn't create a meteor project yet in here as following:

```
C:\Users\Bahram>meteor create ss
C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-runtime.js:8
require("meteor-promise").makeCompatible(Promise, require("fibers"));
                          ^
TypeError: Object function Promise(fn) {
  if (typeof this !== 'object') {
    throw new TypeError('Promises must be constructed via new');
  }
  if (typeof fn !== 'function') {
    throw new TypeError('not a function');
  }
  this._45 = 0;
  this._81 = 0;
  this._65 = null;
  this._54 = null;
  if (fn === noop) return;
  doResolve(fn, this);
} has no method 'makeCompatible'
    at Object.<anonymous> (C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-runtime.js:8:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-babel.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by n1cklarosa** [comment]
+1
Just had to move to a windows machine for a few days and I am getting the same issue

**Comment by lucas-issa** [comment]
+1

I just created a new project with a new Meteor install in a Windows10 (64 bit) and I have the same error when I try to run meteor command.

### Error output:

**> meteor**
```
[[[[[ ...\teste ]]]]]

=> Started proxy.                             
=> Started MongoDB.      

...\teste\.meteor\local\build\programs\server\shell-server.js:15
require("meteor-promise").makeCompatible(Promise, require("fibers"));
                          ^
TypeError: Object function Promise(fn) {
  if (typeof this !== 'object') {
    throw new TypeError('Promises must be constructed via new');
  }      
  if (typeof fn !== 'function') {
    throw new TypeError('not a function');
  }      
  this._45 = 0;
  this._81 = 0;
  this._65 = null;
  this._54 = null;
  if (fn === noop) return;
  doResolve(fn, this);
} has no method 'makeCompatible'
    at Object.<anonymous> (...\teste\.meteor\local\build\programs\server\shell-server.js:15:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (...\teste\.meteor\local\build\programs\server\boot.js:101:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8     
```                   

### Versions:

**> meteor --version**
`Meteor 1.3.4`

**> meteor node --version**
`v0.10.45`

**> meteor npm --version**
`3.9.6`

**> meteor list**
```
angular2-compilers         0.5.7  Angular 2 Templates, HTML and TypeScript compilers for Meteor
autopublish                1.0.7  (For prototyping only) Publish the entire database to all clients
barbatus:angular2-runtime  0.5.0  Polyfills for Angular2
ecmascript                 0.4.6* Compiler plugin that supports ES2015+ in all .js files
es5-shim                   4.5.12* Shims and polyfills to improve ECMAScript 5 support
insecure                   1.0.7  (For prototyping only) Allow all database writes from the client
jquery                     1.11.9  Manipulate the DOM using CSS selectors
meteor-base                1.0.4  Packages that every Meteor app needs
mobile-experience          1.0.4  Packages for a great mobile user experience
mongo                      1.1.9* Adaptor for using MongoDB and Minimongo over DDP
reactive-var               1.0.10  Reactive variable
standard-minifier-css      1.0.7* Standard css minifier used with Meteor apps by default.
standard-minifier-js       1.0.7* Standard javascript minifiers used with Meteor apps by default.
tracker                    1.0.14  Dependency tracker to allow reactive callbacks
```

**> meteor npm ls**
```
teste@ ...\teste
+-- @angular/common@2.0.0-rc.1
+-- @angular/compiler@2.0.0-rc.1
+-- @angular/core@2.0.0-rc.1
+-- @angular/platform-browser@2.0.0-rc.1
+-- @angular/platform-browser-dynamic@2.0.0-rc.1
+-- @angular/router@3.0.0-alpha.3
+-- angular2-meteor@0.5.5
| `-- meteor-promise@0.6.3
|   `-- promise@7.1.1
|     `-- asap@2.0.4
+-- angular2-meteor-auto-bootstrap@0.5.5
+-- angular2-meteor-polyfills@0.1.1
+-- es6-shim@0.35.1
+-- meteor-node-stubs@0.2.3
| +-- assert@1.3.0
| +-- browserify-zlib@0.1.4
| | `-- pako@0.2.8
| +-- buffer@4.5.1
| | +-- base64-js@1.1.2
| | +-- ieee754@1.1.6
| | `-- isarray@1.0.0
| +-- console-browserify@1.1.0
| | `-- date-now@0.1.4
| +-- constants-browserify@1.0.0
| +-- crypto-browserify@3.11.0
| | +-- browserify-cipher@1.0.0
| | | +-- browserify-aes@1.0.6
| | | | +-- buffer-xor@1.0.3
| | | | `-- cipher-base@1.0.2
| | | +-- browserify-des@1.0.0
| | | | +-- cipher-base@1.0.2
| | | | `-- des.js@1.0.0
| | | |   `-- minimalistic-assert@1.0.0
| | | `-- evp_bytestokey@1.0.0
| | +-- browserify-sign@4.0.0
| | | +-- bn.js@4.11.1
| | | +-- browserify-rsa@4.0.1
| | | +-- elliptic@6.2.3
| | | | +-- brorand@1.0.5
| | | | `-- hash.js@1.0.3
| | | `-- parse-asn1@5.0.0
| | |   +-- asn1.js@4.5.2
| | |   | `-- minimalistic-assert@1.0.0
| | |   +-- browserify-aes@1.0.6
| | |   | +-- buffer-xor@1.0.3
| | |   | `-- cipher-base@1.0.2
| | |   `-- evp_bytestokey@1.0.0
| | +-- create-ecdh@4.0.0
| | | +-- bn.js@4.11.1
| | | `-- elliptic@6.2.3
| | |   +-- brorand@1.0.5
| | |   `-- hash.js@1.0.3
| | +-- create-hash@1.1.2
| | | +-- cipher-base@1.0.2
| | | +-- ripemd160@1.0.1
| | | `-- sha.js@2.4.5
| | +-- create-hmac@1.1.4
| | +-- diffie-hellman@5.0.2
| | | +-- bn.js@4.11.1
| | | `-- miller-rabin@4.0.0
| | |   `-- brorand@1.0.5
| | +-- inherits@2.0.1
| | +-- pbkdf2@3.0.4
| | +-- public-encrypt@4.0.0
| | | +-- bn.js@4.11.1
| | | +-- browserify-rsa@4.0.1
| | | `-- parse-asn1@5.0.0
| | |   +-- asn1.js@4.5.2
| | |   | `-- minimalistic-assert@1.0.0
| | |   +-- browserify-aes@1.0.6
| | |   | +-- buffer-xor@1.0.3
| | |   | `-- cipher-base@1.0.2
| | |   `-- evp_bytestokey@1.0.0
| | `-- randombytes@2.0.3
| +-- domain-browser@1.1.7
| +-- events@1.1.0
| +-- http-browserify@1.7.0
| | +-- Base64@0.2.1
| | `-- inherits@2.0.1
| +-- https-browserify@0.0.1
| +-- os-browserify@0.2.1
| +-- path-browserify@0.0.0
| +-- process@0.11.2
| +-- punycode@1.4.1
| +-- querystring-es3@0.2.1
| +-- readable-stream@2.0.6
| | +-- core-util-is@1.0.2
| | +-- inherits@2.0.1
| | +-- isarray@1.0.0
| | +-- process-nextick-args@1.0.6
| | `-- util-deprecate@1.0.2
| +-- stream-browserify@2.0.1
| | `-- inherits@2.0.1
| +-- string_decoder@0.10.31
| +-- timers-browserify@1.4.2
| +-- tty-browserify@0.0.0
| +-- url@0.11.0
| | +-- punycode@1.3.2
| | `-- querystring@0.2.0
| +-- util@0.10.3
| | `-- inherits@2.0.1
| `-- vm-browserify@0.0.4
|   `-- indexof@0.0.1
+-- reflect-metadata@0.1.2
+-- rxjs@5.0.0-beta.6
+-- typings@1.3.0
| +-- any-promise@1.3.0
| +-- archy@1.0.0
| +-- bluebird@3.4.1
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- columnify@1.5.4
| | `-- wcwidth@1.0.1
| |   `-- defaults@1.0.3
| |     `-- clone@1.0.2
| +-- listify@1.0.0
| +-- minimist@1.2.0
| +-- typings-core@1.2.4
| | +-- array-uniq@1.0.3
| | +-- configstore@2.0.0
| | | +-- dot-prop@2.4.0
| | | | `-- is-obj@1.0.1
| | | +-- object-assign@4.1.0
| | | +-- os-tmpdir@1.0.1
| | | +-- osenv@0.1.3
| | | +-- uuid@2.0.2
| | | `-- write-file-atomic@1.1.4
| | |   +-- imurmurhash@0.1.4
| | |   `-- slide@1.1.6
| | +-- debug@2.2.0
| | | `-- ms@0.7.1
| | +-- detect-indent@4.0.0
| | | `-- repeating@2.0.1
| | |   `-- is-finite@1.0.1
| | |     `-- number-is-nan@1.0.0
| | +-- graceful-fs@4.1.4
| | +-- has@1.0.1
| | | `-- function-bind@1.1.0
| | +-- invariant@2.2.1
| | | `-- loose-envify@1.2.0
| | |   `-- js-tokens@1.0.3
| | +-- is-absolute@0.2.5
| | | +-- is-relative@0.2.1
| | | | `-- is-unc-path@0.1.1
| | | |   `-- unc-path-regex@0.1.2
| | | `-- is-windows@0.1.1
| | +-- lockfile@1.0.1
| | +-- make-error-cause@1.1.1
| | | `-- make-error@1.1.1
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | +-- object.pick@1.1.2
| | | `-- isobject@2.1.0
| | |   `-- isarray@1.0.0
| | +-- parse-json@2.2.0
| | | `-- error-ex@1.3.0
| | |   `-- is-arrayish@0.2.1
| | +-- popsicle@6.2.1
| | | +-- arrify@1.0.1
| | | +-- concat-stream@1.5.1
| | | | +-- inherits@2.0.1
| | | | +-- readable-stream@2.0.6
| | | | | +-- core-util-is@1.0.2
| | | | | +-- process-nextick-args@1.0.7
| | | | | +-- string_decoder@0.10.31
| | | | | `-- util-deprecate@1.0.2
| | | | `-- typedarray@0.0.6
| | | +-- form-data@0.2.0
| | | | +-- async@0.9.2
| | | | +-- combined-stream@0.0.7
| | | | | `-- delayed-stream@0.0.5
| | | | `-- mime-types@2.0.14
| | | |   `-- mime-db@1.12.0
| | | +-- throwback@1.1.1
| | | `-- tough-cookie@2.2.2
| | +-- popsicle-proxy-agent@2.0.2
| | | +-- http-proxy-agent@1.0.0
| | | | +-- agent-base@2.0.1
| | | | `-- extend@3.0.0
| | | `-- https-proxy-agent@1.0.0
| | +-- popsicle-retry@3.2.1
| | +-- popsicle-status@2.0.0
| | +-- promise-finally@2.2.1
| | +-- rc@1.1.6
| | | +-- deep-extend@0.4.1
| | | +-- ini@1.3.4
| | | `-- strip-json-comments@1.0.4
| | +-- rimraf@2.5.2
| | | `-- glob@7.0.5
| | |   +-- fs.realpath@1.0.0
| | |   +-- inflight@1.0.5
| | |   | `-- wrappy@1.0.2
| | |   +-- minimatch@3.0.2
| | |   | `-- brace-expansion@1.1.5
| | |   |   +-- balanced-match@0.4.1
| | |   |   `-- concat-map@0.0.1
| | |   +-- once@1.3.3
| | |   `-- path-is-absolute@1.0.0
| | +-- sort-keys@1.1.2
| | | `-- is-plain-obj@1.1.0
| | +-- string-template@1.0.0
| | +-- strip-bom@2.0.0
| | | `-- is-utf8@0.2.1
| | +-- thenify@3.2.0
| | +-- throat@3.0.0
| | +-- touch@1.0.0
| | | `-- nopt@1.0.10
| | |   `-- abbrev@1.0.9
| | +-- typescript@1.8.7
| | `-- zip-object@0.1.0
| +-- update-notifier@1.0.2
| | +-- boxen@0.6.0
| | | +-- ansi-align@1.1.0
| | | +-- camelcase@2.1.1
| | | +-- cli-boxes@1.0.0
| | | +-- filled-array@1.1.0
| | | +-- string-width@1.0.1
| | | | +-- code-point-at@1.0.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | `-- widest-line@1.0.0
| | +-- is-npm@1.0.0
| | +-- latest-version@2.0.0
| | | `-- package-json@2.3.2
| | |   +-- got@5.6.0
| | |   | +-- create-error-class@3.0.2
| | |   | | `-- capture-stack-trace@1.0.0
| | |   | +-- duplexer2@0.1.4
| | |   | +-- is-redirect@1.0.0
| | |   | +-- is-retry-allowed@1.0.0
| | |   | +-- is-stream@1.1.0
| | |   | +-- lowercase-keys@1.0.0
| | |   | +-- node-status-codes@1.0.0
| | |   | +-- pinkie-promise@2.0.1
| | |   | | `-- pinkie@2.0.4
| | |   | +-- read-all-stream@3.1.0
| | |   | +-- timed-out@2.0.0
| | |   | +-- unzip-response@1.0.0
| | |   | `-- url-parse-lax@1.0.0
| | |   |   `-- prepend-http@1.0.4
| | |   +-- registry-url@3.1.0
| | |   `-- semver@5.1.1
| | +-- lazy-req@1.1.0
| | +-- semver-diff@2.1.0
| | | `-- semver@5.0.3
| | `-- xdg-basedir@2.0.0
| |   `-- os-homedir@1.0.1
| +-- wordwrap@1.0.0
| `-- xtend@4.0.1
`-- zone.js@0.6.12
```

**Comment by benjamn** [comment]
Does it help if you manually install `meteor-promise` into `dev_bundle\lib\node_modules`?
```sh
meteor npm install -g meteor-promise@0.7.2
```

**Comment by BahramSoheili** [comment]
@benjamn unfortunately it didn't  solve it even to create a meteor project:

C:\Users\Bahram>meteor npm install -g meteor-promise@0.7.2
C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\bin
`-- meteor-promise@0.7.2

C:\Users\Bahram>meteor create dd

C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-runtime.js:8
require("meteor-promise").makeCompatible(Promise, require("fibers"));
                          ^
TypeError: Object function Promise(fn) {
  if (typeof this !== 'object') {
    throw new TypeError('Promises must be constructed via new');
  }
  if (typeof fn !== 'function') {
    throw new TypeError('not a function');
  }
  this._45 = 0;
  this._81 = 0;
  this._65 = null;
  this._54 = null;
  if (fn === noop) return;
  doResolve(fn, this);
} has no method 'makeCompatible'
    at Object.<anonymous> (C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-runtime.js:8:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-babel.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by benjamn** [comment]
@BahramSoheili thanks for trying that

What happens if you add
```js
console.log(require.resolve("meteor-promise"));
```
as the first line of `C:\Users\Bahram\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\tools\tool-env\install-runtime.js`?

The answer should be `C:\Users\Bahram\AppData\Local.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js`, but maybe somehow it's resolving differently?

**Comment by bduff9** [comment]
@benjamn I'm running into the same problem and just ran your test, which printed:
C:\Users\Duffey\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js

**Comment by lucas-issa** [comment]
Hi @benjamn. It didn't work for me too. The error still the same.

### More versions:

**>meteor npm -g ls**                          
```
C:\Users\Lucas\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\bin
+-- meteor-promise@0.7.2
`-- typings@1.3.0
  +-- any-promise@1.3.0
  +-- archy@1.0.0
  +-- bluebird@3.4.1
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.0.0
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- columnify@1.5.4
  | `-- wcwidth@1.0.1
  |   `-- defaults@1.0.3
  |     `-- clone@1.0.2
  +-- listify@1.0.0
  +-- minimist@1.2.0
  +-- typings-core@1.2.4
  | +-- array-uniq@1.0.3
  | +-- configstore@2.0.0
  | | +-- dot-prop@2.4.0
  | | | `-- is-obj@1.0.1
  | | +-- object-assign@4.1.0
  | | +-- os-tmpdir@1.0.1
  | | +-- osenv@0.1.3
  | | +-- uuid@2.0.2
  | | `-- write-file-atomic@1.1.4
  | |   +-- imurmurhash@0.1.4
  | |   `-- slide@1.1.6
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- detect-indent@4.0.0
  | | `-- repeating@2.0.1
  | |   `-- is-finite@1.0.1
  | |     `-- number-is-nan@1.0.0
  | +-- graceful-fs@4.1.4
  | +-- has@1.0.1
  | | `-- function-bind@1.1.0
  | +-- invariant@2.2.1
  | | `-- loose-envify@1.2.0
  | |   `-- js-tokens@1.0.3
  | +-- is-absolute@0.2.5
  | | +-- is-relative@0.2.1
  | | | `-- is-unc-path@0.1.1
  | | |   `-- unc-path-regex@0.1.2
  | | `-- is-windows@0.1.1
  | +-- lockfile@1.0.1
  | +-- make-error-cause@1.1.1
  | | `-- make-error@1.1.1
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | +-- object.pick@1.1.2
  | | `-- isobject@2.1.0
  | |   `-- isarray@1.0.0
  | +-- parse-json@2.2.0
  | | `-- error-ex@1.3.0
  | |   `-- is-arrayish@0.2.1
  | +-- popsicle@6.2.1
  | | +-- arrify@1.0.1
  | | +-- concat-stream@1.5.1
  | | | +-- inherits@2.0.1
  | | | +-- readable-stream@2.0.6
  | | | | +-- core-util-is@1.0.2
  | | | | +-- process-nextick-args@1.0.7
  | | | | +-- string_decoder@0.10.31
  | | | | `-- util-deprecate@1.0.2
  | | | `-- typedarray@0.0.6
  | | +-- form-data@0.2.0
  | | | +-- async@0.9.2
  | | | +-- combined-stream@0.0.7
  | | | | `-- delayed-stream@0.0.5
  | | | `-- mime-types@2.0.14
  | | |   `-- mime-db@1.12.0
  | | +-- throwback@1.1.1
  | | `-- tough-cookie@2.2.2
  | +-- popsicle-proxy-agent@2.0.2
  | | +-- http-proxy-agent@1.0.0
  | | | +-- agent-base@2.0.1
  | | | `-- extend@3.0.0
  | | `-- https-proxy-agent@1.0.0
  | +-- popsicle-retry@3.2.1
  | +-- popsicle-status@2.0.0
  | +-- promise-finally@2.2.1
  | +-- rc@1.1.6
  | | +-- deep-extend@0.4.1
  | | +-- ini@1.3.4
  | | `-- strip-json-comments@1.0.4
  | +-- rimraf@2.5.2
  | | `-- glob@7.0.5
  | |   +-- fs.realpath@1.0.0
  | |   +-- inflight@1.0.5
  | |   | `-- wrappy@1.0.2
  | |   +-- minimatch@3.0.2
  | |   | `-- brace-expansion@1.1.5
  | |   |   +-- balanced-match@0.4.1
  | |   |   `-- concat-map@0.0.1
  | |   +-- once@1.3.3
  | |   `-- path-is-absolute@1.0.0
  | +-- sort-keys@1.1.2
  | | `-- is-plain-obj@1.1.0
  | +-- string-template@1.0.0
  | +-- strip-bom@2.0.0
  | | `-- is-utf8@0.2.1
  | +-- thenify@3.2.0
  | +-- throat@3.0.0
  | +-- touch@1.0.0
  | | `-- nopt@1.0.10
  | |   `-- abbrev@1.0.9
  | +-- typescript@1.8.7
  | `-- zip-object@0.1.0
  +-- update-notifier@1.0.2
  | +-- boxen@0.6.0
  | | +-- ansi-align@1.1.0
  | | +-- camelcase@2.1.1
  | | +-- cli-boxes@1.0.0
  | | +-- filled-array@1.1.0
  | | +-- string-width@1.0.1
  | | | +-- code-point-at@1.0.0
  | | | `-- is-fullwidth-code-point@1.0.0
  | | `-- widest-line@1.0.0
  | +-- is-npm@1.0.0
  | +-- latest-version@2.0.0
  | | `-- package-json@2.3.2
  | |   +-- got@5.6.0
  | |   | +-- create-error-class@3.0.2
  | |   | | `-- capture-stack-trace@1.0.0
  | |   | +-- duplexer2@0.1.4
  | |   | +-- is-redirect@1.0.0
  | |   | +-- is-retry-allowed@1.0.0
  | |   | +-- is-stream@1.1.0
  | |   | +-- lowercase-keys@1.0.0
  | |   | +-- node-status-codes@1.0.0
  | |   | +-- pinkie-promise@2.0.1
  | |   | | `-- pinkie@2.0.4
  | |   | +-- read-all-stream@3.1.0
  | |   | +-- timed-out@2.0.0
  | |   | +-- unzip-response@1.0.0
  | |   | `-- url-parse-lax@1.0.0
  | |   |   `-- prepend-http@1.0.4
  | |   +-- registry-url@3.1.0
  | |   `-- semver@5.1.1
  | +-- lazy-req@1.1.0
  | +-- semver-diff@2.1.0
  | | `-- semver@5.0.3
  | `-- xdg-basedir@2.0.0
  |   `-- os-homedir@1.0.1
  +-- wordwrap@1.0.0
  `-- xtend@4.0.1

```

**Comment by benjamn** [comment]
Next question: if you open `AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js`, does it not look like [this](https://github.com/meteor/promise/blob/master/promise_server.js)? I'm struggling to imagine how `require("meteor-promise")` can evaluate to the `Promise` constructor when all that module does is define `exports.makeCompatible`.

**Comment by lucas-issa** [comment]
Yes.

```
var assert = require("assert");
var fiberPool = require("./fiber_pool.js").makePool();

exports.makeCompatible = function (Promise, Fiber) {
  var es6PromiseThen = Promise.prototype.then;

  if (typeof Fiber === "function") {
    Promise.Fiber = Fiber;
  }
...
```

**Comment by lucas-issa** [comment]
I'm trying to use Angular2. I followed this tutorial: http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

But I had to change some versions to fix some other errors.

**My package.json:**
```
{
  "name": "teste",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router":"3.0.0-alpha.3",
    "angular2-meteor": "0.5.5",
    "angular2-meteor-auto-bootstrap": "0.5.5",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "typings": "^1.3.0",
    "zone.js": "0.6.12"
  }
}
```

**Comment by lucas-issa** [comment]
I fixed the problem.

In the `node_modules` of the project folder (`<project>/node_modules`) there was a `meteor-promise` with an old version (0.6.3). I deleted this folder (`meteor-promise`) and the error was gone. It seems that this dependence was added by `angular2-meteor`. Later I will try to force the dependency to a newer version rather than erase the folder.

@benjamn  thanks for your help!

**Comment by BahramSoheili** [comment]
@benjamn  i have that route in my machine:

C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise>dir
 Volume in drive C has no label.
 Volume Serial Number is 7C48-DAE6

 Directory of C:\Users\Bahram\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise

06/27/2016  02:13 AM    <DIR>          .
06/27/2016  02:13 AM    <DIR>          ..
06/24/2016  08:22 AM                20 .npmignore
06/24/2016  08:22 AM               213 .travis.yml
06/24/2016  08:22 AM             3,833 fiber_pool.js
06/24/2016  08:22 AM             1,092 LICENSE
06/24/2016  08:22 AM             2,413 package.json
06/24/2016  08:22 AM               564 promise_client.js
06/24/2016  08:22 AM             4,107 promise_server.js
06/24/2016  08:22 AM             1,066 README.md

**Comment by BahramSoheili** [comment]
@lucas-issa  I couldn't create meteor project in so how can I delete the file you described?

**Comment by bduff9** [comment]
@lucas-issa That fix worked for me too, thanks!

In my particular case, I just cloned the base package from meteor chef and ran it.  When I ran it (successfully the first time) it complained that it was an older version of meteor so I updated meteor, which gave me an issue on startup with fibers.  I rectified that, which then had this issue.  Not sure exactly where it went wrong, but deleting the meteor-promise folder definitely fixed it for me.

**Comment by BahramSoheili** [comment]
@bduff9  will it have side effect in future? how come if we need to use meteor_promise inside our project?

**Comment by BahramSoheili** [comment]
@lucas-issa @benjamn I have deleted meteor_promise in clone project and the problem still remains...

**Comment by lucas-issa** [comment]
I executed the command `meteor NPM install meteor-promise@0.7.2 --save` and the error was fixed without removing the 'meteor-promise` folder.

**Comment by BahramSoheili** [comment]
unfortunately it did not solve my problem at all, I have tested all of solutions that presented in here but this issue still remains...

**Comment by abernix** [comment]
A lot of issues with Windows have been resolved since this version of Meteor was released.  If you are still having problems, please upgrade your project to Meteor 1.4.1.1.  Also, please consider doing a fresh uninstall before upgrading as there might be some funky residue left over from past versions that could be difficult to debug.  A fresh install is best – using these instructions...

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.4.1.1 from https://install.meteor.com/windows (skip logging in at the end due to #6218 bug)
* **Restart** (this is very important)
* Open Command Prompt and type `meteor --version` to confirm it's working. 

If problems continue, let's address them at that point.
