### ISSUE TITLE
Tarball created in Windows using "meteor build" fails to deploy to hosting environment

### ISSUE THREAD

**Issue by tab00** [meteor/meteor#7401]
Deployment fails if the following 2 conditions are true:
1. Meteor app has (cheerio OR pusher-client) AND (bufferutil OR utf-8-validate) NPM packages.
2. Tarball created locally in Windows using `meteor build` and `--architecture os.linux.x86_64` option

Deployment of the same app succeeds if `meteor build` is done in the hosting environment instead of locally e.g. using [Meteor Buildpack Horse](https://github.com/AdmitHub/meteor-buildpack-horse). So there could be a problem with running `meteor build` in Windows for a Linux hosting environment.

Also, deployment of the app succeeds via local build if either cheerio is removed or bufferutil is removed (or both).

Here are more details:

Local development platform: Windows 10
Hosting environment platform: Linux
Meteor version: 1.3.4.1. Upgrading to version 1.3.4.4 did not fix the problem.

NPM packages:
[cheerio](https://www.npmjs.com/package/cheerio)
[bufferutil](https://www.npmjs.com/package/bufferutil)

Error messages in deployment script log:
```
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/tmp/staged/app/.meteor/heroku_build/bin/node" "/tmp/staged/app/.meteor/heroku_build/bin/npm" "rebuild"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! path /tmp/staged/app/.meteor/heroku_build/app/programs/server/npm/node_modules/cheerio/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin\sshpk-conv
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! enoent ENOENT, chmod '/tmp/staged/app/.meteor/heroku_build/app/programs/server/npm/node_modules/cheerio/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin\sshpk-conv'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/staged/app/.meteor/heroku_build/app/programs/server/npm/npm-debug.log
npm ERR! argv "/tmp/staged/app/.meteor/heroku_build/bin/node" "/tmp/staged/app/.meteor/heroku_build/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! Exit status 34
npm ERR! Linux 3.19.0-33-generic
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/staged/app/.meteor/heroku_build/app/programs/server/npm-debug.log
Staging failed: Buildpack compilation step failed
```

Error reproduction procedure:
In a Windows command prompt, `cd` to projects directory.
Type:
```
meteor create test-f83jf
cd test-f83jf
npm install --save cheerio bufferutil
meteor build "..\test-f83jf-built" --architecture os.linux.x86_64 --server-only
cd ..\test-f83jf-built
```
Attempt to deploy the .tar.gz file to a hosting account. I have an IBM Bluemix hosting account, so I deploy the .tar.gz using Cloud Foundry CLI and my deployment script which is mostly the same as Meteor Buildpack Horse but with the `meteor build` step removed:
`cf push test-f83jf -b https://github.com/tab00/prebuiltdeploy -c ".meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js"`

**Comment by tab00** [comment]
I've updated my post above to add pusher-client and utf-8-validate NPM packages.

Both cheerio and pusher-client has the "request" NPM package as a dependency. So maybe bufferutil and utf-8-validate conflict with packages that use "request", if deploying from a tarball.

**Comment by benjamn** [comment]
Note that `meteor build --architecture` only affects Atmosphere packages that have been published for multiple platforms using `meteor publish-for-arch`. Atmosphere packages have a mechanism for pre-publishing binaries, but `npm` packages generally do not.

For `npm` packages with binary modules, the `npm rebuild` command has to succeed on the target architecture. From your logs, it looks like the `sshpk` package may be missing some files (e.g. `bin/sshpk-conv`).

Does `/tmp/staged/app/.meteor/heroku_build/app/programs/server/npm/npm-debug.log` have any more useful information?

**Comment by tab00** [comment]
> From your logs, it looks like the sshpk package may be missing some files (e.g. bin/sshpk-conv).

Did you notice the backslash character in 'http-signature/node_modules/sshpk/bin\sshpk-conv''?
I think that comes from the package.json file of `sshpk` that is contained in the tarball when I build in my Windows platform. Here is the "bin" section of that file:
```
  "bin": {
    "sshpk-conv": "bin\\sshpk-conv",
    "sshpk-sign": "bin\\sshpk-sign",
    "sshpk-verify": "bin\\sshpk-verify"
  },
```
Could this be the problem?


> Does /tmp/staged/app/.meteor/heroku_build/app/programs/server/npm/npm-debug.log have any more useful information?

I can only access the files when an app is running. Since deployment fails the app doesn't run, so I cannot access the files.

**Comment by benjamn** [comment]
That `\` does seem noteworthy. Maybe try editing the `sshpk/package.json` file before running `node npm-rebuild.js` on Linux, just to see if that would fix it?

**Comment by benjamn** [comment]
I can reproduce the error if I manually replace the `/`s in the `"bin": {...}` section with `\\`s, so I believe that's the root of the problem. Unfortunately, this seems to be an `npm` problem: specifically, `npm rebuild` doesn't (always) work when the package was original installed on Windows.

**Comment by benjamn** [comment]
I can avoid this specific problem by running `npm rebuild --no-bin-links`, but I'm not sure if it will manifest itself in other ways.

**Comment by tab00** [comment]
I replaced the double backslashes to forward slashes and that fixed the problem. I had to do it for each copy of the `sshpk` directory (one under cheerio, another under pusher-client).

So editing the package.json file is a workaround, but there needs to be a proper solution.

There are over 960 other package.json files in my app's built bundle, and this sshpk module was the only one that caused a problem. I've looked at some of the others and they all use a forward slash as the directory separator. So why are the backslash characters only appearing in sshpk's package.json?

**Comment by benjamn** [comment]
I think it's pretty rare for an `npm` package to have a `"directories": { "bin": "./path/to/bin" }` section, which is what results in the `"bin": { ... }` section in the installed `package.json`.

Proper-er fix coming soon!

**Comment by tab00** [comment]
So was it `meteor build` that put the backslash characters based on the currently running platform?

Windows does actually understand  `/` as a path separator, so I don't think there needs to be any logic to determine which slash character to use. If we just use forward slashes always I think it should be fine.

Thank you for going ahead to fix it.

**Comment by benjamn** [comment]
No, I believe it was the original `npm install` that created the `"bin": {...}` section, and `npm` itself used `\`s when generating additional `package.json` properties, because the install took place on Windows. It's possible that `npm` should fix this by using `/`s everywhere, but that's up to them.

**Comment by tab00** [comment]
I've just updated Meteor on my Windows platform to version 1.3.5.1 and ran `meteor build` for my app. The resulting `package.json` of `sshpk` still contains backslash characters in the `bin` section:
```
  "bin": {
    "sshpk-conv": "bin\\sshpk-conv",
    "sshpk-sign": "bin\\sshpk-sign",
    "sshpk-verify": "bin\\sshpk-verify"
  },
```
Did you see something different in your own testing?

**Comment by abernix** [comment]
Your old mangled `node_modules` might still be lying around.  In your project root, can you:

0. Delete the `node_modules` directory
0. Run `meteor npm install`
0. Run your Meteor project once (e.g. just `meteor`)
0. Try doing the `meteor build`

**Comment by tab00** [comment]
Thank you. It's working after deleting the `node_modules` directory and running `meteor npm install` prior to doing `meteor build`. Deployment to Linux hosting is fine now without needing to edit any package.json files.

**Comment by wearhere** [comment]
[Some](https://github.com/meteor/meteor/issues/7401#issuecomment-232422585) [of](https://github.com/meteor/meteor/issues/7401#issuecomment-232434373) this discussion seems to suggest that the `bin` section of `package.json` is auto-generated and I can tell you that that is not the case, having added one to my own package [`install-files`](https://github.com/mixmaxhq/install-files).

That section just means that your package has an executable it'd like to expose to consumers—[npm docs](https://docs.npmjs.com/files/package.json#bin). One of the nice things about this is that these executables become available from consumers' `install` scripts [like this](https://github.com/mixmaxhq/install-files#example).

The effect of this change appears to be that Meteor does not properly register these executables, breaking packages' install scripts. I'm currently in conversation with Galaxy support about this, but also wanted to document it here.

**Comment by glasser** [comment]
It does look like `bin` gets autogenerated if you use the `directories.bin` feature of package.json instead of directly specifying `bin`.  So you could suggest to `sshpk` that they use `bin` instead of `directories.bin` (or use your own fork that does that).  Not sure if they would take "I depend on the ability to use `npm rebuild` on another platform" as a good justification though.  Or perhaps `npm rebuild` should be fixed to regenerate `bin` from `directories.bin`: after all, you're not allowed to provide both, so if they both exist it should be regenerated?

**Comment by tab00** [comment]
After creating a new project that targets the new 1.4.4.2 Meteor version I now see the exact same error return when I try to deploy to linux via tarball created in Windows:
```
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/app/.meteor/heroku_build/app/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'
npm ERR! enoent and is related to npm not being able to find a file.
```

**Comment by tab00** [comment]
Editing the package.json file of sshpk as described in https://github.com/meteor/meteor/issues/7401#issuecomment-232421798 made deployment work as before.

Please fix this problem (again). Thank you.

**Comment by tab00** [comment]
It looks like this problem has been fixed, as I now no longer need to edit the package.json file of sshpk. The relevant lines now already have forward slashes.

Thank you.

**Comment by rcurrier666** [comment]
I'm seeing the problem now with Meteor 1.4.4.2. I editted the package.json in npm-modules/sshpk and that fixed the problem for now. Hopefully it won't come back, but at least there is a work-around for the problem.

**Comment by cormip** [comment]
Still a problem in Meteor 1.5. Fortunately, the previously mentioned work-around does work.

**Comment by tab00** [comment]
I've just started using version 1.5.x and the problem has returned. So I've now had to go back to using the workaround -  `package.json` of `sshpk` - change:

```
  "bin": {
    "sshpk-conv": "bin\\sshpk-conv",
    "sshpk-sign": "bin\\sshpk-sign",
    "sshpk-verify": "bin\\sshpk-verify"
  },
```

to 
```
  "bin": {
    "sshpk-conv": "bin/sshpk-conv",
    "sshpk-sign": "bin/sshpk-sign",
    "sshpk-verify": "bin/sshpk-verify"
  },
```

I hope this will be fixed permanently soon.

**Comment by mrauhu** [comment]
@tab00 I have two solutions for you:

* If you are working with Meteor Up, then open `mup.js` and change value of field `docker.image` to [`mrauhu/meteord:base`](https://github.com/mrauhu/meteord)
* For standalone Linux installation:
1. Install patched NPM [@mrauhu/npm](https://github.com/mrauhu/npm):
```bash
npm install -g @mrauhu/npm
```
2. Check NPM version:
```
npm -v
# 5.3.0
```
3. Optionally, if NPM failed set right path:
```bash
# Fix path to the scoped NPM
#
# Warning:
# /opt/nodejs is example Node.js location, change it
#
rm /opt/nodejs/bin/npm
echo 'node /opt/nodejs/lib/node_modules/@mrauhu/npm/bin/npm-cli.js "$@"' > /opt/nodejs/bin/npm
chmod +x /opt/nodejs/bin/npm
```

**Comment by tab00** [comment]
@mrauhu, thanks, though I do not use Meteor Up, nor do I feel comfortable to use a patched NPM.

Will there be a proper permanent solution?

**Comment by mrauhu** [comment]
@tab00, then wait for merge of the pull request in the NPM:
https://github.com/npm/npm/pull/17802

**Comment by tab00** [comment]
When can we see the fix in Meteor?

**Comment by abernix** [comment]
I can confirm this is fixed in Meteor 1.6, which includes the fix from npm (and more specifically, the fix applied to [`read-package-json`](npm.im/read-package-json) in https://github.com/npm/read-package-json/pull/74.  Thank you very much @mrauhu for filing the issue with npm (and to the npm team for tracking down the exact fix)!

Keep in mind that Meteor 1.6 is currently a "beta", but follow that progress on #8728.
