### ISSUE TITLE
[1.4] New & existing projects cannot be run after update

### ISSUE THREAD

**Issue by TimeBandit** [meteor/meteor#7511]
Meteor updates to latest release after which projects exit with error when running `meteor` command. Same is seen when new a project is created using `meteor create 1-4-update-fail`

## Error seen:

> => Started proxy.                             
> Unexpected mongo exit code 100. Restarting.   
> Unexpected mongo exit code 100. Restarting.   
> Unexpected mongo exit code 100. Restarting.   
> Can't start Mongo server.                     
> MongoDB had an unspecified uncaught exception.
> This can be caused by MongoDB being unable to write to a local database.
> Check that you have permissions to write to .meteor/local. MongoDB does
> not support filesystems like NFS that do not allow file locking.

## Initial Conditions

System
![system](https://cloud.githubusercontent.com/assets/2059850/17207136/fef8b0ca-54aa-11e6-9bf6-640546273fe6.png)

Disk Usage
![disk](https://cloud.githubusercontent.com/assets/2059850/17207246/8b3c77ba-54ab-11e6-9866-61ecc853689d.png)

File System
![fs](https://cloud.githubusercontent.com/assets/2059850/17207421/6bc48f5c-54ac-11e6-8ae0-ff090cf5c643.png)

## Observations

1. The automatic update repeated a few times and I hung once at which point I `Ctrl^c` out of it.

## Things I’ve Tried

1. `meteor update`.
2.  `meteor reset`
3.  `meteor --version 1.4` output 1.4
4.   Ran export `LC_ALL="en_US.UTF-8"` command before meteor command as per this [SO](https://stackoverflow.com/questions/25102414/unexpected-mongo-exit-code-100-restarting) article.
5.   Tried  removing .meteor/local/db/mongod.lock as per this [SO](https://stackoverflow.com/questions/10103830/problems-to-run-examples-in-meteor) article but the file does not exist. Actually the db folder is empty with a new clean project.
6.   A fresh install of meteor using `curl https://install.meteor.com/ | sh`

## Reproduction
This issue is seen when creating a new project under 1.4. I have created a git repo. https://github.com/TimeBandit/meteor-1-4-update-fail

**Comment by pal8** [comment]
Same problem.

**Comment by DerMarcus** [comment]
Same problem as well

**Comment by jeffcutten** [comment]
Same here.

**Comment by DerekTBrown** [comment]
Try removing `~/.meteor/dev_bundle` and `~/.meteor/local` and attempt to restart.  Does this work?

**Comment by TimeBandit** [comment]
`~/.meteor/dev_bundle` does not exist in a new clean project. Deletion
of `~/.meteor/local` had no effect, reported error still seen.

**Comment by massimilianomarini** [comment]
Good to know I'm not the only with a 32bit and experiencing the same problem! :)

**Comment by tmeasday** [comment]
Confirmed, apologies for this folks.

**Comment by tmeasday** [comment]
The error message is 

```
2016-07-29T02:44:20.826+0000 I STORAGE  [initandlisten] exception in initAndListen: 28663 Cannot start server. The default storage engine 'wiredTiger' is not available with this build of mongod. Please specify a different storage engine explicitly, e.g. --storageEngine=mmapv1., terminating
```

---

So a workaround for the problem: 

1. When updating, don't migrate your database from mmapv1 (this means you can't `meteor reset` either).

2. If you want to create a new app, start with a 1.3 app and then update, respecting 1.

I'm looking into a proper fix.

**Comment by jeffcutten** [comment]
Temporarily I've rolled back to Meteor version 1.3.5.1 from 1.4 to get working again.

I tried `meteor create newtest --release 1.3.5.1` but it was hanging every time while downloading so with help from StackOverflow posts I did all this at the terminal:

`rm -rf ~/.meteor` deleted version 1.4

`curl -L https://install.meteor.com > meteor.sh` download current Meteor install script. Opened meteor.sh in a text editor and changed the version line to  `VERSION="1.3.5.1"`

`sh meteor.sh` at terminal to install Meteor version 1.3.5.1

`meteor create newtest --release 1.3.5.1` now works and I'm up and running again!

**Comment by tmeasday** [comment]
@jeffcutten - could you by any chance try `1.4.0.1-rc.3`? I'm having trouble getting it to install on my linux machine here.

**Comment by Zailef** [comment]
@tmeasday I have just tried version 1.4.0.1-rc.3 on 32bit Ubuntu (with Meteor 1.4) after having the issues with Mongodb mentioned above. Everything seems to be working fine now, thanks for the fix!

**Comment by TimeBandit** [comment]
@tmeasday I can confirm also that a project created using `meteor create newtest --release 1.3.5.1` runs A OK :+1:

**Comment by abernix** [comment]
Confirmed fixed on a new project created with `meteor create --release 1.4.0.1`

(which will be available/recommended soon via regular `meteor update`)

**Comment by laosb** [comment]
Someone in MeteorChina has just bumped into this.

**Comment by abernix** [comment]
@laosb They should not experience it anymore if they run `meteor update --release 1.4.0.1` right now! :wink:

**Comment by laosb** [comment]
@abernix Yeah, he confirmed this fix. Should we close this now?

**Comment by abernix** [comment]
Let's wait for Tom to confirm and close once he officially recommends the release as he's the assignee on this issue.

**Comment by TimeBandit** [comment]
@tmeasday @abernix 
I also ran `meteor update --release 1.4.0.1` within the folder of the project that had previously failed after it had been updated to `1.4` and seen the following error message:

> 
> => Started proxy.                             
> => Started MongoDB.                           
> /home/timebandit/.meteor/packages/meteor-tool/.1.4.0-1.1hg002y++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
>       throw error;
>       ^
> 
> Error: EACCES: permission denied, unlink '/home/timebandit/Documents/projects/charities_code/.meteor/local/build-garbage-tqoc4y/.node_version.txt'
>     at Error (native)
>

**Comment by TimeBandit** [comment]
If I take the specific project I had problems with after updating and perform a `meteor update --release 1.3` followed by a `meteor update --release 1.4.0.1` the project is running again

**Comment by y15651700507** [comment]
I have the same problem. My computer system is linux 32 bit. But when I changed system to 64 bit, the problem disappeared. I have made the codes (meteor update --release 1.4.0.1 ). Yet, the problem can't be solved for linux 32 bit system.

**Comment by tmeasday** [comment]
Should be fixed in 1.4.0.1

**Comment by y15651700507** [comment]
@abernix The problem has disappeared, when I do as follow: curl https://install.meteor.com/ | sh（appear above problem）→meteor update --release 1.4.0.1（appear above problem）→meteor update --release 1.3（problem disappeared）→ meteor update --release 1.4.0.1-rc.3（problem disappeared）→meteor update --release 1.4.0.1（problem disappeared). Even though,I don't know what have changed in meteor, I am very happy that the problem has been solved. Thanks very much.

**Comment by scott-cornwell** [comment]
@tmeasday I tried all of the suggested fixes and I still get this, ideas? I am on 64 bit Ubuntu. I am upgrading a project to 1.4.

**Comment by tmeasday** [comment]
@scott-cornwell this particular issue was unique to linux 32 bit. 

Does it work OK if you `meteor reset`? (If you don't want to do that I guess you could copy your `.meteor/local` before doing it and put it back afterwards)

**Comment by scott-cornwell** [comment]
@tmeasday Well mine is actually failing with Unexpected mongo exit code 14. I have tried meteor reset, rm -r .meteor/local/db, updating to 1.4.0.1-rc.3, updating to meteor 1.4.1, nothing works. I just wiped my vagrant box and reinstalled everything, still exit code 14 :(

**Comment by tmeasday** [comment]
@scott-cornwell can you try running `mongod` directly out of the dev bundle? Something like 

```
~/.meteor/packages/meteor-tool/1.4.1/mt...../dev_bundle/mongodb/bin/mongod --dbpath /path/to/app/.meteor/local/db`

**Comment by scott-cornwell** [comment]
@tmeasday I get this:

`2016-08-24T20:13:23.738+0000 I CONTROL  [initandlisten] MongoDB starting : pid=16987 port=27017 dbpath=/var/www/import/.meteor/local/db 64-bit host=ubuntu-14
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] db version v3.2.6
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] modules: none
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] build environment:
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten]     distarch: x86_64
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2016-08-24T20:13:23.739+0000 I CONTROL  [initandlisten] options: { storage: { dbPath: "/var/www/import/.meteor/local/db" } }
2016-08-24T20:13:23.759+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2016-08-24T20:13:23.789+0000 E STORAGE  [initandlisten] WiredTiger (22) [1472069603:789792][16987:0x7f2d6b3fccc0], connection: /var/www/import/.meteor/local/db/: directory-sync: fdatasync: Invalid argument
2016-08-24T20:13:23.791+0000 I -        [initandlisten] Fatal Assertion 28561
2016-08-24T20:13:23.791+0000 I -        [initandlisten]

***aborting after fassert() failure`

It's not a huge project and I can create a new 1.4.1 project just fine so I think I may just try manually copying code over to the new project and fixing dependencies as needed. If this is an actual bug though hopefully that error helps. I would still be interested in anything you find or if I can try anything else to give you more information, but don't sweat about it too much. Thanks!

**Comment by tmeasday** [comment]
@scott-cornwell sounds like perhaps this problem? http://stackoverflow.com/questions/35005560/mongodb-not-working-in-vagrant-centos-box

**Comment by scott-cornwell** [comment]
@tmeasday It is in a shared folder, along with the rest of the Meteor project, however my working new Meteor project is also in that same shared folder. Could be permissions though, the broken one is owned by user "vagrant" and the one that works is owned by "root". Haven't had a chance to mess with it too much, but I can't chown to root for some reason :/
