### ISSUE TITLE
[IOS][1.3+] WKWebView terminated [White Screen of Death] - kills Geofence events

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/meteor#7590]
When WkWebview is terminated because the device is low on resources the app is no longer running and components like Geofence events are killed along with it.

Reference:  [[IOS] [1.3] White Screen Of Death ... #7018](https://github.com/meteor/meteor/issues/7018) 
  pmwisdom commented on May 12 - 
"apple has basically said its a bug in the WebView. Here's an issue along the same lines on the plugin page:" - [Telerik#41](Telerik-Verified-Plugins/WKWebView#41)

I have added the Fix that recovers the app on open, but when the app is killed the geofences that were added, no longer trigger the transition event which allows me to call a method to track Exits and Enters from the user's device. This was working perfectly on 1.2.1 I had no issues for months. 

I am using:
- Meteor 1.3.5.1
- cordova-plugin-geofence@0.6.0
- cordova-plugin-wkwebview-engine@https://github.com/apache/cordova-plugin-wkwebview-engine.git#815ed0741b9ae30b343d6429bd8ff2ad37ec5790
  (Web View Fix)

**Comment by Wade-BuildOtto** [comment]
I think some think that this issue is resolved with this fix but its not the app still dies limiting anything from being run after its closed.

There must be a lot of apps effected by this issue.

**Comment by anymos** [comment]
+1

Very Annoying bug ...

Meteor 1.3 was supposed to fix the white screen of death by having a better HCP process. 

Finally, despite the effort put in the HCP we still have a white of death.

My customers do not care that the root cause is different, from their point of view this issue is still alive after more than one year ...

**Comment by anymos** [comment]
I am actually wondering, given the number of bug that wkwebview (https://issues.apache.org/jira/browse/CB-11885?jql=project%20%3D%20CB%20AND%20labels%20%3D%20wkwebview-known-issues)

Would it be possible to desactivate it and be back tothe old way ? even if itmeans no more HCP ?

Finally, the stability of an app is what most of the users care ...

**Comment by NawazKhanMd** [comment]
do we need a virtual host to run my meteor app on mobile?

cuz am running meteor run android-device -p MyIp:3000 --mobile-server virtualHostIpToWhichMobileIsConnected:3000

this gives me a blank screen

am i doing it wrong pls Reply :)

**Comment by AshHimself** [comment]
@Wade-BuildOtto - did you have find a resolution for this? I am running gps tracking in the background and my app looks to be crashing randomly and for the god of me can't resolve the issue.

**Comment by Wade-BuildOtto** [comment]
No this is still an outstanding issue with Cordova/IOS/Meteor

**Comment by macrozone** [comment]
We also face this problem on two apps on IOS. We are using a geotracker plugin: https://github.com/transistorsoft/cordova-background-geolocation-lt
but no geofence, only tracking.

- We experience that the app does not resume, when beeing in the background for a while. It then shows the white html page. It happens while the tracker is running and while its not running.
It always starts properly on a cold-start of the app, so killing the app and restarting is the only way to recover from this

- It seems that the local webserver has been crashed in this situation. I therefore applied this fix: https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25 but it does not solve the problem, but introduce another one that assets can't be loaded anymore on resume (from public directory).  See also https://github.com/meteor/meteor/issues/7018#issuecomment-299422580

I don't know how i should approach this problem, its really hard to reproduce and I already spent days to find out what's going on.  

I also don't know the root case. I heard that ios might kill the app, so my question is why ios is killing my app in the first place. And why this leads to a state where the app can't recover.

**Comment by AshHimself** [comment]
@macrozone - are you using iron-router and the accounts package? I found that my app was crashing on resume (white screen) and getting a route not found for a token page that does not exist. I have yet to invest time in resolving this nor do I know if this is the root cause. Happy to collaborate together to resolve this as this is a major show stopper for me.

**Comment by macrozone** [comment]
@AshHimself: thank you for your input, but that's not the issue (i am using flow router), i think you should see some logs on the ios inspector (you can use safari to see the console.log from the webview)

It does not happen on every resume on my apps, it happens if the apps has been in the background for some time. 

I also like to collaborate to resolve this huge issue, but i think we need help from mdg o this and someone with a good knowledge about the cordova integration.

there are so many layers where things can go wrong, it seems to be a bug with the local webserver on the cordova apps (Which adds a opaque-layer of more complexity, which mdg should have avoided in my opinion).

**Comment by macrozone** [comment]
@Wade-BuildOtto  can you try to apply https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30  and check if this fixes your issues?

**Comment by Wade-BuildOtto** [comment]
I am calling this solved with meteor/cordova-plugin-meteor-webapp#30

cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a

This has recovered that app every time, no issues same day, 1 day, and 2 days of termination the app opened every time,

**Comment by abernix** [comment]
Fantastic news, @Wade-BuildOtto!  (And thanks, @macrozone!) I'll pickup conversation in the issue you linked to to hopefully move that along to a release.
