### ISSUE TITLE
1.4.1 Extracting lasts forever

### ISSUE THREAD

**Issue by morwalz** [meteor/meteor#7688]
I tried to install meteor on another system. Installation go well. then i copied my project and i am running meteor run but 
" Extracting meteor-tool@1.4.0-1" it is happening forever. then i tried to update version number to 1.4.1 and run again "meteor run". Now i do not need to install 1.4.0.1 so it worked but got stuck on extracting on other modules. 

Possible reasons can be extraction program of this is release is faulty. this is urgent please someone suggest a solution or how can i download 1.4.0.1 release of meteor directly.

**Comment by Themandunord** [comment]
I'm facing the same problem.
![image](https://cloud.githubusercontent.com/assets/2819925/17839265/6ea1e298-67e3-11e6-8841-e66363276b67.png)

3 hours and nothing happens... I tried to restart but it doesn't work.

I try a meteor reset, an uninstallation of meteor... nothing...

I see that the .meteor folder size is increasing, but very slowly...

I'm on Windows 10

**Comment by laosb** [comment]
Do you have old versions of `tar` or `7z` in your `PATH`? If so, install a new version of tar/7z (or even don't install at all since meteor will try a js-implementation of tar)  and remove the old version. This might be related to #7689 .

**Comment by Themandunord** [comment]
I reinstall 7z yesterday, but it's still the same issue.
I look at my PATH this evening and I'll retry this solution.

**Comment by morwalz** [comment]
same case for me. i tried without 7z and with latest 7z it is still not working.

**Comment by morwalz** [comment]
@laosb any quick help ? i am like stuck on this.

**Comment by jalalat** [comment]
i am also facing the same issue. Please help.

**Comment by Themandunord** [comment]
I try in windows 7 and windows 10 without any workaround...

I don't have tar or 7z in my PATH.

**Comment by laosb** [comment]
So that was not related to #7689. Not sure what was happening if 7z itself works fine. @benjamn I guess this is in your realm?

**Comment by joelviel** [comment]
I have the same issue (Win10 64-bit Home). Endless extracting operation!
![endless](https://cloud.githubusercontent.com/assets/2602237/17933085/f473c462-6a3c-11e6-8852-77da43852b52.PNG)

_tar is not in my PATH_

**Comment by bhawani21** [comment]
I am also facing this issue. I am completely stuck. any helps on this ?

**Comment by jalalat** [comment]
i do not know whether it is the right solution or not. I checked my task manager when extraction was in progress and i saw my antivirus was scanning and using a lot of memory. I immediately disabled it. Somehow it worked.
(NOT AN EXPERT)

**Comment by jalalat** [comment]
and use --patch option as there is a patch 1.4.1.1 now

**Comment by joelviel** [comment]
Actually the extraction operation was not endless for me, just insanely long (more than 30min).

**Comment by ManuelDeLeon** [comment]
After completely removing Meteor with a 3rd party uninstaller, it doesn't take forever anymore, but it still takes a LONG time to do anything. By anything I mean create a new project, add a package, update an existing project, etc. By long I mean 30-60mins.

Right now Meteor is unusable in Windows.

**Comment by morwalz** [comment]
it is still not working for me. I tried to keep it open for two days nothing happened. It does create new project, but does not install 1.4.0.1 stuck there.

**Comment by AliMor** [comment]
@morwalz use 

> where tar

 command find all instance tar files and remove them. I had the same issue couple of days ago. I also, remove old version of 7z from my PC. I needed 7z so I installed new version (not necessary for  Meteor) problem gone.

**Comment by redsummit** [comment]
I am seeing the same behavior on Max OS X. Any meteor (1.4.0.1) command that downloads files takes forever to run. Using bsdtar 2.8.3.

**Comment by Nakroma** [comment]
Problem for me too. Can't add packages because weird extraction errors, and reverting doesn't work because it doesn't unpack meteor-tools. My friend also can't update meteor.

**Comment by logvik** [comment]
+1

**Comment by suits-at** [comment]
+1

**Comment by bouchepat** [comment]
Same problem. Tried to do a simple meteor update as of last tuesday and stuck on extracting meteor-tool@1.4.1_1...
On windows 7

**Comment by stefanholzapfel** [comment]
Hi!

I had the same issue. Obviously it is a problem with tar extractor.

I installed the newest 7zip and renamed the tar.exe in my GIT program folder ("where tar" command in cmd revealed, that somehow that exe was associated with .tar archives) to tar.exe.old.

Don't know which action solved the problem, but now extraction works.

**Comment by NenadPavlov** [comment]
Just to confirm as well it was an issue with tar that came with old version of git (which meteor was using for extraction). In my case I have upgraded git and tar disappeared. If I get it correctly instance of 7zip comes along with meteor update files and it is used for extracting. Everything went well reasonably quickly.

**Comment by morwalz** [comment]
i confirm this as well. it is due to tar.exe in git folder. I renamed it and it worked for me.

**Comment by michaeldewal** [comment]
This is not working for me.
I had no tar.exe in the first place and the latest 7zip was already installed. I reinstalled meteor as well after that, but still my installation is stuck on extracting templating@1.1.9 even after 3 hours nothing happens.

**Comment by kluch** [comment]
Having the exact same problem. 

Its stuck on "extracting meteor-tool@1.3.4_1..."

![extracting error](https://cloud.githubusercontent.com/assets/574399/18248601/8b651796-7379-11e6-80db-32f34587d450.png)

Windows 10
No 7zip on the machine
where tar returns no results

**Comment by stefanholzapfel** [comment]
Try installing the newest version of 7zip. (It got a tar extractor included and meteor seems to use it if available..)

Did you wait for a while? In some cases the extraction takes really long, like 15minutes...

**Comment by kluch** [comment]
I left it over night, nothing happened. 

I will try installing the newest version of 7zip.

Thanks.

**Comment by onedr0p** [comment]
I'll jump in here with my solution. Inside my project directory I deleted my `.meteor/local` directory and renamed the `versions` files to `versions.bak` and re-ran `meteor update`

**Comment by carsonburr** [comment]
@onedr0p This worked for me. I was getting hung up at extracting templating@1.0.9

**Comment by michaeldewal** [comment]
I just installed Ubuntu and got rid of all the errors that way.

**Comment by ManuelDeLeon** [comment]
@laosb @benjamn 
What's the official solution to this? I renamed `tar.exe` and it's still stuck on `Extracting templating@1.1.9...`

**Comment by onedr0p** [comment]
@ManuelDeLeon did you try what I posted?

**Comment by ManuelDeLeon** [comment]
@onedr0p 

Here's what I got when I tried that:
```
>meteor update
=> Errors while initializing project:

While checking for semantic:ui-css@2.2.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.
```

**Comment by onedr0p** [comment]
Well the other problem went away.. I am not sure what is going on there. Did the publisher remove the package from atmosphere?

**Comment by ManuelDeLeon** [comment]
It works now. I had to force a prior version of some packages.

**Comment by bastiW** [comment]
@michaeldewal 
The command 
where tar also had no result so after installing git and 7zip it was working.

**Comment by pgiani** [comment]
Here is my solution download the 32bit version of 7Zip and install it

copy the file:
 7z.exe 

from:
C:\Program Files (x86)\7-Zip\

And replace it where meteor has its version ( while meteor add is running open TaskManager right click on the 7z.exe file under Bacground processes  then choose open file location), in my case the path is:

C:\Users\--- YOUR USER NAME ---\AppData\Local\.meteor\packages\meteor-tool\1.4.2_1\mt-os.windows.x86_32\dev_bundle\bin

stop meteor run meteor add or updated whatever is the command where you had the problem

**Comment by suits-at** [comment]
This solution finally worked for me too, thanks @pgiani !!!

**Comment by abernix** [comment]
@pgiani & @suits-at Thanks for reporting this information.  I'm curious if you could help debug this a bit more.  Meteor is supposed to ship with the 32-bit version of 7-zip, so it would be nice to fix this for other users...

* Can you "break" it again by doing a clean reinstall of Meteor?
* What is the output of the following command, run from _Command Prompt_ (`cmd.exe`):

        systeminfo | findstr /C:"OS"
* If you do the same thing you described with this install: http://www.7-zip.org/a/7z1602.msi _(the previous "1602" build – the version on their site right now is "1604")_.  Does it work?
* Now, what if you try with http://www.7-zip.org/a/7z1604.msi (the latest)?

**Comment by pgiani** [comment]
systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Award Software International, Inc. F7, 6/23/2010

Going to to a clean install and I will report back with the results, I gave up on windows I installed Ubuntu on a VM and using it now, too many problems with npm install also

**Comment by mhlmhl** [comment]
I have been using Meteor 1.4.2.2 on my Windows 8.1 64-bit system.  Today I noticed a message saying that " A patch (Meteor 1.4.2.3) for your current release is available!", so I did "meteor update --patch".  Now I regret that, because the update is stuck on "extracting meteor-tool@1.4.2_3....".

Per the discussion on this issue, I've tried replacing the version of 7z.exe that was executing (in the Meteor 1.4.2_1 folder) with the version that I installed on my system, and restarted the patch installation.  After 30 minutes, it's still extracting...

**Comment by mhlmhl** [comment]
Also, ctrl-c does not work anymore.  I had to close my entire command shell to stop it.

**Comment by ManuelDeLeon** [comment]
@mhlmhl Unfortunately the replacing 7z.exe only works if you already have the version of Meteor installed. It still takes a little bit less than forever if you're installing a new version for the first time.

**Comment by mhlmhl** [comment]
You're right.  I left it running when I went to bed, and the new version was installed when I returned this morning.

Suggestion: users should be given some indication of how long it may take to install a new version.

**Comment by BadOPCode** [comment]
Alright... I'm running Arch Linux everything is up to date with my server and it wasn't working.  Arch tends to use bleeding edge.  So the version of 7z is not the problem.  I did install NVM and rolled back my system version of Node (7.x) to 6.9 LTS.  Still was having the same issues.  So I went deeper into this.  The problem is actually that Meteor is trying to download/extract to /tmp.  >.>  Really guys?
Okay to pin this out further... on majority of systems the /tmp directory is made by tmpfs which is a RAM drive system that by default sets the max size to half that of your system RAM total.  I've got a large VM running which is a whopping 1G RAM making my tmpfs 512M.  So downloading a bunch of archives and their dependencies and than trying to extract them all in the same place ... surprise surprise ran out of room on the tmpfs.   There is a solution for Linux is to make a tmp directory in your home directory and add this to your environment ```export TMPDIR=$HOME/tmp```  I haven't tested it because through fiddling with the issue I managed to get log jam broke up and the packages installed.  But guys you could fix the majority of the problems if you did nothing else but downloaded archives somewhere in the .meteor directory.

**Comment by meteorplus** [comment]
Working solution! just delete the 7z shipped with meteor tools

from here

win 10. I fixed:
in \AppData\Local.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin
should delete 7z.exe

and it will work!

seems there is an issue with this running on 64bit machines and shouldn't be shipped with meteor  tools!

thanks

**Comment by abernix** [comment]
I'm going to reopen this as it seems there is still an issue here and I don't want this to get lost.  It sounds like Meteor might need to bundle a different version of 7z.

If anyone wants to review what currently happens the code which packages the 7zip within the `dev_bundle` (which you're all modifying) is [located here](https://github.com/meteor/meteor/blob/release-1.4.2.2/scripts/generate-dev-bundle.ps1#L38-L46).

I'm curious if this is just a problem with the 7z1602.msi (a newer version is available).  If someone could investigate, it would be much appreciated!

**Comment by spawn-guy** [comment]
just replaced "bundled" 16.02 with "official" 16.04-x64. 
- downloaded `7z1604-extra.7z` 
- extracted the x64 version from the x64 folder
- renamed to 7z.exe and put it into the appDtata\local........\bin folder

after 4 hours of "waiting" - everything got completed within minutes.
hope it helps

**Comment by abernix** [comment]
@spawn-guy Despite the fact that you may be on a 64-bit Windows, do you mind trying the 32-bit version of 7z1604 and see if the improvements are also noticeable?  If I'm not mistaken, `meteor-tool` currently only builds a 32-bit Windows version for maximum compatibility.  If the 7z1604 32-bit also shows the improvement you've indicated, then the version of 7z which is bundled with Meteor can easily be bumped.  If it's still slow, then the (correct) solution might be a bit more complicated (e.g. a 64-bit exception or a separate build).

**Comment by mgleed** [comment]
Running Windows 10. @meteorplus 's solution from 12 days ago worked for me (deleting 7z.exe from meteor_tool)

**Comment by ltung** [comment]
@mgleed  & @metrorplus, Thanks for the idea. Instead of deleting 7z.exe (in case of breaking something), I just copied my newest version of 7z.exe from "c:\Proggram Files\7-zip" into "AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin" and everything seems working.

**Comment by bastiW** [comment]
@abernix

I can confirm that 7z1604 32bit is working on 64bit Windows 10

**Comment by jeffersonDesouza** [comment]
The **Download 7-Zip 16.04 (2016-10-04) for Windows:** version worked to me.

**type**: .exe
**Windows**:	64-bit x64
**Description**: 7-Zip for 64-bit Windows x64 (Intel 64 or AMD64)

**Comment by abernix** [comment]
@bastiW Thank you for that confirmation and taking the time to test it.  I've gone ahead and bumped the version of 7-Zip to the 32-bit version 1604 in https://github.com/meteor/meteor/commit/0dbfda35e66bdf38bce84ca8eaab11a2d5d0dbff and published it in `1.4.3-beta.3`.

**Unfortunately**, due to the way that updating to a new version works and the implications of the the full effects of this fix will not be seen until the next release AFTER Meteor 1.4.3 becomes recommended.  This is due to the fact that the previous version must extract the new version.  I'll leave this open until that can be confirmed.

**Comment by benjamn** [comment]
This is going to be [included](https://github.com/meteor/meteor/pull/8306/commits/38dd26ab6494b72df9e9769770e9aa5b6597f065) in a small patch release ([Meteor 1.4.2.4](https://github.com/meteor/meteor/pull/8306)), which won't help with updating to Meteor 1.4.2.4 but will help when you later update to 1.4.3 or later.

**Comment by gepolv** [comment]
Meteor 1.4.2.7 still cannot work.

**Comment by san2code** [comment]
Installed Meteor 1.4.3 after uninstalling previous version, still not working. waiting to finish Extracting for more than 30 minutes now.

**Comment by manuelro** [comment]
I have a 32 GB RAM Windows computer, and even though the process hangs and the fans start working like crazy. Meteor version `1.4.4.1`. I did remove the 7z file provided by Meteor and replaced it with a freshly installed 7z from my local folder. Nothing seems to work. Although it will eventually install the new version, it's taking an enormous amount of time and resources.

**Comment by BadOPCode** [comment]
RAM is not a variable to this problem in Windows.  The RAM drive (tmpfs) problem is something that can happen in *nix.  Fans kicked on signifies that there is intense amount of CPU usage going on.   Maybe snoop to see what processes are taking so much resource when it's installing.  Just shooting blindly in the dark at the problem as I run Meteor in Linux... Sounds like something trying to do a ridiculously big recursion.  It is finishing, but it's taking forever and gobbling resources.  NPM has been known to lose it's mind in recursion when it's trying to solve dependencies.  Sorry I can't be more help.

**Comment by spawn-guy** [comment]
Disable Windows Defender (or the AntiVirus that you use) while installing modules - It'll drastically speed up things!

Aaand there is nothing else to fix in current process, as Defender does what it needs to do - check the JS files and binaries for malicious code from an "unknown" source ( read _the internets_). And there are TONS of these files in distros.

7z distribution is fixed(to my knowledge) with official sources. High CPU load is doe to antivirus.

Don't forget to turn it ON afterwards. Or, well, just wait

**Comment by spawn-guy** [comment]
And another issue with LongPaths on Windows10 can be fixed with group Policies https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx#maxpath

This, Imo, is worth mentioning in Readme

**Comment by meteorplus** [comment]
@spawn-guy I don't use an anti virus and I have a gaming workstation :p this is due to the build taking too long due either to tmp folder full or some packages are not downloaded and keep getting re-downloaded and so on... sometimes it happens on linux but I found that it is related to the tmp folder being full so I clear it and it's good to go!

otherwise I will have to meteor reset the app to get it working again!

so I think this is just related to the build path! (needs some checking and validations)

**Comment by toledoroy** [comment]
Try to turn off Windows Defender

**Comment by muninn9** [comment]
Freeing up disk space worked for me

**Comment by llermaly** [comment]
After disabling windows defender instantly worked.

Windows key + Windows defender

Go go Windows defender security center
Click "Antivirus protection and against threats"
Configure antivirus and threat protection
Disable everything

good luck

**Comment by stevenqzhang** [comment]
I had a similar issue for 1.5.2. The extraction process just took super long (30+ min), and the lack of the spinner working led me to (wrongly) believe the extraction process was stalled

**Comment by hershko765** [comment]
also had this issue and i also tought its stuck, but its mostly just takes super long since the tar file is extracting more or less extracting the globe, if your not sure you check if this folder is growing while the process is extracting:
C:\Users\<USER>\AppData\Local\.meteor
just verify that the process is not stuck and the folder size is growing

**Comment by afriC84** [comment]
**This fixed the problem for me:**
(I am running Meteor 1.6.1 on a Windows 10 machine)

1. Update git
2. `choco uninstall meteor`
3. check that the `%appdata%/Local/.meteor` folder is removed
4. remove the `[project-folder]/.meteor/local` directory
4. remove the `versions`-file in `[project-folder]/.meteor`
4. remove the `[project-folder]/node_modules` directory
4. `choco install meteor`
4. in the project-folder, run `meteor npm install`
4. in the project-folder, run `meteor`
4. wait, see and celebrate

Good luck ;-)

**Comment by yozawiratama** [comment]
thanks @llermaly it work, and now everything work fast.

when you run meteor command dont forget to disabled windows defender, and activate it when meteor ready

**Comment by iamzee** [comment]
I stopped **windows defender** and it worked for me....
