### ISSUE TITLE
livedata tests (ddp-client) are missing reverse.meteor.com

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#8092]
In `ddp-client` tests there is a test which connects to `reverse.meteor.com`. It cannot connect anymore because it seems that app was removed. The test does not fail, but it does also not test anymore anything.

Probably `reverse.meteor.com` app should be redeployed to `meteorapp.com` and test updated.

**Comment by mitar** [comment]
There is also `subdomain.meteor.com` missing. And something which is `ddp--****-foo.meteor.com`? Is this even a valid domain?

**Comment by glasser** [comment]
The `*` thing is a feature we implemented for DDP.connect where the client will replace the `*`s with random digits. This was to work around browser per-hostname connection limits: you'd only be able to have so many tabs open to your app before the long polling stopped working.

Your server would have to be able to route those connections to the right place; the old free hosting did but Galaxy does not.  (The hosting service would set $DDP_DEFAULT_CONNECTION_URL to an URL like that.)  I believe this is mostly irrelevant these days because Websockets don't have the same low connection limits.

This is documented in translateUrl in stream_client_common.js.

**Comment by mitar** [comment]
[True](https://cs.chromium.org/chromium/src/net/socket/client_socket_pool_manager.cc?q=WEBSOCKET_SOCKET_POOL&sq=package:chromium&type=cs&l=29). 256 connections in Chrome, 200 in Firefox.

Do you still have those (other) apps from meteor.com? Could you deploy them to meteorapp.com?

**Comment by glasser** [comment]
The source code to reverse.meteor.com has been lost, but it was literally just an app with a single `Meteor.methods` call identical to the one in the test without the `+ " LOCAL"`.  You're welcome to deploy it :)  I think subdomain.meteor.com is just an example for URL parsing.

**Comment by mitar** [comment]
I have used all my free meteorapp.com containers. :-( I think this should probably be deployed and fixed by somebody from MDG.

**Comment by hwillson** [comment]
This is still an issue (see the [`livedata connection - reconnect to a different server`](https://github.com/meteor/meteor/blob/0d7ce023e0902094305960fd5d1268e21702a9f3/packages/ddp-client/livedata_connection_tests.js#L1611) test).

@benjamn @abernix Since this can really only be handled by MDG (if a `*.meteor.com` or `*.meteorapp.com` domain is to be used), maybe this issue should be moved internally and closed here?

**Comment by abernix** [comment]
I've re-deployed reverse.meteor.com on an MDG account per the description above.

@mitar Can we fix the test so it actually fails?

**Comment by mitar** [comment]
I have no idea what this test does. I just noticed it. Probably @glasser is a better person here to answer this.

**Comment by glasser** [comment]
The test validates that if you call reconnect with a different URL, you actually end up connected to a different server. I don't remember why we cared about this functionality 4+ years ago.  If it were trivial to just start a second server within the process (if Meteor were less full of singletons) it would be much easier to test.

**Comment by abernix** [comment]
Running the second server seems fine, but it seems the test should be fixed so that if `reverse.meteor.com` is down (as it has been for a long time), that the test actually fails. I haven't actually looked at the code yet (and won't be able to until later) so I was just asking if @mitar thought the test could be fixed.

**Comment by hwillson** [comment]
PR https://github.com/meteor/meteor/pull/9416 adjusts the `livedata connection - reconnect to a different server` test so that it will properly fail if `reverse.meteor.com` goes down again.

**Comment by abernix** [comment]
For the record, the app repository for the deployed `reverse.meteor.com` is here: https://github.com/meteor/livedata-reverse-testapp
