### ISSUE TITLE
[1.4.2.6] Can no longer build or deploy

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#8370]
I get build errors when I try to run `meteor deploy` (see at the very bottom, it's quite long). To troubleshoot, I tried `meteor reset` and that didn't help clear it up.

I might try to roll back to 1.4.2.3. Is there some official way to do that, or can I just edit `.meteor/release` and change it to 1.4.2.3 and then run meteor?

```
Errors prevented deploying:
While minifying app code:
eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:1547:18: SyntaxError: Unexpected token: operator (>)
at new JS_Parse_Error (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:1547:18)
at js_error (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:1555:11)
at croak (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2094:9)
at token_error (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2102:9)
at unexpected (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2108:9)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2635:9)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2869:32)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at vardefs (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2514:56)
at const_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2535:27)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2273:30)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at block_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2434:20)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2406:25)
at function_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2412:15)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2627:24)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2696:25)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2621:35)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2696:25)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2621:35)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2696:25)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2621:35)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at expr_list (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2646:24)
at subscripts (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2780:30)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2633:20)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at vardefs (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2514:56)
at var_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2527:27)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2270:30)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at block_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2434:20)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2406:25)
at function_ (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2412:15)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2627:24)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at expr_atom (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2613:26)
at maybe_unary (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2797:19)
at expr_ops (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2832:24)
at maybe_conditional (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2837:20)
at maybe_assign (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2861:20)
at expression (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2880:20)
at simple_statement (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2319:55)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2200:24)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2141:24)
at eval (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2909:23)
at Object.parse (eval at <anonymous>
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:1:0),
<anonymous>:2920:7)
at addFile
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:72:33)
at
/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:81:17
at Array.forEach (native)
at exports.minify
(/Users/samh/.meteor/packages/standard-minifier-js/.1.2.2.52ezw9++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/tools/node.js:79:26)
at packages/minifyStdJS_plugin.js:55:16
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle
(packages/minifyStdJS_plugin.js:50:9)
```

**Comment by benjamn** [comment]
Editing `.meteor/release` will work, though `meteor update --release 1.4.2.3` should also work. You might also try Meteor 1.4.2.7 (out today).

I would also recommend removing `/Users/samh/.meteor/packages/standard-minifier-js/` completely, just to be sure it gets re-downloaded/built.

**Comment by ffxsam** [comment]
Tried 1.4.2.7 and 1.4.2.3. No go. Very strange.. I don't remember updating any packages, but apparently something changed. I'll remove the folder you mentioned. Failing that, I'll clear out the entire `.meteor` folder except for the bare necessities.

**Comment by ffxsam** [comment]
That didn't work either. 😢  I even tried `rm -rf ~/.meteor` to start completely over, and I still get the same errors.

**Comment by ffxsam** [comment]
If it helps, below are my Meteor & NPM packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.14                   # The database Meteor supports right now
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.1                 # Meteor's client-side reactive programming library

es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.6.1              # Enable ECMAScript2015+ syntax in app code

react-meteor-data
jagi:astronomy
jagi:astronomy-timestamp-behavior
jagi:astronomy-softremove-behavior
random@1.0.10
static-html@1.1.12_1
kadira:flow-router
reactive-dict@1.1.8
universe:i18n
babrahams:constellation
mdg:validated-method
accounts-password@1.3.3
edgee:slingshot
mikowals:batch-insert
standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
reywood:publish-composite
practicalmeteor:mocha
hwillson:stub-collections
email@1.1.18
reactive-var@1.0.11
c9s:scss
http@1.2.10
meteorhacks:picker
session@1.1.7
meteorhacks:kadira
shell-server@0.2.1
```

```
  "dependencies": {
    "@slack/client": "^3.7.0",
    "aws-sdk": "^2.4.2",
    "bcrypt": "^0.8.7",
    "body-parser": "^1.15.2",
    "bufferutil": "^2.0.1",
    "change-case": "^3.0.0",
    "chart.js": "^2.5.0",
    "classnames": "^2.2.5",
    "cron-parser": "^2.2.0",
    "eslint": "^3.15.0",
    "filesize": "^3.3.0",
    "formous": "^0.9.2",
    "immutable": "^3.8.1",
    "intercom-client": "^2.8.5",
    "invariant": "^2.2.1",
    "keycode": "^2.1.2",
    "lodash": "^4.13.1",
    "material-ui": "^0.17.0",
    "meteor-node-stubs": "^0.2.3",
    "meteor-react-prebind": "^1.0.2",
    "moment": "^2.13.0",
    "moment-timezone": "^0.5.10",
    "radium": "^0.18.1",
    "react": "^15.1.0",
    "react-addons-pure-render-mixin": "^15.1.0",
    "react-addons-shallow-compare": "^15.3.2",
    "react-addons-transition-group": "^15.3.2",
    "react-chartjs-2": "^2.0.0",
    "react-delay": "0.0.3",
    "react-dom": "^15.1.0",
    "react-intercom": "^1.0.11",
    "react-linkify": "^0.2.0",
    "react-markdown": "^2.3.0",
    "react-mixin": "^3.0.5",
    "react-motion": "^0.4.4",
    "react-mounter": "^1.2.0",
    "react-sticky": "^5.0.5",
    "react-tap-event-plugin": "^2.0.1",
    "rollbar": "^0.6.2",
    "shallow-equal": "^1.0.0",
    "shallowequal": "^0.2.2",
    "stripe": "^4.9.1",
    "utf-8-validate": "^3.0.1",
    "validator": "^6.0.0"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.34.0",
    "aws-sdk": "^2.10.0",
    "babel-eslint": "^7.0.0",
    "babel-jest": "^18.0.0",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-root-slash-import": "^1.1.0",
    "babel-runtime": "^6.11.6",
    "enzyme": "^2.7.1",
    "eslint": "^3.15.0",
    "eslint-plugin-flowtype": "^2.3.0",
    "eslint-plugin-react": "^6.0.0",
    "flow-bin": "^0.39.0",
    "idgen": "^2.0.2",
    "jest": "^18.1.0",
    "json-loader": "^0.5.4",
    "random-word-generator": "^0.9.9",
    "react-addons-perf": "^15.1.0",
    "react-addons-test-utils": "^15.4.2",
    "react-test-renderer": "^15.4.1"
  }
```

**Comment by abernix** [comment]
@ffxsam It's bizarre that you just started getting this specific error because of just a change in Meteor.  Are you sure there were no NPM packages that were updated as well?  While `meteor update --release <version>` will generally work, using version-control is generally a better way to ensure a proper downgrade.

I'm inclined to believe this might have something to do with a third-party NPM which might be using modern ECMAscript constructs that should be getting transpiled (by the package author) but aren't.  You should be able to reproduce this problem locally by using `meteor --production` (which will use production minifying).  Unfortunately, the error message from UglifyJS is, well, particularly ugly (see #5517).

Maybe check my comments in https://github.com/meteor/meteor/issues/8020#issuecomment-265758830 (And the rest of issue too)

**Comment by ffxsam** [comment]
I'll try rolling back to a known good version and see what happens. If that works, I'll use `git bisect` to track down the problem (if it is indeed a rogue package).

Thanks!

**Comment by benjamn** [comment]
UglifyJS is becoming more and more finnicky as it falls behind new ECMAScript features, unfortunately.

One way to debug this issue is to install `standard-minifier-js` as a local package:
```sh
cd path/to/your/app
mkdir -p packages
cd packages
ln -s path/to/checkout/of/meteor/packages/standard-minifier-js ./
```
Now you can edit `standard-minifier-js/plugin/minify-js.js` to produce better debugging output, perhaps by putting a `try`-`catch` block around [this line](https://github.com/meteor/meteor/blob/005c521f54887c418204707e7bbb33f926a6b0e3/packages/standard-minifier-js/plugin/minify-js.js#L41):
```js
allJs += UglifyJSMinify(file.getContentsAsString(), minifyOptions).code;
```
Note that `file.getPathInBundle()` is the name of the file.

**Comment by benjamn** [comment]
(I know that isn't super easy, but it's probably easier than putting together a reproduction.)

**Comment by ffxsam** [comment]
Reporting in. I reverted to a commit that was definitely working, because it was built & deployed.. and I still get the error. Something is really wrong here.

I tried your suggestion of symlinking `standard-minifier-js` to `packages/`, but for some reason Meteor isn't seeing it there. It's still using the one in `~/.meteor/packages`. Then I noticed the actual package contents are in `~/.meteor/packages/standard-minifier-js/1.2.2`, so I symlinked that instead. Still no go:

```
=> Errors while initializing project:

While selecting package versions:
error: No version of standard-minifier-js satisfies all constraints: @1.2.1,
@=0.0.0
Constraints on package "standard-minifier-js":
* standard-minifier-js@1.2.1 <- top level
* standard-minifier-js@=0.0.0 <- top level
```

**Comment by ffxsam** [comment]
I edited the JS file as is in `~/.meteor/packages` to insert a try/catch block. This error got dumped out:

```
JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: operator (>)',
  filename: 0,
  line: 423994,
  col: 33,
  pos: 51445351,
```

But it doesn't help much (line 423994!).

**Comment by ffxsam** [comment]
Got it!

I'm always wary of npm packages that have to compile (i.e. node pregyp). This isn't the first time I (or others) have run into problems, like with bcrypt 1.x.

In this case, `utf-8-validate` is the culprit. Here's the output from installing the latest version (3.0.1). Note that 2.0.0 worked totally fine.

```
> utf-8-validate@3.0.1 install /Volumes/SuperData/Sites/harris-partners/harris/node_modules/utf-8-validate
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds/utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/samh/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.1-utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/utf-8-validate/releases/download/v3.0.1/utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/websockets/utf-8-validate/releases/download/v3.0.1/utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info downloading to @ /Users/samh/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.1-utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz.72182-c9884cdc.tmp
prebuild-install info renaming to @ /Users/samh/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.1-utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info unpacking @ /Users/samh/.npm/_prebuilds/https-github.com-websockets-utf-8-validate-releases-download-v3.0.1-utf-8-validate-v3.0.1-node-v46-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Volumes/SuperData/Sites/harris-partners/harris/node_modules/utf-8-validate/build/Release/validation.node
prebuild-install info unpack required /Volumes/SuperData/Sites/harris-partners/harris/node_modules/utf-8-validate/build/Release/validation.node successfully
prebuild-install info install Prebuild successfully installed!
wrote npm-shrinkwrap.json
harris@0.13.1 /Volumes/SuperData/Sites/harris-partners/harris
└─┬ utf-8-validate@3.0.1  invalid
  ├── (dependencies redacted)
```

And actually there's a second culprit package, `bufferutil`. Version 1.3.0 was fine, but version 2.0.1 is not. I need these because I use `@slack/client` in my app, which depends on `ws` which depends on the two aforementioned troublemakers.

**Comment by ffxsam** [comment]
On a semi-related note, bcrypt 1.0.2 now works great with Meteor (1.0.1 and earlier did not). I don't know if that was a bcrypt fix or something you guys did, but it works. 😄

**Comment by benjamn** [comment]
Ah yeah, that's probably due to https://github.com/meteor/meteor/issues/8136.

**Comment by ffxsam** [comment]
Ah, gotcha. Someone said Meteor 1.4.2.7 fixed this issue, but it seems that may not be the case?

**Comment by ntorgov** [comment]
Got same error in 1.4.2.7

> C:\Users\ntorg\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\163.12024.17\bin\runnerw.exe C:\Users\ntorg\AppData\Local\.meteor\meteor.bat --production
> Warning: The --production flag should only be used to simulate production
> bundling for testing purposes. Use meteor build to create a bundle for
> production deployment. See: https://guide.meteor.com/deployment.html
> [[[[[ C:\Users\ntorg\WebstormProjects\agroprint-crm ]]]]]
> 
> => Started proxy.
> => Started MongoDB.
> => Errors prevented startup:
>    
>    While minifying app code:
>    eval at <anonymous>
>    (C:\Users\ntorg\AppData\Local\.meteor\packages\standard-minifier-js\1.2.2\plugin.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\uglify-js\tools\node.js:28:1),
>    <anonymous>:1547:18: SyntaxError: Unexpected token punc В«(В», expected
>    punc В«:В»
>    at new JS_Parse_Error (eval at <anonymous>
>    (C:\Users\ntorg\AppData\Local\.meteor\packages\standard-minifier-js\1.2.2\plugin.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\uglify-js\tools\node.js:28:1),
>    <anonymous>:1547:18)
>    at js_error (eval at <anonymous>
>    (C:\Users\ntorg\AppData\Local\.meteor\packages\standard-minifier-js\1.2.2\plugin.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\uglify-js\tools\node.js:28:1),
>    <anonymous>:1555:11)

**Comment by abernix** [comment]
@ffxsam If I'm not mistaken, we can close this (so I'm going to do that :smile:).  You may want to try my `abernix:standard-minifiers-js` package from that issue to see if it allows you to continue merrily until UglifyJS gets caught up officially (the fix I've provided is actually a "harmony" branch of the usual Uglify package.  For what it's worth, I'm considering making a Google Closure Compiler plugin to bridge the gap here, but we should discuss that in the other issue...

Others (including @ntorgov): Please refer to https://github.com/meteor/meteor/issues/8020#issuecomment-265758830 which seems to be the actual issue here.  The issue isn't directly related to Meteor 1.4.2.7, but more than likely that there are some other dependencies of your project which have been updated since you updated Meteor last.  The linked issue has more information.

**Comment by ffxsam** [comment]
@abernix So the workaround for now is to either use your package or just keep the current versions of the two problematic packages in my project, correct?

**Comment by BTooLs** [comment]
Hello, I'm searching for a few hours how to fix these errors. I made the mistake not building the app and added lots of npm-packages, writing the code and now I face hundred of errors, with no line/file trace. 
There is a way on meteor 1.4.2.7 to disable/replace uglify.js? I don't know if the uglify comes before or after the babel, and if I can find the errors using manually uglify-js on the source files?

**Comment by ntorgov** [comment]
I'm using this elegant solution since 1.4.2.4. [#8020] Yep. I'm don't use the minification in production now :(
```
# standard-minifier-js@1.2.1           # JS minifier run for production mode. :(
# standard-minifier-js@1.2.2           # not works
# abernix:standard-minifier-js@1.2.2   # not works
```
https://github.com/meteor/meteor/issues/8020#issuecomment-265758830 didn't solve the problem for me. I have told about it here: https://github.com/meteor/meteor/issues/8020#issuecomment-276658980

**Comment by BTooLs** [comment]
I have the same error, because all the code is put in a big .js file, I cannot tell what file causes this
> SyntaxError: Unexpected token: name (
as here https://github.com/webpack/webpack/issues/2972 
As a temporary solution I disabled the standard-minifier-js, and added "babili" as a babel preset, but only minifies my app code, and does Not combines all the modules in 1 file. Found another problem too, meteor does not support babelrc environements yet, so I had to bypass that too.

**Comment by abernix** [comment]
As a stop-gap measure until this issue is resolved, I've updated my `abernix:standard-minifier-js` package to capture the specific location of the error in [this commit](https://github.com/abernix/standard-minifier-js/commit/b66bd7f6e481987aeaa68ccd5c8c0edfdd4004f3), by traversing the SourceMap decoration, when the error is captured within `package/modules.js` (the Meteor package which is a concatenated encapsulation of `node_modules` deemed necessary to ship to the client).

This should at least make it easier for developers to know _which_ dependency is using the newer ECMAScript language which UglifyJS does not understand and allow them to react accordingly.

@ffxsam The other option is to just remove `standard-minifier-js` entirely and forego minification for the time-being.  While not idea, I will point out that Meteor code uses Gzip compression in transit to the client so actual minification gains may vary.  This isn't to say that minification isn't valuable, but your mileage may vary and I'd encourage you to

**Comment by BTooLs** [comment]
tx @abernix with your version of the minifier the compiler works.

**Comment by ffxsam** [comment]
I'd also just like to thanks @abernix in general. You are a shining ⭐️  in the community. 😄

**Comment by abernix** [comment]
Until the next version of Meteor is released with Minifier improvements, I've just published `abernix:standard-minifier-js@1.3.19`.  It now uses the [`harmony-v2.8.15`](https://github.com/mishoo/UglifyJS2/tree/harmony-v2.8.15) branch of UglifyJS (opposed to `v2.7.5`) which has seen some active work in the past couple weeks which has remedied many of the failing [`test262` tests](https://github.com/tc39/test262) but still falls short of compliance ([here are the latest results](https://gist.github.com/avdg/023b7cbe3d6a5b5ad80fa77879576fdb)).  That said, UglifyJS is still [the fastest](https://github.com/babel/babili#benchmarks) minifier, even if it's not feature-complete with ES6.

If anyone has struggled with the official `standard-minifier-js`, or a past version of my `abernix:standard-minifier-js`, I'd be very interested in your feedback if this new version of my package improves/changes things for you.  Please do report back your findings!

**Comment by joedeveloper** [comment]
@abernix  fyi - I tried your 1.3.19 in an attempt to resolve: https://github.com/mapbox/mapbox-gl-js/issues/4359 - it did not resolve that particular issue. Is there a way to tweak the Uglify config?
