### ISSUE TITLE
1.5.2: "process out of memory" while building the app

### ISSUE THREAD

**Issue by maxnowack** [meteor/meteor#9075]
I've tried to upgrade to Meteor 1.5.2, but an error occurs while building my app. The error always occurs while building the app with heroku and sometimes locally. It seems, that it doesn't affect the `meteor test` command, since the error has never occurred on our CI (CircleCI).
Here's the stacktrace I've got, as the error has occurred locally:
````
<--- Last few GCs --->

  203313 ms: Mark-sweep 1361.2 (1454.1) -> 1359.6 (1454.1) MB, 1028.5 / 0 ms [allocation failure] [GC in old space requested].
  204285 ms: Mark-sweep 1359.6 (1454.1) -> 1361.2 (1454.1) MB, 972.1 / 0 ms [allocation failure] [GC in old space requested].
  205222 ms: Mark-sweep 1361.2 (1454.1) -> 1358.6 (1454.1) MB, 936.9 / 0 ms [last resort gc].
  206159 ms: Mark-sweep 1358.6 (1454.1) -> 1361.2 (1454.1) MB, 936.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3559ba437399 <JS Object>
    1: _serializeMappings(aka SourceMapGenerator_serializeMappings) [/Users/maxnowack/.meteor/packages/meteor-tool/.1.5.2.18kossj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map-generator.js:~285] [pc=0xb42eee0c538] (this=0x36fc05cfd7a1 <a SourceMapGenerator with map 0x9679e84ed99>)
    2: toJSON(aka SourceMapGenerator_toJSON) [/User...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
````

Initially I thought that the error was caused by the heroku buildpack which I'm using and I'm currently investigating with @abernix.
Since the error now also occurs locally, I'm pretty sure that it is more related to meteor than to the buildpack. As a reference, here's the link to the original issue: AdmitHub/meteor-buildpack-horse#179

**Comment by Floriferous** [comment]
@maxnowack we've just discussed this same issue on the previous thread that concerned the `standard-minifier`, I'll continue here.

Here's what I tried:
- I made sure it wasn't due to the `standard-minifier` by switching it on and off.
- I added the `TOOL_NODE_FLAGS: "--max_old_space_size=4096"` to my `circle.yml` which did help the CI go beyond the out of memory point, but then it failed with this error:

Your build has exceeded the memory limit of 4G on 1 container. The results of this build are likely invalid. We have taken a snapshot of the memory usage at the time, which you can find in a build artifact named memory-usage.txt. The RSS column in this file shows the amount of memory used by each process, measured in kilobytes.

Here's the memory-usage.txt if it is of any use:
```
PID   RSS %CPU COMMAND
 16109 3431880 100 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node --expose-gc --max_old_space_size=4096 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/index.js test --settings settings-dev.json --once --driver-package dispatch:mocha
 16860 455008 89.4 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /tmp/meteor-test-runb4d8ma/.meteor/local/build/main.js
 12241 183352 0.0 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock
 16098 98152  0.1 node /home/ubuntu/.yarn/bin/yarn.js run test-CI
 16138 57292  0.9 /home/ubuntu/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod --bind_ip 127.0.0.1 --port 3001 --dbpath /tmp/meteor-test-runb4d8ma/.meteor/local/db --oplogSize 8 --replSet meteor --nojournal
  1478 51056  0.2 /usr/bin/mongod --config /etc/mongod.conf
 16537 36120  0.4 /usr/lib/erlang/erts-5.10.4/bin/beam.smp -Bd -K true -A 4 -- -root /usr/lib/erlang -progname erl -- -home /var/lib/couchdb -- -noshell -noinput -os_mon start_memsup false start_cpu_sup false disk_space_check_interval 1 disk_almost_full_threshold 1 -sasl errlog_type error -couch_ini /etc/couchdb/default.ini /etc/couchdb/local.ini -s couch
    42 20052  0.0 Xvfb :99 -screen 0 1280x1024x24
 12308 16940  0.0 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
  1417  4556  0.0 xfwm4 --daemon
  2781  4048  0.0 sshd: ubuntu [priv] 
  2835  3236  0.0 sshd: ubuntu@pts/7  
  1839  3064  0.0 /usr/sbin/sshd -D
     1  2924  0.0 /sbin/init
 12313  2760  0.0 postgres: 9.5/main: autovacuum launcher process                                                                             
  1416  2608  0.0 /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd
  1647  2412  0.0 dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
  5142  1964  0.0 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 116:123
 12310  1916  0.0 postgres: 9.5/main: checkpointer process                                                                                    
 12314  1816  0.0 postgres: 9.5/main: stats collector process                                                                                 
 16523  1708  0.0 su couchdb -c /usr/bin/couchdb
 12311  1704  0.0 postgres: 9.5/main: writer process                                                                                          
 12312  1700  0.0 postgres: 9.5/main: wal writer process                                                                                      
 16565  1516  0.0 /lib/systemd/systemd-logind
  1407  1460  0.0 /lib/systemd/systemd-udevd --daemon
  1483  1220  0.0 /usr/sbin/irqbalance
 16876  1168  0.0 ps -e -o pid,rss,%cpu,command --sort -rss
 16566  1152  0.0 rsyslogd
 16525  1084  0.0 dbus-daemon --system --fork
  1452  1044  0.0 cron
  1414   988  0.0 //bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
  1549   960  0.0 dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dnsmasq.pid --conf-file= --listen-address 10.0.4.1 --dhcp-range 10.0.4.2,10.0.4.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=lxcbr0 --dhcp-leasefile=/var/lib/misc/dnsmasq.lxcbr0.leases --dhcp-authoritative
  7622   872  0.0 /sbin/getty -8 38400 tty1
  1420   868  0.0 /sbin/getty -8 38400 tty4
  1428   868  0.0 /sbin/getty -8 38400 tty3
  7617   864  0.0 /sbin/getty -8 38400 console
  1427   856  0.0 /sbin/getty -8 38400 tty2
 11989   748  0.0 /bin/sh /usr/bin/mysqld_safe
  1413   732  0.0 dbus-launch --autolaunch 54f9f16cebc74faf7c49864956cb7375 --binary-syntax --close-stderr
 16108   668  0.0 sh -c TEST_BROWSER_DRIVER=nightmare SERVER_TEST_REPORTER=xunit XUNIT_FILE=$CIRCLE_TEST_REPORTS/reports/unit.xml meteor test --settings settings-dev.json --once --driver-package dispatch:mocha
 15618   660  0.0 /bin/sh /home/ubuntu/.yarn/bin/yarn run test-CI
   343   652  0.0 upstart-socket-bridge --daemon
  1403   652  0.0 upstart-udev-bridge --daemon
 16724   652  0.0 sh -s disksup
  1451   644  0.0 acpid -c /etc/acpi/events -s /var/run/acpid.socket
 16561   644  0.0 upstart-file-bridge --daemon
  6798   524  0.0 ssh-agent
  1453   160  0.0 atd
```

- Finally, as per @abernix's recommendation, I added `meteor npm install --global source-map@0.5.6`. 

The full output of that command is the following (didn't include npm 5 upgrade ad):
```
meteor npm install --global source-map@0.5.6
/home/ubuntu/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib
└── source-map@0.5.6 
```

**Comment by abernix** [comment]
Thanks, @Floriferous.

For completeness, this refers to: https://github.com/meteor/meteor/issues/8157#issuecomment-328867440 (which wasn't the issue linked to above. :wink:)

I don't have any additional thoughts at the moment, unfortunately.

**Comment by lightpriest** [comment]
I'm having the same problem now (with CircleCI), which I assume is because the process exceeds the available memory. The line under `JS stack trace` also references `source-map`, but a different location.
This also happens when running the `test` command, but I suspect the build won't be any different.

@abernix Do you have any tips on debugging or taking a heapdump of the build/compile process?

**Comment by abernix** [comment]
@lightpriest A core dump should be produced if you run `ulimit -c unlimited` immediately before the command that is failing **in the same shell**, but there are lots of settings on CI which can hinder this.  Understand that my emphasis is because each command in the `circle.yml` YAML is ran in a different shell, meaning you'd need to do `ulimit -c unlimited && command` and then copy the `core` dump (if it exists) to artifacts.  I'll point out that a core dump can contain sensitive information if sensitive information was present in the environment, so it should only be exposed to someone who can be trusted!

You may find inspiration in [Meteor's CircleCI configuration](https://github.com/meteor/meteor/blob/devel/.circleci/config.yml#L275) which accomplishes this, though I'll point out that it's built for CircleCI 2.0 which most folks are not using.

**Comment by menelike** [comment]
Adding `TOOL_NODE_FLAGS="--max-old-space-size=4096 --optimize_for_size --gc-interval=100"` to global envs helped us when we hit memory boundaries in circle CI.

**Comment by yanickrochon** [comment]
This is an old project. I cannot use the `standard-minifier-js` neither the `bundle-visualizer` packages because of this. I either build for production without the minifier, or I add the `TOOL_NODE_FLAGS: "--max_old_space_size=4096"` environment variable, but still get a JS error when loading the app.

```
2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17 Uncaught ReferenceError: ge is not defined
    at 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17
    at 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17
    at locales.min.js (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17)
    at l (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15)
    at e (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15)
    at locales.js (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:149)
    at l (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15)
    at e (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15)
    at InventoryReservationForm.jsx (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:149)
    at l (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15)
(anonymous) @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17
(anonymous) @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17
locales.min.js @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:17
l @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
e @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
locales.js @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:149
l @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
e @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
InventoryReservationForm.jsx @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:149
l @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
e @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:15
(anonymous) @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:149
2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:87 Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
    at 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:87
    at s (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:1)
    at HTMLDocument.u (2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:1)
(anonymous) @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:87
s @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:1
u @ 2d3429dc62323cd0171102f6e423878da2b363a5.js?meteor_js_resource=true:1
```

**Comment by nate-strauser** [comment]
i started experiencing this problem yesterday on codeship - adding the command
```export TOOL_NODE_FLAGS="--max_old_space_size=4096"```
right before deployment has resolved the issue for me

i was not able to replicate the issue locally it only would occur on codeship builds

after upgrading to meteor 1.5.2.1, the issue has not returned

**Comment by derouck** [comment]
I had this issue on codeship and circleci with meteor 1.5.2.2

When I set the TOOL_NODE_FLAGS variable it seems fixed now.

**Comment by maxnowack** [comment]
`TOOL_NODE_FLAGS="--max_old_space_size=4096"` doesn't fix the issue on heroku for me.

**Comment by steve-ross** [comment]
Thanks for the tip on codeship, we too are seeing this on our production deployments

**Comment by jorgeer** [comment]
I get this error when rebuilding my unit tests. Only happened after upgrading to 1.5.2.1

**Comment by dancastellon** [comment]
I started getting this yesterday when deploying to Galaxy.

`export TOOL_NODE_FLAGS="--max_old_space_size=4096"`

Running that before the deploy command worked for me.

**Comment by abernix** [comment]
For everyone responding saying they're also experiencing this and that changing `max_old_space_size` fixes it for them, it would be even more helpful if you could also report if removing `standard-minifier-js` (or `abernix:standard-minifier-js`) _also_ fixes the problem (though you should continue to deploy to production with those packages present, of course, since minification is important!)

**Comment by dancastellon** [comment]
@abernix Removing `standard-minifier-js` also fixes the issue for me.

**Comment by yanickrochon** [comment]
Removing the `standard-minifier-js` package also worked for me because using the `TOOL_NODE_FLAGS` caused JavaScript errors (i.e. some undefined variable... not sure from which module since it's all uglified!). So I did deploy the few previous versions without minifying/uglifying the code. This, however, has for effect to be unable to use the `bundle-visualizer` package...

However, yesterday I tried `abernix:standard-minifier-js` and it seems to work, even without the flag. I got to try the `bundle-visualizer` for the first time. I haven't deployed anything, yet, but I'm confident that it will work. If not, I know what to do.

**Comment by derouck** [comment]
@abernix removing the standard-minifier-js package also fixes the problem - having the TOOL_NODE_FLAGS only fixes it from time to time it seems.

**Comment by abernix** [comment]
@derouck @yanickrochon @dancastellon:

Have you tried this with [Meteor 1.6](https://github.com/meteor/meteor/pull/8728)  (release candidate, not officially released)?  If not, it would be great if you could try and provide feedback on how it goes (*with* `standard-minifier-js` included, of course).

    meteor update --release 1.6-rc.8

**Comment by xavierpriour** [comment]
hi, just a confirmation that for me, switching to 1.6-rc.8 solved the issue (without changing anything else in the app). Thanks a lot for the fix!

**Comment by maxnowack** [comment]
1.6-rc.8 seems to work for me as well :)

**Comment by derouck** [comment]
I still get an error during the minification with 1.6-rc.8

**Comment by dweller23** [comment]
We've had a similar issue with same `process out of memory` outcome in Circle CI. 

What fixed the issue for us was realizing that circle.yml config should contain exact version of Meteor that is to be used (unless it's the most recent one) in case there is no cached Meteor (in exactly the version we want to use in the build) available.

The exact fix was adding to dependencies/override check if Meteor is available and if not then `curl https://install.meteor.com/?release=release_id_like | sh`

**Comment by derouck** [comment]
@dweller23 that's an interesting idea, i will try this asap

For me it seemed the issue remained there on 1.6 on circleCI, but in codeship it seemed solved. But both would still have been on 1.5.2.2 as installed meteor though. It became much slower as well on codeship though.

**Comment by sailorsenergy** [comment]
Just another data point. I started having this problem when I added the [analytics-node](https://github.com/segmentio/analytics-node) package to my Meteor 1.5.2.2 project yesterday. I can only get the project to deploy to Galaxy (`DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy app.myapp.com...`) when I remove the standard-minifier-js package.

**Comment by ffxsam** [comment]
I'm running into this issue suddenly. Literally the only package changes I've made is adding `paper` and `canvas`. No meteor packages have been updated and I'm on Meteor version 1.4.4.2 (this is intentional - this is a major application and last time I tried to update to 1.5, it broke everything, so I reverted).

```
Talking to Galaxy servers at https://us-east-1.galaxy-deploy.meteor.com
Deploying your app...
   Minifying app code                        /
<--- Last few GCs --->

  122285 ms: Scavenge 1396.5 (1454.8) -> 1396.5 (1454.8) MB, 6.2 / 0 ms (+ 5.2 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  123307 ms: Mark-sweep 1396.5 (1454.8) -> 1393.0 (1453.8) MB, 1022.0 / 0 ms (+ 88.9 ms in 548 steps since start of marking, biggest step 5.2 ms) [last resort gc].
  124330 ms: Mark-sweep 1393.0 (1453.8) -> 1395.5 (1454.8) MB, 1022.5 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2d92f8bb4629 <JS Object>
    1: parseLiteral [/Users/samh/.meteor/packages/standard-minifier-js/.2.0.0.8pd81e++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:~3708] [pc=0x3012703ceb9e] (this=0x75cbc7c4bf1 <a Parser with map 0x15a56b4d8541>,value=0x16120c5470a9 <String[3]: 2.0>,type=0x270f914a7a89 <String[13]: StringLiteral>,startPos=0x2d92f8b041...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
.scripts/deploy: line 12: 77509 Abort trap: 6           meteor deploy app.reelcrafter.com --settings settings.prod.json
```

I'm so frustrated with Meteor. This minifier/build process has been a constant struggle since 1.4.

**Comment by gary-menzel** [comment]
I am recently (today) having this problem doing a build with CircleCI with meteor@1.5.2.2

I've just done a local run with --production (without removing the standard-minifier) and get the error...

```
> MONGO_URL=mongodb://admin:admin@localhost:27017/meteor ROOT_URL=http://110.20.194.126:4700 meteor --port 4700 --settings dev-settings.json --production

Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/Desktop/meteor/sandpit ]]]]]

=> Started proxy.
   Minifying app code                        |
<--- Last few GCs --->

   99453 ms: Scavenge 1391.3 (1453.7) -> 1391.3 (1453.7) MB, 0.9 / 0 ms (+ 2.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  100520 ms: Mark-sweep 1391.3 (1453.7) -> 1388.7 (1453.7) MB, 1066.6 / 0 ms (+ 3.3 ms in 2 steps since start of marking, biggest step 2.1 ms) [last resort gc].
  101561 ms: Mark-sweep 1388.7 (1453.7) -> 1392.0 (1453.7) MB, 1041.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xb5f6a537399 <JS Object>
    1: get [/Users/gmenzel/.meteor/packages/standard-minifier-js/.2.1.2.xcktwo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-traverse/lib/path/index.js:~76] [pc=0x5ea69d37d3f] (this=0x3af468c11d39 <JS Function NodePath (SharedFunctionInfo 0x380b6bc22e69)>,_ref=0x466e805a101 <an Object with map 0x24ad166ea4f9>)
    2: node [/Users/gmen...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

Removing `standard-minifier-js` resolved the problem locally.

Adding `abernix:standard-minifier-js` successfully completed the build locally:

```
abernix:minifier-js@2.1.0
abernix:standard-minifier-js@2.1.0
```

Pushing the branch (with `abernix:standard-minifier-js`) to circleci also resulted in a successful build and deployment.

**Comment by yanickrochon** [comment]
I confirm that this issue is resolve with Meteor 1.6.0 for me. And the `bundle-visualizer` reports an initial bundle size significantly smaller than with Meteor 1.5 (2.88 MB => 1.88 MB) ! The app seemingly feels more responsive as well with async loading.

Great work guys!!!

**Comment by hwillson** [comment]
There are 2 main solutions listed in this issue thread:

1. Update to Meteor 1.6
2. If that doesn't work, use `abernix:standard-minifier-js` instead of `standard-minifier-js`.

Meteor 1.6, like `abernix:standard-minifier-js`, is using [`uglify-es`](https://www.npmjs.com/package/uglify-es). They're using different versions though, which helps explain why just updating to Meteor 1.6 isn't enough for everyone. PR https://github.com/meteor/meteor/pull/9368 brings the version of `uglify-es` being used by Meteor up to the latest and greatest, which includes numerous `uglify-es` bug fixes, so moving forward (after merged) there shouldn't be any reason to keep using `abernix:standard-minifier-js`. 

Given that the above solutions seem to address this issue for most people, and that an `uglify-es` update is pending, I'll close this issue for now. Thanks!

**Comment by lunafi-dorian** [comment]
I would like to add some more information here as well because I noticed no one mentioned `--production` flag when npm installing.

## Setup:
Circle 2.0
Meteor 1.6.1 w/ standard-minifier@2.2.0

## Attempts
1. Doing nothing, gave me the `JS stack trace` issue other people found.
2. Adding the `TOOL_NODE_FLAGS="--max-old-space-size=4096` as an `ENV` in`config.yml` just killed it because it ran out of mem
3. Deleting the standard-minifier got it to **work** w/ tool_node_flags on and off, but that's **lame**.
4. I _didn't_ try the `abernix:standard-minifier-js` because @hwillson already merged the changes for `standard-minifier-js`, so I will wait to test that in next [release](https://github.com/meteor/meteor/milestone/40).

## Solution
4. I **wasn't** running the `--production` flag when npm installing. Changing it to `meteor npm i --production` worked w/ tool_node_flags *on*

**Comment by xquadradpi** [comment]
Hey Guys, sorry for reactivating this but im not able to get my docker running always facing the same problem.

I am using Meteor 1.6.1.1 with following packages:

```
meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
reactive-var@1.0.11           # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-js

es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.10.6             # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command
angular-compilers
server-render@0.3.0

npm-bcrypt@0.9.3
accounts-base@1.4.2
accounts-password@1.5.0
accounts-google@1.3.1
erasaur:meteor-lodash
froala:editor
service-configuration@1.0.11
mys:fonts
generalledger:sleepforms
```

and  

```
"dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@angular/platform-server": "^5.2.10",
    "@angular/router": "^5.2.10",
    "@babel/runtime": "^7.0.0-beta.46",
    "@types/lodash": "^4.14.108",
    "angular-date-value-accessor": "0.0.2",
    "angular-froala-wysiwyg": "^2.8.1",
    "bcrypt": "^2.0.1",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.6",
    "lodash": "^4.17.10",
    "meteor-node-stubs": "~0.3.3",
    "meteor-rxjs": "^0.4.11",
    "rxjs": "^5.5.10",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.10",
    "@types/chai": "^4.1.3",
    "@types/meteor": "^1.4.15",
    "@types/mocha": "^2.2.44",
    "@types/sinon": "^4.3.1",
    "chai": "^4.1.2",
    "sinon": "^4.5.0",
    "typescript": "^2.8.3",
    "node-sass": "^4.9.0",
    "raw-loader": "^0.5.1",
    "less": "^3.0.4",
    "sass-loader": "^7.0.1",
    "webpack": "^4.8.0"
  }

```

Locally its all fine working great,
but when i try to build a docker its not working...


i have tryed using `TOOL_NODE_FLAGS="--max-old-space-size=4096` with every ammount of space...

i have tryed replacing `standard-minifier-js` with `abernix:standard-minifier-js`

All not working :( 
Please help me, 
im trying to get it working for 3 days now and just found out, docker build is working as long as there are no additional packages included


> [client]: SCSS Files Compilation: 128.250ms
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: 
> <--- Last few GCs --->
> 
> [4894:0x3af1820]   194343 ms: Mark-sweep 1580.5 (1703.6) -> 1580.4 (1703.6) MB, 1234.5 / 0.1 ms  allocation failure GC in old space requested
> [4894:0x3af1820]   195856 ms: Mark-sweep 1580.4 (1703.6) -> 1580.4 (1668.1) MB, 1512.4 / 0.0 ms  last resort GC in old space requested
> [4894:0x3af1820]   197239 ms: Mark-sweep 1580.4 (1668.1) -> 1580.4 (1664.1) MB, 1382.4 / 0.0 ms  last resort GC in old space requested
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x3c3995a57c1 <JSObject>
>     1: ReferencedIdentifier [/root/.meteor/packages/angular-compilers/.0.3.1_2.1wen3kj.2nxv++os+web.browser+web.cordova/plugin.Angular_Compilers.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/scope/index.js:~91] [pc=0x14efe8beb831](this=0x3dfaad48c2a9 <Object map = 0x16bd98cd0389>,path=0x29f768e4e169 <NodePath map = 0x17437cd89269>,state=0x3dfaad48c2a9 <Object map = 0x...
> 
> node::Abort() [/root/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
>  2: 0x125c56c [/root/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]

**Comment by adamgins** [comment]
@xquadradpi did you solve this? Are you using the CI option on cloud.docker.com?

I am getting `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by AndrewMorsillo** [comment]
@xquadradpi I'm running into the same thing on docker. Trying to build a nearly empty meteor app fails with OOM even with max_old_space_size=4096.

**Comment by adamgins** [comment]
Same. I have had to move back to Meteor 1.6.1, as I cannot get 1.7.1 deployed. Even 1.6.1 I hit the issues. Just as a test you can try removing the minifiers as they seem to chew up a heap of memory

@AndrewMorsillo  see this https://forums.meteor.com/t/meteor-docker-image-build-failed-with-server-pointing-to-localhost/45121/7 I changed the Docker memory on my machine and it fixed it

Also linking this issue https://github.com/meteor/meteor/issues/10218

**Comment by gokhanmelma** [comment]
If you are on React application, this should work:

`react-scripts --max_old_space_size=4096 start`

**Comment by mubeenyasin72** [comment]
> export TOOL_NODE_FLAGS="--max_old_space_size=4096

i also get the same error and the solution provide above not work for me
