### ISSUE TITLE
React 16.x dead code elimination error in production

### ISSUE THREAD

**Issue by uiii** [meteor/meteor#9260]
# Actual behavior
When I run production build (`meteor --production` or bundle after `meteor build`) with React 16.x as NPM dependency I get this error: `React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build`

# Expected behaviour
The meteor's minifier eliminates the dead code or use the production version of react.

# Info
Meteor version: 1.5.2.2
React version: 16.0.0
OS: Windows 10 (x64)

# Reproduction
1. create new meteor project
2. `npm install react react-dom`
3. replace `main.html` with:
```html
<head>
  <title>Meteor</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  <div id="root"></div>
</body>
```
4. replace `main.js` with
```js
import {Meteor} from 'meteor/meteor';
import * as React from 'react';
import * as ReactDOM from 'react-dom';

Meteor.startup(() => {
	ReactDOM.render(<div>hello</div>, document.getElementById('root'));
});
```
5. run `meteor --production`

# Note
React 15.x doesn't print the error, but I don't know if the React's production version is used.

**Comment by tomscholz** [comment]
I am also experiencing this with meteor v1.6-rc.16

**Comment by chenhaoact** [comment]
me too ,with React version 16.0.0

**Comment by jjjkkklll** [comment]
try the latest meteor version, which is 1.6. As far as I know, it is fixed in the final release.

**Comment by bmanturner** [comment]
Still an issue for me, even with 1.6.

**Comment by benjamn** [comment]
If you're using Meteor 1.6 and you run
```sh
meteor update minifier-js standard-minifier-js
```
you should now get version 2.2.1 of both packages, which should fix this problem. See commit 9e65d8bea72068f042b41ffa0df55791b4c7d71f for details.

**Comment by abredykhin** [comment]
I still see this problem whenever i run my pretty simple project with ```meteor --production```. I use v1.6.0.1 of meteor, and run ```meteor update minifier-js standard-minifier-js```. In the ```.meteor/packages``` i see that I use up-to-date versions of minifier: ```standard-minifier-css@1.3.5   # CSS minifier run for production mode
standard-minifier-js@2.2.3    # JS minifier run for production mode
```

**Comment by paulincai** [comment]
@benjamn 
I used Meteor 1.6.0.1 until yesterday. I didn't see it in prod or dev. Updated to 1.6.1-rc6 and minifiers are at standard-minifier-js@2.3.1-rc161.6.

I see the message on Dev on my station but production in Heroku looks ok.
