### ISSUE TITLE
Dead code elimination during minification does not prune module dependency graph.

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor#9388]
Now that the `uglify-es` minifier performs dead code elimination for production builds (see https://github.com/meteor/meteor/commit/9e65d8bea72068f042b41ffa0df55791b4c7d71f), it's possible that entire module dependency trees will disappear as a result of minification.

We don't currently take full advantage of this pruning, because the `ImportScanner` runs before the minifier. For example, when using React 16 in production, both `react/cjs/react.production.min.js` and `react/cjs/react.development.js` are bundled, though thankfully `react.development.js` is wrapped with an `if (process.env.NODE_ENV !== "production")` check, which can be dead-code-eliminated by the minifier. Other packages may not have the same layers of defense, so we should do the smart thing in all cases, if possible.

Fixing this won't be trivial, but it should have a big impact, and may dovetail nicely with the advanced tree shaking that I described [here](https://github.com/meteor/meteor-feature-requests/issues/206#issuecomment-341117517).

**Comment by bsbechtel** [comment]
@benjamn We are seeing an issue with React 16 not importing a module only in production, making it very hard to debug. Is it possible this module being eliminated is related to this issue?

**Comment by hwillson** [comment]
@bsbechtel The issue you're encountering shouldn't be related to this. The changes being discussed here haven't been implemented yet, and the changes in https://github.com/meteor/meteor/commit/9e65d8bea72068f042b41ffa0df55791b4c7d71f are scheduled to be released with Meteor 1.6.1.

**Comment by openmedi** [comment]
It seems to me that this is still not done in Meteor 1.8.1 and standard-minifier-js@2.4.1. Is this true or am I doing something wrong?

**Comment by ivan133** [comment]
So this should be fixed in 1.11 right?

**Comment by micnic** [comment]
Is there any progress in this direction? Still reproducible in Meteor 2.5
